"""The guard that notices when nothing reviewed a pull request.

Between 2026-08-22 and 2026-08-24, twenty-six consecutive pull requests merged
with no review at all. Sourcery had run out of weekly quota and was answering

    Sorry @blooop, you have reached your weekly rate limit of 500000 diff
    characters.

-- posted *as a review*. So a reader looking for one found one, the merge path
was satisfied, and the outage was invisible for a day and a half. The largest
changes in the repo went through in that window, including a breaking CLI
grammar change and a 1,862-line feature withdrawn again twenty-two hours later.

The question asked here is **"was this reviewed"**, not "did Sourcery answer".
A weekly quota outage lasts a week, and a guard that stops every merge for a
week is a guard that gets deleted -- which is the failure mode `test_bench_
workflow.py` and `test_readme_cli_doc.py` both write about. So a `wf-review`
report by the author satisfies it: that is the review this repo actually runs
when the bot is out, and it is a two-axis report written in fresh context, not
an "lgtm" from the person who wrote the code.

The strings below are real: both refusals verbatim from those pull requests, the
real "reviewed your changes and they look great" Sourcery posts when it found
nothing, and the real provenance line every `wf-review` report opens with.
"""

import json
import os
import subprocess
from pathlib import Path

ROOT = Path(__file__).parent.parent
VERDICT = ROOT / "scripts" / "review_verdict.sh"
CI = ROOT / ".github" / "workflows" / "ci.yml"
JOB = "review"

AUTHOR = "blooop"
BOT = "sourcery-ai[bot]"
HUMAN = "someone-else"

# Verbatim from PRs #343-#368 and #370-#376.
WEEKLY_QUOTA = (
    "Sorry @blooop, you have reached your weekly rate limit of 500000 diff "
    "characters.\n\nPlease try again later or [upgrade](https://app.sourcery.ai/login)"
)
# Verbatim from PR #369, the 1,631-line `--rm` grammar change.
OVER_DIFF_CAP = (
    "Sorry @blooop, your pull request is larger than the review limit of 150000 diff characters"
)
# Verbatim from PRs #330, #331, #333, #334, #337 and #342.
CLEAN = (
    "Hey - I've reviewed your changes and they look great!\n\n***\n\n"
    "<details><summary>Sourcery is free for open source</summary>"
)
FINDINGS = "Hey - I've found 2 issues\n\n## Individual Comments"
# The line every wf-review report opens with, verbatim from #331/#343/#348.
SELF_REVIEW = (
    "> *This was generated by AI during review.*\n\n"
    "Two independent axes, fresh context, fixed point `a1c6fe8...0d0e59a`.\n\n"
    "## Standards\n\nNo blocking findings.\n\n## Spec\n\n**Axis: pass.**\n\n"
    "## Verdict\n\n**Approve**"
)


def verdict(reviews, author=AUTHOR, head=None):
    """Run the real script.

    `reviews` is (author, body), (author, body, state) or
    (author, body, state, commit).
    """
    payload = [
        {
            "author": r[0],
            "body": r[1],
            "state": r[2] if len(r) > 2 else "COMMENTED",
            "commit": r[3] if len(r) > 3 else "",
        }
        for r in reviews
    ]
    env = {"PATH": os.environ["PATH"]}
    if author is not None:
        env["PR_AUTHOR"] = author
    if head is not None:
        env["PR_HEAD_SHA"] = head
    return subprocess.run(
        ["bash", str(VERDICT)],
        input=json.dumps(payload),
        capture_output=True,
        text=True,
        check=False,
        env=env,
    )


# --- what must still fail -------------------------------------------------


def test_a_quota_refusal_alone_is_not_a_review():
    result = verdict([(BOT, WEEKLY_QUOTA)])
    assert result.returncode == 1, "the outage that started this ran for 26 PRs"
    assert "no self-review to stand in for it" in result.stdout


def test_a_diff_cap_refusal_alone_is_not_a_review():
    # The worse of the two: it fires on size, so it exempts exactly the changes
    # that least tolerate going unread. #369 was 1,631 lines of CLI grammar.
    result = verdict([(BOT, OVER_DIFF_CAP)])
    assert result.returncode == 1


def test_no_reviews_at_all_is_not_a_review():
    for empty in ([], ""):
        result = verdict(empty) if empty == [] else verdict([])
        assert result.returncode == 1
        assert "Nothing reviewed" in result.stdout


def test_the_author_saying_lgtm_is_not_a_review():
    """A self-review counts, but only a real one.

    Without the provenance line this is the author approving their own code,
    which is the thing the guard exists to notice rather than a way past it.
    """
    result = verdict([(AUTHOR, "lgtm, merging")])
    assert result.returncode == 1


def test_a_refusal_plus_the_authors_lgtm_is_still_not_a_review():
    result = verdict([(BOT, WEEKLY_QUOTA), (AUTHOR, "looks fine to me")])
    assert result.returncode == 1


# --- what must pass -------------------------------------------------------


def test_a_self_review_stands_in_when_the_bot_is_out_of_quota():
    """The case this change exists for.

    A weekly quota outage must not stop a week of merges, so the wf-review
    report the repo already runs is what the merge rests on.
    """
    result = verdict([(BOT, WEEKLY_QUOTA), (AUTHOR, SELF_REVIEW)])
    assert result.returncode == 0, result.stdout
    assert "self-review" in result.stdout
    # And it is recorded, because merging on your own review is worth seeing
    # in the log afterwards.
    assert "::notice::" in result.stdout


def test_a_self_review_alone_passes():
    result = verdict([(AUTHOR, SELF_REVIEW)])
    assert result.returncode == 0, result.stdout


def test_a_review_that_found_nothing_passes():
    # The case that makes this usable rather than merely loud: most reviews find
    # nothing, and failing those would get the job deleted.
    result = verdict([(BOT, CLEAN)])
    assert result.returncode == 0, result.stdout


def test_a_review_that_found_something_passes():
    result = verdict([(BOT, FINDINGS)])
    assert result.returncode == 0, result.stdout


def test_a_human_review_passes_without_any_provenance_line():
    """A second party needs no marker. The line is only how an author's own
    review is told from an approval they typed themselves."""
    result = verdict([(HUMAN, "Checked the edge case, it's handled.")])
    assert result.returncode == 0, result.stdout


def test_a_second_party_beats_a_refusal_in_the_same_list():
    result = verdict([(BOT, WEEKLY_QUOTA), (HUMAN, "Fine by me.")])
    assert result.returncode == 0, result.stdout


# --- wiring ---------------------------------------------------------------


def test_the_gate_requires_the_job():
    ci = CI.read_text(encoding="utf-8")
    assert f"\n  {JOB}:\n" in ci, f"{JOB} is the job this file is about"
    needs = [line for line in ci.splitlines() if line.strip().startswith("needs: [ci,")]
    assert len(needs) == 1, (
        "expected exactly one `needs: [ci, ...]` line; reformatting it as a YAML "
        f"block list would make this guard silently stop looking. Found {len(needs)}"
    )
    needs = needs[0]
    assert JOB in needs, (
        "a job outside `gate`'s needs is not required by the branch ruleset, "
        "which is the same shape of nothing-gating-anything this guard catches"
    )


def test_the_workflow_runs_this_script_rather_than_its_own_copy():
    ci = CI.read_text(encoding="utf-8")
    assert "./scripts/review_verdict.sh" in ci, (
        "the classification must be the one under test; a copy inside a `run:` "
        "block is what goes stale"
    )


# --- the ordering defect, and the near-misses that pin the rule ---------------


# A review *of this guard* quotes the refusal sentences. The first wf-review
# report posted on the PR that introduced self-reviews was classified as a
# refusal and thrown away because `is_refusal` ran before the provenance check;
# the reviewer had to misspell both strings to get a report through.
REPORT_QUOTING_REFUSALS = (
    "> *This was generated by AI during review.*\n\n## Standards\n\n"
    "The guard matches `Sorry @blooop, you have reached your weekly rate limit "
    "of 500000 diff characters.` and `Sorry @blooop, your pull request is larger "
    "than the review limit of 150000 diff characters`.\n\n## Verdict\n\nApprove"
)


def test_a_self_review_that_quotes_the_refusals_is_still_a_self_review():
    result = verdict([(BOT, WEEKLY_QUOTA), (AUTHOR, REPORT_QUOTING_REFUSALS)])
    assert result.returncode == 0, (
        "a report is identified by who wrote it and its provenance line, not by "
        f"whether the prose mentions a refusal: {result.stdout}"
    )


def test_a_human_review_that_quotes_a_refusal_still_counts():
    result = verdict([(HUMAN, f"Sourcery said: {WEEKLY_QUOTA} — I read it instead.")])
    assert result.returncode == 0, result.stdout


def test_the_provenance_line_is_matched_tightly_enough_to_mean_something():
    """The near-miss that keeps `PROVENANCE` from being whittled down.

    Shortening the needle to `AI` left all thirteen original tests green while
    letting an author's "reviewed with AI help, lgtm" through — the exact
    approval the split between second-party and self-review exists to refuse.
    """
    for body in (
        "Reviewed with AI assistance. Verdict: approve.",
        "Reviewed by AI, lgtm.",
        "I used AI to check this. Looks good.",
        "generated during review",
        "This was generated by a human, during review.",
    ):
        result = verdict([(AUTHOR, body)])
        assert result.returncode == 1, f"{body!r} must not read as a wf-review report"


def test_an_empty_body_from_the_author_is_not_a_self_review():
    for body in ("", "   \n  "):
        assert verdict([(AUTHOR, body)]).returncode == 1


def test_an_unknown_pr_author_fails_closed():
    """Without `PR_AUTHOR` the script cannot tell a self-review from a second
    party, and the wrong guess is the one that lets something through."""
    result = verdict([(AUTHOR, "lgtm")], author=None)
    assert result.returncode == 1
    assert "PR_AUTHOR is empty" in result.stdout


def test_a_bare_approval_from_a_second_party_counts():
    """Somebody who read it and pressed Approve left no prose to measure."""
    assert verdict([(HUMAN, "", "APPROVED")]).returncode == 0


def test_a_dismissed_review_is_a_review_taken_back():
    assert verdict([(HUMAN, "Looks fine", "DISMISSED")]).returncode == 1


def test_changes_requested_counts_as_having_been_reviewed():
    """This gate asks whether anyone read the code, not whether they liked it.
    Blocking on unresolved change requests is the ruleset's job, not this one."""
    assert verdict([(HUMAN, "", "CHANGES_REQUESTED")]).returncode == 0


def test_an_empty_commented_review_from_a_second_party_does_not_count():
    """Somebody opened the review box, typed nothing and left no verdict.

    Not distinguishable from a drive-by without fetching the inline comments,
    and the direction to be wrong in is the one that asks for a review rather
    than the one that waves a PR through on an empty box. A reviewer who leaves
    only inline comments is the case this refuses; they can approve, request
    changes, or write a sentence.
    """
    assert verdict([(HUMAN, "", "COMMENTED")]).returncode == 1
    assert verdict([(HUMAN, "   \n ", "COMMENTED")]).returncode == 1


# --- staleness: warned, never failed -----------------------------------------


HEAD = "0d0e59a"
OLDER = "a1c6fe8"


def test_a_review_of_an_earlier_commit_still_passes_but_says_so():
    """A review of superseded code *did happen*, which is a different thing from
    the absence this guard catches. Failing it would mean re-reviewing after
    every typo fix — how a guard earns being deleted. It must not pass silently
    though: this exact case is how the change that added it reached its own
    merge."""
    result = verdict([(AUTHOR, SELF_REVIEW, "COMMENTED", OLDER)], head=HEAD)
    assert result.returncode == 0, result.stdout
    assert "::warning::" in result.stdout
    assert HEAD in result.stdout


def test_a_review_of_the_current_head_warns_about_nothing():
    result = verdict([(AUTHOR, SELF_REVIEW, "COMMENTED", HEAD)], head=HEAD)
    assert result.returncode == 0, result.stdout
    assert "::warning::" not in result.stdout


def test_one_review_at_head_is_enough_to_clear_the_warning():
    result = verdict(
        [
            (AUTHOR, SELF_REVIEW, "COMMENTED", OLDER),
            (HUMAN, "Re-checked at the new head.", "COMMENTED", HEAD),
        ],
        head=HEAD,
    )
    assert result.returncode == 0
    assert "::warning::" not in result.stdout


def test_without_a_head_sha_nothing_is_claimed_about_staleness():
    result = verdict([(AUTHOR, SELF_REVIEW, "COMMENTED", OLDER)])
    assert result.returncode == 0
    assert "::warning::" not in result.stdout


# --- the delta's own behaviour, each pinned because none of it was -------------


REFUSAL_THEN_REPORT = (
    f"{WEEKLY_QUOTA}\n\n> *This was generated by AI during review.*\n\n## Verdict\n\nApprove"
)


def test_a_report_that_opens_with_the_refusal_is_still_a_report():
    """A report is identified by who wrote it and its provenance line, whatever
    the prose says or where it says it.

    This passes under either ordering of the loop now, because `is_refusal` asks
    about the reviewer rather than about the text. It is kept as a statement of
    the property, not as a pin on the ordering — that ordering is deliberately no
    longer load-bearing, and the comment in the script says so.
    """
    assert verdict([(AUTHOR, REFUSAL_THEN_REPORT)]).returncode == 0


def test_only_the_reviewer_can_refuse_on_its_own_behalf():
    """Sniffing the prose was wrong twice in opposite directions: loose, it ate a
    report that quoted the refusal; anchored to `Sorry @`, it stopped recognising
    a refusal with a leading newline — strictly weaker than the loose match it
    replaced. The question is who wrote it, not what it says."""
    for lead in ("", "\n", " ", "## Review\n\n"):
        assert verdict([(BOT, lead + WEEKLY_QUOTA)]).returncode == 1, repr(lead)
    # A human quoting one is reviewing, not refusing. Broken under both previous
    # spellings of this function.
    assert verdict([(HUMAN, WEEKLY_QUOTA)]).returncode == 0
    assert verdict([(HUMAN, f"{WEEKLY_QUOTA}\n\nSo I read it myself.")]).returncode == 0


def test_a_pending_draft_review_is_not_a_review():
    """Only its author can see it."""
    assert verdict([(AUTHOR, SELF_REVIEW, "PENDING")]).returncode == 1
    assert verdict([(HUMAN, "Looks fine", "PENDING")]).returncode == 1


def test_a_stale_second_party_review_warns_too():
    """Half the staleness feature: dropping the notice from the second-party
    path left the suite green."""
    result = verdict([(HUMAN, "Fine by me.", "COMMENTED", OLDER)], head=HEAD)
    assert result.returncode == 0
    assert "::warning::" in result.stdout


def test_a_refusal_at_head_does_not_clear_the_staleness_warning():
    """Sourcery posts a refusal on every push, so counting refusals towards
    `at_head` would silence staleness permanently."""
    result = verdict(
        [(BOT, WEEKLY_QUOTA, "COMMENTED", HEAD), (AUTHOR, SELF_REVIEW, "COMMENTED", OLDER)],
        head=HEAD,
    )
    assert result.returncode == 0
    assert "::warning::" in result.stdout


def test_an_author_review_without_provenance_does_not_clear_it_either():
    result = verdict(
        [(AUTHOR, "lgtm", "COMMENTED", HEAD), (AUTHOR, SELF_REVIEW, "COMMENTED", OLDER)],
        head=HEAD,
    )
    assert result.returncode == 0
    assert "::warning::" in result.stdout


def test_the_workflow_passes_everything_the_script_reads():
    """All of the delta's wiring was untested: deleting `PR_HEAD_SHA` or
    reverting the jq map left the suite green while staleness stopped working
    and DISMISSED started counting."""
    ci = CI.read_text(encoding="utf-8")
    for field in ("author: .user.login", "body: .body", "state: .state", "commit: .commit_id"):
        assert field in ci, f"the script reads {field.split(':')[0]} and nothing supplies it"
    for env in ("PR_AUTHOR:", "PR_HEAD_SHA:"):
        assert env in ci, f"{env} is read by the script and must be set by the job"
