"""The guard that notices when nothing reviewed a pull request.

Between 2026-08-22 and 2026-08-24, twenty-six consecutive pull requests merged
with no review at all. Sourcery had run out of weekly quota and was answering

    Sorry @blooop, you have reached your weekly rate limit of 500000 diff
    characters.

-- posted *as a review*. So a reader looking for one found one, the merge path
was satisfied, and the outage was invisible for a day and a half. The largest
changes in the repo went through in that window, including a breaking CLI
grammar change and a 1,862-line feature withdrawn again twenty-two hours later.

The question asked here is **"was this reviewed"**, not "did Sourcery answer".
A weekly quota outage lasts a week, and a guard that stops every merge for a
week is a guard that gets deleted -- which is the failure mode `test_bench_
workflow.py` and `test_readme_cli_doc.py` both write about. So a `wf-review`
report by the author satisfies it: that is the review this repo actually runs
when the bot is out, and it is a two-axis report written in fresh context, not
an "lgtm" from the person who wrote the code.

The strings below are real: both refusals verbatim from those pull requests, the
real "reviewed your changes and they look great" Sourcery posts when it found
nothing, and the real provenance line every `wf-review` report opens with.
"""

import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).parent.parent
VERDICT = ROOT / "scripts" / "review_verdict.sh"
CI = ROOT / ".github" / "workflows" / "ci.yml"
JOB = "review"

AUTHOR = "blooop"
BOT = "sourcery-ai[bot]"
HUMAN = "someone-else"

# Verbatim from PRs #343-#368 and #370-#376.
WEEKLY_QUOTA = (
    "Sorry @blooop, you have reached your weekly rate limit of 500000 diff "
    "characters.\n\nPlease try again later or [upgrade](https://app.sourcery.ai/login)"
)
# Verbatim from PR #369, the 1,631-line `--rm` grammar change.
OVER_DIFF_CAP = (
    "Sorry @blooop, your pull request is larger than the review limit of 150000 diff characters"
)
# Verbatim from PRs #330, #331, #333, #334, #337 and #342.
CLEAN = (
    "Hey - I've reviewed your changes and they look great!\n\n***\n\n"
    "<details><summary>Sourcery is free for open source</summary>"
)
FINDINGS = "Hey - I've found 2 issues\n\n## Individual Comments"
# The line every wf-review report opens with, verbatim from #331/#343/#348.
SELF_REVIEW = (
    "> *This was generated by AI during review.*\n\n"
    "Two independent axes, fresh context, fixed point `a1c6fe8...0d0e59a`.\n\n"
    "## Standards\n\nNo blocking findings.\n\n## Spec\n\n**Axis: pass.**\n\n"
    "## Verdict\n\n**Approve**"
)


def verdict(reviews, author=AUTHOR):
    return subprocess.run(
        ["bash", str(VERDICT)],
        input=json.dumps([{"author": a, "body": b} for a, b in reviews]),
        capture_output=True,
        text=True,
        check=False,
        env={"PATH": __import__("os").environ["PATH"], "PR_AUTHOR": author},
    )


# --- what must still fail -------------------------------------------------


def test_a_quota_refusal_alone_is_not_a_review():
    result = verdict([(BOT, WEEKLY_QUOTA)])
    assert result.returncode == 1, "the outage that started this ran for 26 PRs"
    assert "no self-review to stand in for it" in result.stdout


def test_a_diff_cap_refusal_alone_is_not_a_review():
    # The worse of the two: it fires on size, so it exempts exactly the changes
    # that least tolerate going unread. #369 was 1,631 lines of CLI grammar.
    result = verdict([(BOT, OVER_DIFF_CAP)])
    assert result.returncode == 1


def test_no_reviews_at_all_is_not_a_review():
    for empty in ([], ""):
        result = verdict(empty) if empty == [] else verdict([])
        assert result.returncode == 1
        assert "Nothing reviewed" in result.stdout


def test_the_author_saying_lgtm_is_not_a_review():
    """A self-review counts, but only a real one.

    Without the provenance line this is the author approving their own code,
    which is the thing the guard exists to notice rather than a way past it.
    """
    result = verdict([(AUTHOR, "lgtm, merging")])
    assert result.returncode == 1


def test_a_refusal_plus_the_authors_lgtm_is_still_not_a_review():
    result = verdict([(BOT, WEEKLY_QUOTA), (AUTHOR, "looks fine to me")])
    assert result.returncode == 1


# --- what must pass -------------------------------------------------------


def test_a_self_review_stands_in_when_the_bot_is_out_of_quota():
    """The case this change exists for.

    A weekly quota outage must not stop a week of merges, so the wf-review
    report the repo already runs is what the merge rests on.
    """
    result = verdict([(BOT, WEEKLY_QUOTA), (AUTHOR, SELF_REVIEW)])
    assert result.returncode == 0, result.stdout
    assert "self-review" in result.stdout
    # And it is recorded, because merging on your own review is worth seeing
    # in the log afterwards.
    assert "::notice::" in result.stdout


def test_a_self_review_alone_passes():
    result = verdict([(AUTHOR, SELF_REVIEW)])
    assert result.returncode == 0, result.stdout


def test_a_review_that_found_nothing_passes():
    # The case that makes this usable rather than merely loud: most reviews find
    # nothing, and failing those would get the job deleted.
    result = verdict([(BOT, CLEAN)])
    assert result.returncode == 0, result.stdout


def test_a_review_that_found_something_passes():
    result = verdict([(BOT, FINDINGS)])
    assert result.returncode == 0, result.stdout


def test_a_human_review_passes_without_any_provenance_line():
    """A second party needs no marker. The line is only how an author's own
    review is told from an approval they typed themselves."""
    result = verdict([(HUMAN, "Checked the edge case, it's handled.")])
    assert result.returncode == 0, result.stdout


def test_a_second_party_beats_a_refusal_in_the_same_list():
    result = verdict([(BOT, WEEKLY_QUOTA), (HUMAN, "Fine by me.")])
    assert result.returncode == 0, result.stdout


# --- wiring ---------------------------------------------------------------


def test_the_gate_requires_the_job():
    ci = CI.read_text(encoding="utf-8")
    assert f"\n  {JOB}:\n" in ci, f"{JOB} is the job this file is about"
    needs = next(line for line in ci.splitlines() if line.strip().startswith("needs: [ci,"))
    assert JOB in needs, (
        "a job outside `gate`'s needs is not required by the branch ruleset, "
        "which is the same shape of nothing-gating-anything this guard catches"
    )


def test_the_workflow_runs_this_script_rather_than_its_own_copy():
    ci = CI.read_text(encoding="utf-8")
    assert "./scripts/review_verdict.sh" in ci, (
        "the classification must be the one under test; a copy inside a `run:` "
        "block is what goes stale"
    )
