//! Workspace identity: the one place a workspace id is derived.
//!
//! A workspace is identified by the triple `(owner, repo, ref)`. [`WorkspaceId`]
//! is the parsed form of that triple, and its [`value`](WorkspaceId::value) names
//! **both** the devpod workspace and the clone-directory leaf. Constructing a
//! `WorkspaceId` is the only way to derive an id from a triple, and constructing
//! one validates the triple, so no code path can reach a workspace clone
//! directory with an unvalidated ref.
//!
//! The id format is:
//!
//! ```text
//! <repo-slug>-<ref-slug>-<suffix>
//! ```
//!
//! `suffix` is eight characters of hashed identity and is never truncated.
//! `repo-slug` is the readable context and is cut to at most
//! [`REPO_SLUG_LENGTH`] characters, never shorter. `ref-slug` absorbs all
//! remaining truncation.
//!
//! **What truncation does and does not guarantee.** Only the slugs are ever
//! shortened, and the suffix is hashed over the full triple before any of that,
//! so truncating the readable part adds no collisions of its own: two triples
//! collide only when their suffixes collide. That is a birthday bound, not a
//! guarantee: distinct triples share an id with probability 2**-[`SUFFIX_BITS`]
//! per pair, so a large enough corpus will eventually produce one. At the earlier
//! 18-bit width a real pair did — `release/9999999999999999999999999176` and
//! `...234` in one repo — which is why the width is now 24. The property worth
//! relying on is the *independence*: truncation policy is a readability choice
//! with no effect on the collision rate.
//!
//! [`source_workspace_id`] covers git sources that name no ref (plain URL
//! specs), which cannot form a triple. Note that path specs (`dl ./some/dir`) do
//! not pass through this module at all — they reach devpod as a resolved
//! directory name — so an id handed to devpod is not necessarily one of these.
//!
//! See blooop/devlaunch#55 for the reasoning and #64 for the implementation
//! ticket.
//!
//! # Ported from `devlaunch/workspace_id.py`
//!
//! The derivation is reproduced byte for byte, pinned by golden vectors
//! generated by running the Python. Two of Python's regex behaviours are part of
//! that contract and are ported deliberately rather than tidied:
//!
//! - **`$` also matches before one trailing newline**, so `"x\n"` is a safe name
//!   while `"x\n\n"` and `"x\ny"` are not. The ref reaches the suffix hash
//!   verbatim, so tightening this would move ids Python already published.
//! - **`\w` under `re.UNICODE` is `str.isalnum()` plus `_`**, which is
//!   *category*-based (`L*`, `N*`). This port uses `char::is_alphanumeric()`,
//!   which is the `Alphabetic` property plus `N*` and therefore a strict
//!   superset: measured against Python 3.14 / UCD 16.0 it accepts 6167 more
//!   codepoints (4672 unassigned in the older UCD, 927 `Mn` and 438 `Mc`
//!   combining marks, 130 `So` enclosed letters). Every name Python accepts is
//!   accepted here and derives the same id, so no workspace on disk moves; the
//!   only difference is that a handful of names Python *refused* — an enclosed
//!   letter like `Ⓐ`, an Indic vowel sign like `ा`, a codepoint assigned after
//!   Python's UCD — are now accepted, and the slug rule erases all of them
//!   anyway. Plain combining accents (`U+0301` and friends) are *not* in that
//!   set: both runtimes refuse them, so an NFD ref is refused either way. Exact
//!   parity is not reachable without embedding a category table, and would not
//!   stay exact anyway — the `Cn` slice is Unicode version skew between the two
//!   runtimes, not a decision.
//!
//! `slug` needs no such caveat: it was checked against Python for all 1114112
//! codepoints and agrees on every one.

use std::fmt;

/// Total id budget. devpod's own ceiling is 48, but the setup pass's hostname
/// stage names the container after the workspace id, and downstream tooling
/// stacks prefixes and suffixes on it against a 64-byte limit
/// (kinisi-robotics/kinisi_ros#9766 already sat at 62/64). 48 is a ceiling
/// others eat into, not a budget to fill, so aim at 38.
pub(crate) const TARGET_LENGTH: usize = 38;

/// The repo slug is cut to this length when the id would otherwise overflow, and
/// is never cut below it. It carries no identity — only legibility — so trimming
/// it is safe, but trimming it to nothing would make `devpod list` unreadable.
pub(crate) const REPO_SLUG_LENGTH: usize = 20;

// 16 consonants x 4 vowels = 64 combinations = exactly 6 bits per syllable, so
// four syllables encode 24 bits of the digest in 8 pronounceable characters
// ("zovomobo", "hesirora", "lenevere") with no wordlist to keep in sync across
// languages.
//
// This was 3 syllables / 18 bits when the scheme was first decided. 18 bits put
// a birthday collision inside a single repo's plausible branch count — 500
// branches already produced one in test — so it was widened by one syllable. The
// extra two characters come out of the readable budget; the 38-char cap did not
// move.
const CONSONANTS: &[u8; 16] = b"bdfghjklmnprstvz";
const VOWELS: &[u8; 4] = b"aeio";
const SYLLABLES: usize = 4;

/// Bits of the digest the suffix encodes (6 per syllable).
///
/// Only this module's tests read it; the encoder walks the syllables instead.
#[cfg_attr(not(test), allow(dead_code))]
pub(crate) const SUFFIX_BITS: usize = SYLLABLES * 6;

/// Length of the identity-bearing suffix, in characters.
pub(crate) const SUFFIX_LENGTH: usize = SYLLABLES * 2;

/// Domain tag for ref-less sources, kept out of the triple's hash input so a URL
/// spec can never derive the same suffix as an `(owner, repo, ref)` workspace.
const SOURCE_KIND: &str = "source";

/// Which part of the triple was unsafe.
///
/// The part travels with the refusal because the caller renders it (Python's
/// `Invalid git {kind} name: ...`); core holds no user-facing English.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
// binary surface — not part of the frozen wf API (#251 §7)
pub enum NamePart {
    Owner,
    Repo,
    Ref,
}

/// A name that is not safe as a git ref or a path component.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
// binary surface — not part of the frozen wf API (#251 §7)
pub struct UnsafeName {
    pub part: NamePart,
    pub name: String,
}

/// Whether *name* is safe as a git ref and as a path component.
///
/// Starts with a word character (so it can never be read as a flag) and holds
/// only word characters, dots, slashes and dashes — Python's
/// `^[\w][\w./-]*$`, trailing-newline quirk included (see the module docs).
///
/// Bad input gets exactly one response in this codebase: it is rejected. The
/// previous split — one path raising while another coerced — meant the same bad
/// ref produced a hard error on one path and a silently different workspace on
/// another. Coercion is also what made the old derivation non-injective, since
/// five distinct refs coerced to one directory name. Rejecting is the honest
/// answer: a ref that is not a ref cannot be checked out later anyway, so the
/// only choice is where the user hears about it.
pub(crate) fn is_safe_name(name: &str) -> bool {
    let body = name.strip_suffix('\n').unwrap_or(name);
    let mut chars = body.chars();
    match chars.next() {
        Some(first) if is_word(first) => {}
        _ => return false,
    }
    chars.all(|c| is_word(c) || matches!(c, '.' | '/' | '-'))
}

fn is_word(c: char) -> bool {
    c == '_' || c.is_alphanumeric()
}

/// [`is_safe_name`] as a refusal that names the part it rejected.
pub(crate) fn validate_ref_name(name: &str, part: NamePart) -> Result<(), UnsafeName> {
    if is_safe_name(name) {
        Ok(())
    } else {
        Err(UnsafeName {
            part,
            name: name.to_string(),
        })
    }
}

/// Lowercase *text* and collapse every run of non-alphanumerics to one dash.
///
/// This is the only slug rule in devlaunch. It applies to the repo part and the
/// ref part alike, so `my_repo` becomes `my-repo` everywhere rather than
/// `my-repo` in one derivation and `myrepo` in another.
pub(crate) fn slug(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let mut in_run = false;
    for c in text.to_lowercase().chars() {
        if c.is_ascii_lowercase() || c.is_ascii_digit() {
            out.push(c);
            in_run = false;
        } else if !in_run {
            out.push('-');
            in_run = true;
        }
    }
    out.trim_matches('-').to_string()
}

/// Workspace id for a git source that names no ref, e.g. `github.com/owner/repo`.
///
/// A URL spec has no ref, so it cannot form an `(owner, repo, ref)` triple, but
/// it still reaches devpod as `--id`. It gets the same treatment as a triple:
/// slugged for legibility, suffixed for identity, capped at [`TARGET_LENGTH`]. A
/// bare slug would be both uncapped — a long URL reached 92 characters against
/// devpod's 48-char ceiling — and non-injective, since `my_repo`, `my-repo` and
/// `my.repo` all slug to the same string.
///
/// The hashed fields are the tag `"source"` and the lowercased *source*. The tag
/// keeps a ref-less source from ever sharing a suffix with a real workspace
/// triple. Lowercasing matches the triple's treatment of owner and repo: a host
/// is case-insensitive and so are GitHub owner and repo names, so two spellings
/// of one URL are one workspace.
pub(crate) fn source_workspace_id(source: &str) -> String {
    let suffix = syllable_suffix(&[SOURCE_KIND, &source.to_lowercase()]);
    let room = TARGET_LENGTH.saturating_sub(suffix.len() + 1);
    join(&[head(&slug(source), room).trim_matches('-'), &suffix])
}

/// A validated `(owner, repo, ref)` triple and the id derived from it.
///
/// Constructing this type is the parse boundary. It validates all three parts,
/// so holding a `WorkspaceId` is itself the evidence that the ref was checked —
/// no caller has to remember to validate, and no code path can skip it.
/// [`value`](Self::value) is the derived id, used verbatim as the devpod
/// workspace id and as the clone directory's leaf name.
///
/// The fields are private and there is no other constructor, which is what makes
/// an unvalidated triple unrepresentable rather than merely discouraged.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct WorkspaceId {
    owner: String,
    repo: String,
    git_ref: String,
}

impl WorkspaceId {
    /// Parse an unsanitized triple, or refuse it naming the part at fault.
    ///
    /// Parts are checked owner-first, because a caller that builds
    /// `repos_dir/<owner>/<repo>` needs the owner's verdict before it touches
    /// the filesystem.
    pub fn new(owner: &str, repo: &str, git_ref: &str) -> Result<Self, UnsafeName> {
        validate_ref_name(owner, NamePart::Owner)?;
        validate_ref_name(repo, NamePart::Repo)?;
        validate_ref_name(git_ref, NamePart::Ref)?;
        Ok(Self {
            owner: owner.to_string(),
            repo: repo.to_string(),
            git_ref: git_ref.to_string(),
        })
    }

    pub(crate) fn owner(&self) -> &str {
        &self.owner
    }

    pub(crate) fn repo(&self) -> &str {
        &self.repo
    }

    pub(crate) fn git_ref(&self) -> &str {
        &self.git_ref
    }

    /// The eight-character identity suffix. Never truncated.
    ///
    /// Owner and repo are lowercased before hashing because GitHub treats them
    /// case-insensitively: `NVIDIA/cuda-samples` and `nvidia/cuda-samples` are
    /// one repository, and giving each spelling its own id means one repo cloned
    /// twice into two containers. The ref is hashed verbatim — git refs really
    /// are case-sensitive, and `Main` and `main` can both exist in one repo.
    ///
    /// Lowercasing does not move ids for input that was already lowercase, which
    /// is every id this project has published.
    pub(crate) fn suffix(&self) -> String {
        syllable_suffix(&[
            &self.owner.to_lowercase(),
            &self.repo.to_lowercase(),
            &self.git_ref,
        ])
    }

    /// The derived id, at most [`TARGET_LENGTH`] characters.
    pub fn value(&self) -> String {
        let suffix = self.suffix();
        let mut repo_part = slug(&self.repo);
        // Cut the repo slug only when the id would otherwise overflow. Capping it
        // at REPO_SLUG_LENGTH leaves at least TARGET_LENGTH - 20 - 1 - 1 - 8 = 8
        // characters for the ref, so the ref budget can never go non-positive —
        // the hole that let a 47-char repo name skip truncation altogether.
        let untruncated = join(&[&repo_part, &fit_ref(&self.git_ref, TARGET_LENGTH), &suffix]);
        if untruncated.len() > TARGET_LENGTH {
            repo_part = head(&repo_part, REPO_SLUG_LENGTH)
                .trim_matches('-')
                .to_string();
        }
        let separators = if repo_part.is_empty() { 1 } else { 2 };
        let room = TARGET_LENGTH.saturating_sub(suffix.len() + repo_part.len() + separators);
        join(&[&repo_part, &fit_ref(&self.git_ref, room), &suffix])
    }
}

impl fmt::Display for WorkspaceId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.value())
    }
}

/// Eight characters of hashed identity for NUL-delimited *fields*.
///
/// The digest is taken over the fields joined by NUL, with no other
/// normalization applied here. The delimiter is what keeps field boundaries, so
/// `(a, bc)` stays distinct from `(ab, c)`; callers decide what to normalize
/// before calling.
///
/// This algorithm is frozen. Every workspace directory and devpod workspace on
/// disk is named by its output, so the tables, the syllable count, the digest,
/// the byte slice and the delimiter are all pinned by golden vectors taken from
/// the Python implementation.
fn syllable_suffix(fields: &[&str]) -> String {
    let digest = sha256(fields.join("\0").as_bytes());
    let mut head = [0u8; 8];
    head.copy_from_slice(&digest[..8]);
    let mut bits = u64::from_be_bytes(head);
    let mut out = String::with_capacity(SUFFIX_LENGTH);
    for _ in 0..SYLLABLES {
        out.push(CONSONANTS[((bits >> 2) & 15) as usize] as char);
        out.push(VOWELS[(bits & 3) as usize] as char);
        bits >>= 6;
    }
    out
}

/// Join non-empty *parts* with dashes, so an absent part leaves no stray dash.
fn join(parts: &[&str]) -> String {
    let mut out = String::new();
    for part in parts.iter().filter(|part| !part.is_empty()) {
        if !out.is_empty() {
            out.push('-');
        }
        out.push_str(part);
    }
    out
}

/// The first *n* characters of *s*, like Python's `s[:n]`.
fn head(s: &str, n: usize) -> &str {
    match s.char_indices().nth(n) {
        Some((end, _)) => &s[..end],
        None => s,
    }
}

/// Slug *git_ref* down to *room* characters, dropping whole segments first.
///
/// Refs are path-shaped, and their middle segments are usually taxonomy while
/// the ends carry the meaning. Truncating characters first turns
/// `dependabot/github_actions/codecov/codecov-action-6` into
/// `dependabot-github-actions-`, which says nothing about *which* action.
/// Dropping middle segments instead keeps `dependabot-codecov-action-6`.
fn fit_ref(git_ref: &str, room: usize) -> String {
    let mut segments: Vec<String> = git_ref
        .split('/')
        .map(slug)
        .filter(|segment| !segment.is_empty())
        .collect();
    while segments.len() > 2 && segments.join("-").len() > room {
        segments.remove(1);
    }
    head(&segments.join("-"), room)
        .trim_matches('-')
        .to_string()
}

/// SHA-256 (FIPS 180-4), because the frozen suffix is defined by this digest.
/// The `sha2` crate rather than a hand-rolled compression function: the golden
/// ids pin the output either way, and crypto primitives are the one place
/// "no dependency" costs more review than it saves.
fn sha256(message: &[u8]) -> [u8; 32] {
    use sha2::Digest;
    sha2::Sha256::digest(message).into()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    /// (owner, repo, ref) -> (suffix, value), straight out of the Python
    /// implementation. FROZEN: every workspace directory and devpod workspace
    /// on disk is named by this output.
    const GOLDEN_TRIPLES: &[(&str, &str, &str, &str, &str)] = &[
        (
            "blooop",
            "devlaunch",
            "main",
            "zovomobo",
            "devlaunch-main-zovomobo",
        ),
        (
            "blooop",
            "wayfinder",
            "main",
            "hesirora",
            "wayfinder-main-hesirora",
        ),
        (
            "blooop",
            "devlaunch",
            "feature/auth",
            "poliseno",
            "devlaunch-feature-auth-poliseno",
        ),
        (
            "blooop",
            "devlaunch",
            "feature-auth",
            "nesatabe",
            "devlaunch-feature-auth-nesatabe",
        ),
        (
            "blooop",
            "devlaunch",
            "feature.auth",
            "bahahefo",
            "devlaunch-feature-auth-bahahefo",
        ),
        (
            "blooop",
            "devlaunch",
            "feature_auth",
            "vakotite",
            "devlaunch-feature-auth-vakotite",
        ),
        (
            "blooop",
            "devlaunch",
            "featureauth",
            "mepediro",
            "devlaunch-featureauth-mepediro",
        ),
        (
            "blooop",
            "devlaunch",
            "Main",
            "zogizozi",
            "devlaunch-main-zogizozi",
        ),
        (
            "NVIDIA",
            "cuda-samples",
            "main",
            "libemaka",
            "cuda-samples-main-libemaka",
        ),
        (
            "nvidia",
            "cuda-samples",
            "main",
            "libemaka",
            "cuda-samples-main-libemaka",
        ),
        (
            "BlOoOp",
            "dEvLaUnCh",
            "main",
            "zovomobo",
            "devlaunch-main-zovomobo",
        ),
        (
            "owner",
            "My_Repo.git",
            "Feature/MyBranch",
            "rimivese",
            "my-repo-git-feature-mybranch-rimivese",
        ),
        (
            "blooop",
            "devlaunch",
            "dependabot/github_actions/codecov/codecov-action-6",
            "sifivasa",
            "devlaunch-dependabot-codecov-sifivasa",
        ),
        (
            "blooop",
            "devlaunch",
            "dependabot/github_actions/blooop/prek-action-2",
            "zakogozo",
            "devlaunch-dependabot-prek-act-zakogozo",
        ),
        (
            "blooop",
            "python_template",
            "dependabot/pip/lib/dependencies-1",
            "hinarami",
            "python-template-dependabot-de-hinarami",
        ),
        (
            "blooop",
            "lifetime_foc_rig",
            "dependabot/github_actions/codecov/codecov-action-6",
            "matagere",
            "lifetime-foc-rig-dependabot-c-matagere",
        ),
        (
            "kinisi-robotics",
            "kinisi_ros",
            "ags-devcontainer-tooling-support",
            "lenevere",
            "kinisi-ros-ags-devcontainer-t-lenevere",
        ),
        (
            "blooop",
            "devlaunch",
            "fix/gh-auth-in-devcontainer",
            "pedoveho",
            "devlaunch-fix-gh-auth-in-devc-pedoveho",
        ),
        (
            "blooop",
            "test_renv",
            "nb4",
            "polenita",
            "test-renv-nb4-polenita",
        ),
        (
            "blooop",
            "dl",
            "a/bbbbbbbb/cccccccc/dddddddd/zzz",
            "jobiriti",
            "dl-a-cccccccc-dddddddd-zzz-jobiriti",
        ),
        (
            "blooop",
            "dl",
            "aa/mmmmmmmmmmmmmmmmmmmmmmmmmmmmmm/nnnnnnnnnnnnnnnnnnnnnnnnnnnnnn/zz",
            "rakibasi",
            "dl-aa-zz-rakibasi",
        ),
        (
            "blooop",
            "devlaunch",
            "a//b///c/d",
            "hagoloke",
            "devlaunch-a-b-c-d-hagoloke",
        ),
        (
            "blooop",
            "devlaunch",
            "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            "zedabezi",
            "devlaunch-aaaaaaaaaaaaaaaaaaa-zedabezi",
        ),
        (
            "owner",
            "rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
            "main",
            "rerajezi",
            "rrrrrrrrrrrrrrrrrrrr-main-rerajezi",
        ),
        (
            "owner",
            "rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
            "a/very/long/branch/name/that/eats/the/budget",
            "bijizoli",
            "rrrrrrrrrrrrrrrrrrrr-a-budget-bijizoli",
        ),
        (
            "owner",
            "rrrrrrrrrrrrrrrrrrrr",
            "a/very/long/branch/name/that/eats/the/budget",
            "tafifipo",
            "rrrrrrrrrrrrrrrrrrrr-a-budget-tafifipo",
        ),
        (
            "owner",
            "repo",
            "release/9999999999999999999999999176",
            "sehirani",
            "repo-release-9999999999999999-sehirani",
        ),
        (
            "owner",
            "repo",
            "release/9999999999999999999999999234",
            "zivalero",
            "repo-release-9999999999999999-zivalero",
        ),
        ("a", "bc", "main", "bajovafa", "bc-main-bajovafa"),
        ("ab", "c", "main", "mofijihe", "c-main-mofijihe"),
        (
            "anyone",
            "github.com",
            "owner/repo",
            "vogasono",
            "github-com-owner-repo-vogasono",
        ),
        (
            "blooop",
            "a-repo-name-that-is-long",
            "feature/shared-prefix-1",
            "lapajiha",
            "a-repo-name-that-is-feature-s-lapajiha",
        ),
        (
            "blooop",
            "a-repo-name-that-is-long",
            "feature/shared-prefix-2",
            "sopalopi",
            "a-repo-name-that-is-feature-s-sopalopi",
        ),
        (
            "owner",
            "repo",
            "v1.2.3",
            "jozalali",
            "repo-v1-2-3-jozalali",
        ),
        (
            "owner",
            "repo",
            "release_1",
            "kihetira",
            "repo-release-1-kihetira",
        ),
        (
            "owner",
            "r",
            "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
            "sigivapa",
            "r-bbbbbbbbbbbbbbbbbbbbbbbbbbb-sigivapa",
        ),
        (
            "owner",
            "rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
            "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
            "bagakino",
            "rrrrrrrrrrrrrrrrrrrr-bbbbbbbb-bagakino",
        ),
        (
            "owner",
            "repo",
            "caf\u{e9}",
            "vodojage",
            "repo-caf-vodojage",
        ),
        (
            "owner",
            "repo",
            "\u{5206}\u{652f}",
            "gafafade",
            "repo-gafafade",
        ),
        (
            "owner",
            "repo",
            "\u{432}\u{435}\u{442}\u{43a}\u{430}",
            "dogedife",
            "repo-dogedife",
        ),
        (
            "owner",
            "repo",
            "\u{661}\u{662}\u{663}",
            "rolofito",
            "repo-rolofito",
        ),
        ("owner", "KKK", "main", "notitogi", "kkk-main-notitogi"),
        ("owner", "repo", "x\n", "vefidaze", "repo-x-vefidaze"),
        (
            "owner",
            "repo",
            "\u{130}stanbul",
            "zinimili",
            "repo-i-stanbul-zinimili",
        ),
        ("owner", "\u{212a}", "main", "javefiji", "k-main-javefiji"),
    ];

    /// source -> id, for git sources that name no ref.
    const GOLDEN_SOURCES: &[(&str, &str)] = &[
        ("github.com/owner/repo", "github-com-owner-repo-lokolede"),
        (
            "github.com/loft-sh/devpod",
            "github-com-loft-sh-devpod-vatomiha",
        ),
        (
            "gitlab.com/group/my_repo",
            "gitlab-com-group-my-repo-gaditizi",
        ),
        (
            "gitlab.com/group/my-repo",
            "gitlab-com-group-my-repo-ledorapa",
        ),
        (
            "gitlab.com/group/my.repo",
            "gitlab-com-group-my-repo-napasava",
        ),
        (
            "github.com/Blooop/DevLaunch",
            "github-com-blooop-devlaunch-lakatoje",
        ),
        (
            "github.com/blooop/devlaunch",
            "github-com-blooop-devlaunch-lakatoje",
        ),
        (
            "github.com/oooooooooooooooooooooooooooooooooooooooo/rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
            "github-com-oooooooooooooooooo-rasijome",
        ),
        (
            "github.com/oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo/rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
            "github-com-oooooooooooooooooo-bepolero",
        ),
        ("github.com/o/r", "github-com-o-r-deparori"),
        ("o", "o-rotebife"),
        (
            "github.com/owner/repo.git",
            "github-com-owner-repo-git-tefakojo",
        ),
        (
            "git@github.com:owner/repo.git",
            "git-github-com-owner-repo-git-vijisada",
        ),
        (
            "GIT@GitHub.COM:Owner/Repo",
            "git-github-com-owner-repo-natapake",
        ),
        ("github.com/owner/repo-", "github-com-owner-repo-fesihali"),
        ("-----", "fapijige"),
        ("", "serotizo"),
        ("\u{5206}\u{652f}", "gafalofi"),
    ];

    /// text -> slug.
    const GOLDEN_SLUGS: &[(&str, &str)] = &[
        ("main", "main"),
        ("Feature/MyBranch", "feature-mybranch"),
        ("my_repo", "my-repo"),
        ("python_template", "python-template"),
        ("v1.2.3", "v1-2-3"),
        ("--evil--", "evil"),
        ("a...b", "a-b"),
        ("", ""),
        ("-", ""),
        ("---", ""),
        ("MAIN", "main"),
        ("\u{dc}n\u{ef}c\u{f4}de", "n-c-de"),
        ("\u{5206}\u{652f}", ""),
        ("\u{212a}", "k"),
        ("\u{130}stanbul", "i-stanbul"),
        ("\u{3a3}\u{39f}\u{3a6}\u{39f}\u{3a3}", ""),
        ("a b c", "a-b-c"),
        ("\u{ff21}\u{ff22}\u{ff23}", ""),
        ("\u{ff11}\u{ff12}\u{ff13}", ""),
        ("\u{bd}", ""),
        ("\u{24b6}", ""),
        ("caf\u{e9}", "caf"),
        ("main\u{301}", "main"),
        ("x\n", "x"),
        ("x\n\n", "x"),
        ("a/b\n", "a-b"),
        ("x ", "x"),
        ("x\t", "x"),
    ];

    /// name -> whether Python's `^[\w][\w./-]*$` accepts it.
    const GOLDEN_SAFE_NAMES: &[(&str, bool)] = &[
        ("main", true),
        ("feature/my-branch", true),
        ("v1.2.3", true),
        ("release_1", true),
        ("a.b", true),
        ("a-b", true),
        ("a/b", true),
        ("_x", true),
        (".x", false),
        ("", false),
        ("--evil", false),
        ("-x", false),
        ("branch name", false),
        ("a;b", false),
        ("..", false),
        ("a%b", false),
        ("a b", false),
        ("a@b", false),
        ("a:b", false),
        ("a\\b", false),
        ("caf\u{e9}", true),
        ("\u{432}\u{435}\u{442}\u{43a}\u{430}", true),
        ("\u{5206}\u{652f}", true),
        ("\u{661}\u{662}\u{663}", true),
        ("\u{bd}", true),
        ("\u{b2}", true),
        ("\u{ff21}\u{ff22}\u{ff23}", true),
        ("\u{130}", true),
        ("\u{4e94}", true),
        ("x\n", true),
        ("x\n\n", false),
        ("\n", false),
        ("x\ny", false),
        ("x\r", false),
        ("x\r\n", false),
        ("main\n", true),
        ("a/b\n", true),
        ("x ", false),
        ("x\t", false),
        ("\u{212a}", true),
    ];

    /// Names Python refuses and this port accepts: see the module docs.
    const DIVERGENT_NAMES: &[&str] = &[
        "\u{24b6}",
        "x\u{24b6}",
        "\u{93e}",
        "x\u{93e}",
        "\u{5bf}",
        "x\u{903}",
    ];

    #[test]
    fn golden_triples_reproduce_the_python_derivation() {
        for &(owner, repo, git_ref, suffix, value) in GOLDEN_TRIPLES {
            let id = WorkspaceId::new(owner, repo, git_ref)
                .unwrap_or_else(|_| panic!("{owner}/{repo}@{git_ref:?} must parse"));
            assert_eq!(id.suffix(), suffix, "suffix for {owner}/{repo}@{git_ref:?}");
            assert_eq!(id.value(), value, "value for {owner}/{repo}@{git_ref:?}");
        }
    }

    #[test]
    fn golden_sources_reproduce_the_python_derivation() {
        for &(source, expected) in GOLDEN_SOURCES {
            assert_eq!(source_workspace_id(source), expected, "source {source:?}");
        }
    }

    #[test]
    fn golden_slugs_reproduce_the_python_slug_rule() {
        for &(text, expected) in GOLDEN_SLUGS {
            assert_eq!(slug(text), expected, "slug of {text:?}");
        }
    }

    #[test]
    fn golden_safe_names_reproduce_the_python_predicate() {
        for &(name, accepted) in GOLDEN_SAFE_NAMES {
            assert_eq!(
                is_safe_name(name),
                accepted,
                "safe-name verdict for {name:?}"
            );
        }
    }

    #[test]
    fn a_single_trailing_newline_is_accepted_like_pythons_dollar_anchor() {
        // `re.match(r"^[\w][\w./-]*$", "x\n")` matches: `$` also matches just before
        // one trailing newline. The port keeps the quirk rather than tightening it,
        // because the ref reaches the suffix hash verbatim and tightening would move
        // an id that Python already published.
        assert!(is_safe_name("x\n"));
        assert!(!is_safe_name("x\n\n"));
        assert!(!is_safe_name("x\ny"));
        assert!(!is_safe_name("\n"));
        let with_newline = WorkspaceId::new("owner", "repo", "x\n").expect("accepted");
        let without = WorkspaceId::new("owner", "repo", "x").expect("accepted");
        assert_ne!(with_newline.suffix(), without.suffix());
    }

    #[test]
    fn names_python_refuses_for_exotic_unicode_are_accepted_here() {
        // The measured divergence documented in the module docs. Every name Python
        // accepts, this port accepts and derives the same id for; the extra names are
        // combining marks, enclosed letters and codepoints Python's older UCD does
        // not know yet.
        for &name in DIVERGENT_NAMES {
            assert!(is_safe_name(name), "{name:?}");
        }
    }

    #[test]
    fn the_digest_matches_the_published_sha256_vectors() {
        assert_eq!(
            hex(&sha256(b"")),
            "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
        );
        assert_eq!(
            hex(&sha256(b"abc")),
            "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
        );
        assert_eq!(
            hex(&sha256(&[b'a'; 1000])),
            "41edece42d63e8d9bf515a9ba6932e1c20cbc9f5a5d134645adb5db1b9737ea3"
        );
    }

    fn hex(bytes: &[u8]) -> String {
        bytes.iter().map(|b| format!("{b:02x}")).collect()
    }

    fn id(owner: &str, repo: &str, git_ref: &str) -> WorkspaceId {
        WorkspaceId::new(owner, repo, git_ref).expect("the test triple is safe")
    }

    // ---- the suffix -------------------------------------------------------

    #[test]
    fn the_suffix_is_four_syllables() {
        assert_eq!(SUFFIX_LENGTH, 8);
        assert_eq!(SUFFIX_BITS, 24);
        assert_eq!(id("blooop", "devlaunch", "main").suffix().len(), 8);
    }

    #[test]
    fn the_suffix_alternates_consonant_and_vowel() {
        let suffix = id("blooop", "devlaunch", "main").suffix();
        assert_eq!(suffix.len(), SUFFIX_LENGTH);
        for (i, ch) in suffix.chars().enumerate() {
            let table = if i % 2 == 0 {
                "bdfghjklmnprstvz"
            } else {
                "aeio"
            };
            assert!(table.contains(ch), "{ch} at {i}");
        }
    }

    #[test]
    fn the_suffix_hashes_the_unsanitized_ref() {
        assert_ne!(
            id("blooop", "devlaunch", "feature/auth").suffix(),
            id("blooop", "devlaunch", "feature-auth").suffix()
        );
    }

    #[test]
    fn the_suffix_separates_the_triples_fields() {
        // The NUL delimiter keeps field boundaries; without it these would collide.
        assert_ne!(
            id("a", "bc", "main").suffix(),
            id("ab", "c", "main").suffix()
        );
    }

    // ---- owner and repo are case-insensitive ------------------------------

    const CASE_VARIANTS: &[(&str, &str)] = &[
        ("blooop", "devlaunch"),
        ("Blooop", "devlaunch"),
        ("blooop", "DevLaunch"),
        ("BLOOOP", "DEVLAUNCH"),
        ("BlOoOp", "dEvLaUnCh"),
    ];

    #[test]
    fn case_variants_of_one_repo_derive_one_id() {
        let ids: HashSet<String> = CASE_VARIANTS
            .iter()
            .map(|&(owner, repo)| id(owner, repo, "main").value())
            .collect();
        assert_eq!(ids.len(), 1);
    }

    #[test]
    fn case_variants_share_the_suffix() {
        let suffixes: HashSet<String> = CASE_VARIANTS
            .iter()
            .map(|&(owner, repo)| id(owner, repo, "main").suffix())
            .collect();
        assert_eq!(suffixes.len(), 1);
    }

    #[test]
    fn lowercase_input_is_unaffected_by_case_folding() {
        assert_eq!(id("blooop", "devlaunch", "main").suffix(), "zovomobo");
    }

    #[test]
    fn refs_stay_case_sensitive() {
        assert_ne!(
            id("blooop", "devlaunch", "main").value(),
            id("blooop", "devlaunch", "Main").value()
        );
    }

    #[test]
    fn the_nvidia_case_regression_stays_fixed() {
        assert_eq!(
            id("NVIDIA", "cuda-samples", "main").value(),
            id("nvidia", "cuda-samples", "main").value()
        );
    }

    // ---- the slug rule ----------------------------------------------------

    #[test]
    fn underscore_has_exactly_one_meaning() {
        assert_eq!(slug("my_repo"), "my-repo");
        assert!(
            id("owner", "my_repo", "main")
                .value()
                .starts_with("my-repo-")
        );
    }

    // ---- validation -------------------------------------------------------

    #[test]
    fn ordinary_refs_are_accepted() {
        for git_ref in ["main", "feature/my-branch", "v1.2.3", "release_1"] {
            assert_eq!(id("owner", "repo", git_ref).git_ref(), git_ref);
        }
    }

    #[test]
    fn unsafe_refs_are_refused_with_the_part_and_the_name() {
        for git_ref in ["", "--evil", "-x", "branch name", "a;b", "..", "a%b"] {
            assert_eq!(
                WorkspaceId::new("owner", "repo", git_ref),
                Err(UnsafeName {
                    part: NamePart::Ref,
                    name: git_ref.to_string(),
                }),
                "{git_ref:?}"
            );
        }
    }

    #[test]
    fn unsafe_owners_are_refused() {
        for owner in ["", "--evil", "own er"] {
            assert_eq!(
                WorkspaceId::new(owner, "repo", "main").map(|w| w.value()),
                Err(UnsafeName {
                    part: NamePart::Owner,
                    name: owner.to_string(),
                })
            );
        }
    }

    #[test]
    fn unsafe_repos_are_refused() {
        for repo in ["", "--evil", "re po"] {
            assert_eq!(
                WorkspaceId::new("owner", repo, "main").map(|w| w.value()),
                Err(UnsafeName {
                    part: NamePart::Repo,
                    name: repo.to_string(),
                })
            );
        }
    }

    #[test]
    fn the_owner_is_validated_before_the_repo_and_the_ref() {
        // Python validates owner, then repo, then ref, and dl.py reports the first
        // failure; a caller building repos_dir/<owner>/<repo> depends on the owner
        // being refused even when the ref is bad too.
        assert_eq!(
            WorkspaceId::new("../x", "..", "--evil"),
            Err(UnsafeName {
                part: NamePart::Owner,
                name: "../x".to_string(),
            })
        );
        assert_eq!(
            WorkspaceId::new("owner", "..", "--evil"),
            Err(UnsafeName {
                part: NamePart::Repo,
                name: "..".to_string(),
            })
        );
    }

    #[test]
    fn the_constructor_and_the_predicate_agree() {
        assert!(is_safe_name("main"));
        assert!(!is_safe_name("--evil"));
        assert!(WorkspaceId::new("owner", "repo", "main").is_ok());
        assert!(WorkspaceId::new("owner", "repo", "--evil").is_err());
    }

    // ---- injectivity ------------------------------------------------------

    #[test]
    fn slash_and_dash_refs_differ() {
        assert_ne!(
            id("blooop", "devlaunch", "feature/auth").value(),
            id("blooop", "devlaunch", "feature-auth").value()
        );
    }

    #[test]
    fn the_five_preimages_of_feature_auth_differ() {
        let ids: HashSet<String> = [
            "feature/auth",
            "feature-auth",
            "feature.auth",
            "feature_auth",
            "featureauth",
        ]
        .into_iter()
        .map(|git_ref| id("blooop", "devlaunch", git_ref).value())
        .collect();
        assert_eq!(ids.len(), 5);
    }

    #[test]
    fn refs_sharing_a_thirty_character_prefix_differ() {
        let prefix = "feature/a-very-long-branch-nam";
        assert_eq!(prefix.len(), 30);
        assert_ne!(
            id("blooop", "devlaunch", &format!("{prefix}e-one")).value(),
            id("blooop", "devlaunch", &format!("{prefix}e-two")).value()
        );
    }

    #[test]
    fn the_same_ref_in_a_different_repo_differs() {
        assert_ne!(
            id("blooop", "devlaunch", "main").value(),
            id("blooop", "wayfinder", "main").value()
        );
    }

    #[test]
    fn the_same_ref_under_a_different_owner_differs() {
        assert_ne!(
            id("blooop", "devlaunch", "main").value(),
            id("someone-else", "devlaunch", "main").value()
        );
    }

    #[test]
    fn truncation_contributes_no_collisions() {
        // 500 refs whose readable part truncates to one byte-identical string: the
        // number of distinct ids must equal the number of distinct suffixes, so
        // truncation adds nothing on top of the suffix's own birthday rate.
        let parsed: Vec<WorkspaceId> = (0..500)
            .map(|i| {
                id(
                    "blooop",
                    "a-repo-name-that-is-long",
                    &format!("feature/shared-prefix-{i}"),
                )
            })
            .collect();
        let readable: HashSet<String> = parsed
            .iter()
            .map(|w| drop_last_segment(&w.value()))
            .collect();
        assert_eq!(
            readable.len(),
            1,
            "the corpus must collide before truncation"
        );
        let values: HashSet<String> = parsed.iter().map(|w| w.value()).collect();
        let suffixes: HashSet<String> = parsed.iter().map(|w| w.suffix()).collect();
        assert_eq!(values.len(), suffixes.len());
    }

    fn drop_last_segment(value: &str) -> String {
        match value.rsplit_once('-') {
            Some((head, _)) => head.to_string(),
            None => value.to_string(),
        }
    }

    // ---- length -----------------------------------------------------------

    #[test]
    fn a_forty_seven_character_repo_fits() {
        let repo = "r".repeat(47);
        assert!(id("owner", &repo, "main").value().len() <= TARGET_LENGTH);
    }

    #[test]
    fn every_repo_length_fits() {
        for repo_len in 1..60 {
            let value = id("owner", &"r".repeat(repo_len), "some/long/branch/name-here").value();
            assert!(value.len() <= TARGET_LENGTH, "{repo_len}: {value}");
        }
    }

    #[test]
    fn every_ref_length_fits() {
        for ref_len in 1..80 {
            let value = id("owner", "devlaunch", &"b".repeat(ref_len)).value();
            assert!(value.len() <= TARGET_LENGTH, "{ref_len}: {value}");
        }
    }

    #[test]
    fn the_repo_slug_is_intact_up_to_twenty_characters() {
        let repo = "r".repeat(REPO_SLUG_LENGTH);
        let value = id(
            "owner",
            &repo,
            "a/very/long/branch/name/that/eats/the/budget",
        )
        .value();
        assert!(value.starts_with(&format!("{repo}-")), "{value}");
    }

    #[test]
    fn the_repo_slug_is_never_cut_below_twenty_characters() {
        let value = id(
            "owner",
            &"r".repeat(47),
            "a/very/long/branch/name/that/eats/the/budget",
        )
        .value();
        assert!(
            value.starts_with(&format!("{}-", "r".repeat(REPO_SLUG_LENGTH))),
            "{value}"
        );
    }

    #[test]
    fn the_suffix_is_never_truncated() {
        for repo_len in [1, 20, 47, 80] {
            let parsed = id("owner", &"r".repeat(repo_len), &"b".repeat(80));
            assert!(
                parsed.value().ends_with(&format!("-{}", parsed.suffix())),
                "{}",
                parsed.value()
            );
        }
    }

    #[test]
    fn a_constructed_id_is_lowercase_alphanumerics_and_dashes() {
        let value = id("Owner", "My_Repo.git", "Feature/MyBranch").value();
        assert!(
            value
                .chars()
                .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-'),
            "{value}"
        );
        assert!(!value.starts_with('-'));
        assert!(!value.ends_with('-'));
    }

    // ---- segment-aware truncation -----------------------------------------

    #[test]
    fn a_dependabot_ref_keeps_the_action_name() {
        let value = id(
            "blooop",
            "devlaunch",
            "dependabot/github_actions/codecov/codecov-action-6",
        )
        .value();
        assert!(value.contains("codecov"), "{value}");
        assert!(value.starts_with("devlaunch-dependabot-codecov"), "{value}");
        assert!(!value.contains("github-actions"), "{value}");
    }

    #[test]
    fn only_as_many_middle_segments_drop_as_needed() {
        let value = id("blooop", "dl", "a/bbbbbbbb/cccccccc/dddddddd/zzz").value();
        assert!(value.starts_with("dl-a-cccccccc-dddddddd-zzz-"), "{value}");
        assert!(!value.contains("bbbbbbbb"), "{value}");
    }

    #[test]
    fn the_first_and_last_segments_survive_heavy_truncation() {
        let git_ref = format!("aa/{}/{}/zz", "m".repeat(30), "n".repeat(30));
        let value = id("blooop", "dl", &git_ref).value();
        assert!(value.starts_with("dl-aa-zz-"), "{value}");
        assert!(
            !value.contains("mmmm") && !value.contains("nnnn"),
            "{value}"
        );
    }

    #[test]
    fn a_single_segment_ref_is_truncated_by_characters() {
        let value = id("blooop", "devlaunch", &"a".repeat(60)).value();
        assert!(value.starts_with("devlaunch-aaa"), "{value}");
    }

    #[test]
    fn dropping_segments_leaves_no_double_dashes() {
        let value = id("blooop", "devlaunch", "a//b///c/d").value();
        assert!(!value.contains("--"), "{value}");
    }

    // ---- ref-less sources -------------------------------------------------

    #[test]
    fn underscore_dash_and_dot_sources_stay_distinct() {
        let ids: HashSet<String> = [
            "gitlab.com/group/my_repo",
            "gitlab.com/group/my-repo",
            "gitlab.com/group/my.repo",
        ]
        .into_iter()
        .map(source_workspace_id)
        .collect();
        assert_eq!(ids.len(), 3);
    }

    #[test]
    fn every_source_length_is_capped() {
        for length in [1, 10, 40, 80, 200] {
            let source = format!("github.com/{}/{}", "o".repeat(length), "r".repeat(length));
            assert!(
                source_workspace_id(&source).len() <= TARGET_LENGTH,
                "{length}"
            );
        }
    }

    #[test]
    fn the_readable_prefix_of_a_source_survives() {
        assert!(
            source_workspace_id("github.com/loft-sh/devpod")
                .starts_with("github-com-loft-sh-devpod-")
        );
    }

    #[test]
    fn a_sources_suffix_is_present_and_full_width() {
        let value = source_workspace_id("github.com/owner/repo");
        let (_, suffix) = value.rsplit_once('-').expect("a suffix is joined on");
        assert_eq!(suffix.len(), SUFFIX_LENGTH);
    }

    #[test]
    fn source_case_is_folded() {
        assert_eq!(
            source_workspace_id("github.com/Blooop/DevLaunch"),
            source_workspace_id("github.com/blooop/devlaunch")
        );
    }

    #[test]
    fn a_source_id_cannot_collide_with_a_triple_id() {
        let triple = id("anyone", "github.com", "owner/repo");
        let source = source_workspace_id("github.com/owner/repo");
        assert_eq!(drop_last_segment(&source), "github-com-owner-repo");
        assert_eq!(drop_last_segment(&triple.value()), "github-com-owner-repo");
        assert_ne!(source, triple.value());
    }

    #[test]
    fn a_sources_id_is_deterministic() {
        assert_eq!(
            source_workspace_id("github.com/owner/repo"),
            source_workspace_id("github.com/owner/repo")
        );
    }

    // ---- determinism ------------------------------------------------------

    #[test]
    fn the_derivation_is_pure() {
        // Nothing here reads the environment, the working directory, the clock or a
        // randomised hash seed -- the module's only inputs are its arguments, which
        // is why Python needed a fresh-interpreter test and this does not. The
        // repeated call is the part still worth asserting.
        let first = id("blooop", "devlaunch", "main").value();
        let second = id("blooop", "devlaunch", "main").value();
        assert_eq!(first, second);
        assert_eq!(first, "devlaunch-main-zovomobo");
    }

    // ---- the real-world corpus -------------------------------------------

    #[test]
    fn the_real_world_corpus_is_unique_and_within_budget() {
        let ids: Vec<String> = GOLDEN_TRIPLES
            .iter()
            .map(|&(owner, repo, git_ref, _, _)| id(owner, repo, git_ref).value())
            .collect();
        for value in &ids {
            assert!(value.len() <= TARGET_LENGTH, "{value}");
        }
        // Two rows are deliberate case variants of one repo, so the corpus has
        // exactly two duplicate pairs.
        let distinct: HashSet<&String> = ids.iter().collect();
        assert_eq!(distinct.len(), ids.len() - 2);
    }

    #[test]
    fn a_short_repo_name_is_intact_in_the_corpus() {
        for &(owner, repo, git_ref, _, _) in GOLDEN_TRIPLES {
            let repo_slug = slug(repo);
            if repo_slug.len() <= REPO_SLUG_LENGTH && !repo_slug.is_empty() {
                let value = id(owner, repo, git_ref).value();
                assert!(value.starts_with(&format!("{repo_slug}-")), "{value}");
            }
        }
    }

    // ---- the parsed value itself ------------------------------------------

    #[test]
    fn display_is_the_id() {
        let parsed = id("blooop", "devlaunch", "main");
        assert_eq!(parsed.to_string(), parsed.value());
    }

    #[test]
    fn equality_is_by_triple() {
        assert_eq!(
            id("blooop", "devlaunch", "main"),
            id("blooop", "devlaunch", "main")
        );
        assert_ne!(
            id("blooop", "devlaunch", "main"),
            id("blooop", "devlaunch", "other")
        );
    }

    #[test]
    fn the_parsed_value_is_hashable() {
        let set: HashSet<WorkspaceId> = [
            id("blooop", "devlaunch", "main"),
            id("blooop", "devlaunch", "main"),
        ]
        .into_iter()
        .collect();
        assert_eq!(set.len(), 1);
    }

    #[test]
    fn the_triple_is_readable_back_off_the_parsed_value() {
        let parsed = id("blooop", "devlaunch", "feature/auth");
        assert_eq!(parsed.owner(), "blooop");
        assert_eq!(parsed.repo(), "devlaunch");
        assert_eq!(parsed.git_ref(), "feature/auth");
    }
}
