//! Workspace identity: the one place a workspace id is derived.
//!
//! A workspace is identified by the triple `(owner, repo, ref)`. [`WorkspaceId`]
//! is the parsed form of that triple, and its [`value`](WorkspaceId::value) names
//! **both** the devpod workspace and the clone-directory leaf. Constructing a
//! `WorkspaceId` is the only way to derive an id from a triple, and constructing
//! one validates the triple, so no code path can reach a workspace clone
//! directory with an unvalidated ref.
//!
//! The id format is:
//!
//! ```text
//! <repo-slug>-<ref-slug>-<suffix>
//! ```
//!
//! `suffix` is [`SUFFIX_LENGTH`] characters of hashed identity and is never
//! truncated. `repo-slug` is the readable context and is cut to at most
//! [`REPO_SLUG_LENGTH`] characters, never shorter. `ref-slug` absorbs all
//! remaining truncation.
//!
//! [`WorkspaceId::label`] is the same three pieces read for a person rather than
//! for devpod: `<repo-slug>@<ref-slug>`, no suffix. It is a second *rendering* and
//! not a second derivation, which is the property worth keeping: both come out of
//! one [`WorkspaceId::parts`], so a change to where the cuts fall moves the id and
//! the label together or not at all. Nothing addresses a workspace by a label and
//! it is not unique, which is what lets it drop the four characters that carry the
//! identity. See its own docs for where that is spent.
//!
//! **What truncation does and does not guarantee.** Only the slugs are ever
//! shortened, and the suffix is hashed over the full triple before any of that,
//! so truncating the readable part adds no collisions of its own: two triples
//! collide only when their suffixes collide *and* their readable halves cut to
//! the same string. That is a birthday bound, not a guarantee: a pair shares a
//! suffix with probability 1/[`SUFFIX_SPACE`], so a large enough corpus will
//! eventually produce one. At an earlier 18-bit width a real pair did —
//! `release/9999999999999999999999999176` and `...234` in one repo. The property
//! worth relying on is the *independence*: truncation policy is a readability
//! choice with no effect on the collision rate.
//!
//! **A collision is not caught today**, which is why the width is the whole of
//! the defence. Sharing an id means sharing one clone directory and one devpod
//! workspace, so the loser opens the winner's checkout with nothing said.
//! blooop/devlaunch#438 is the guard for that, and it is cheap because
//! [`WorktreeInfo`](crate::domain::model::WorktreeInfo) already stores the triple
//! beside the id derived from it. See [`SUFFIX_LENGTH`] for what the width is
//! chosen against in the meantime.
//!
//! [`source_workspace_id`] covers git sources that name no ref (plain URL
//! specs), which cannot form a triple. Note that path specs (`dl ./some/dir`) do
//! not pass through this module at all — they reach devpod as a resolved
//! directory name — so an id handed to devpod is not necessarily one of these.
//!
//! See blooop/devlaunch#55 for the reasoning and #64 for the implementation
//! ticket.
//!
//! # Ported from `devlaunch/workspace_id.py`
//!
//! The derivation is reproduced byte for byte, pinned by golden vectors
//! generated by running the Python. Two of Python's regex behaviours are part of
//! that contract and are ported deliberately rather than tidied:
//!
//! - **`$` also matches before one trailing newline**, so `"x\n"` is a safe name
//!   while `"x\n\n"` and `"x\ny"` are not. The ref reaches the suffix hash
//!   verbatim, so tightening this would move ids Python already published.
//! - **`\w` under `re.UNICODE` is `str.isalnum()` plus `_`**, which is
//!   *category*-based (`L*`, `N*`). This port uses `char::is_alphanumeric()`,
//!   which is the `Alphabetic` property plus `N*` and therefore a strict
//!   superset: measured against Python 3.14 / UCD 16.0 it accepts 6167 more
//!   codepoints (4672 unassigned in the older UCD, 927 `Mn` and 438 `Mc`
//!   combining marks, 130 `So` enclosed letters). Every name Python accepts is
//!   accepted here and derives the same id, so no workspace on disk moves; the
//!   only difference is that a handful of names Python *refused* — an enclosed
//!   letter like `Ⓐ`, an Indic vowel sign like `ा`, a codepoint assigned after
//!   Python's UCD — are now accepted, and the slug rule erases all of them
//!   anyway. Plain combining accents (`U+0301` and friends) are *not* in that
//!   set: both runtimes refuse them, so an NFD ref is refused either way. Exact
//!   parity is not reachable without embedding a category table, and would not
//!   stay exact anyway — the `Cn` slice is Unicode version skew between the two
//!   runtimes, not a decision.
//!
//! `slug` needs no such caveat: it was checked against Python for all 1114112
//! codepoints and agrees on every one.

use std::fmt;

/// Total id budget, one character inside devpod's own ceiling of 48.
///
/// 48 is hard and fatal: `devpod up --id` with a 49-character id is rejected
/// outright (`workspace name cannot be longer than 48 characters`, verified
/// against the pinned v0.26.1), so an id derived here that overshoots is a
/// launch that does not happen. 47 keeps one character of margin from that wall.
///
/// This was 38, for the reason it is still not 48: the setup pass names the
/// container out of this id, and downstream tooling stacks its own prefixes and
/// suffixes onto that name against a 64-byte limit (kinisi-robotics/kinisi_ros#9766
/// already sat at 62/64 with a 38-char id). Widening to 47 spent nine characters of
/// that reserve on legibility — branch names that used to lose their tail now keep
/// it.
///
/// **That reserve is the tight one again, and deliberately so.** The container's
/// hostname used to be the id's readable half, which topped a downstream caller out
/// at 38 and left about 26 bytes of the 64. The prompt, the tab and the `dl --ls`
/// row are one string now, the whole id, so what downstream builds on is 47 and the
/// reserve is 17. #9766's stack does not fit in 17. Nothing here can detect that:
/// the limit belongs to a consumer this crate has never heard of, and the symptom is
/// that consumer's rather than a launch that fails. It is written down because the
/// next person to widen this constant should know the slack was already spent once.
///
/// What holds the cap here is devpod's 48, which the id itself is measured against.
/// Nothing breaks at any value up to 48, and the id is a legal hostname at 47.
pub(crate) const TARGET_LENGTH: usize = 47;

/// The repo slug is cut to this length when the id would otherwise overflow, and
/// is never cut below it. It carries no identity — only legibility — so trimming
/// it is safe, but trimming it to nothing would make `devpod list` unreadable.
pub(crate) const REPO_SLUG_LENGTH: usize = 20;

/// The alphabet the suffix is spelled in: every character a DNS label allows
/// except `-`, which is the separator the id is joined on.
///
/// Base 36 is 5.17 bits per character. The scheme this replaced spelled the suffix
/// as consonant-vowel syllables drawn from a 16x4 table, which is 6 bits per *two*
/// characters, so 3.0 per character: it spent 42% of every character on being
/// pronounceable. Nothing reads a suffix aloud, and the characters it gives back go
/// to the ref slug, which people do read.
const SUFFIX_ALPHABET: &[u8; 36] = b"0123456789abcdefghijklmnopqrstuvwxyz";

/// Distinct suffixes: [`SUFFIX_ALPHABET`] to the [`SUFFIX_LENGTH`].
///
/// Only this module's tests and its prose read it; the encoder divides instead.
#[cfg_attr(not(test), allow(dead_code))]
pub(crate) const SUFFIX_SPACE: u64 = 36u64.pow(SUFFIX_LENGTH as u32);

/// Length of the identity-bearing suffix, in characters.
///
/// 4 characters is 20.7 bits, against the 24 the syllable scheme spent 8 characters
/// on and the 18 that demonstrably failed.
///
/// **The width is chosen against the population that actually contends for a
/// suffix, which is not the number of workspaces on the machine.** Two triples can
/// only collide when their readable halves truncate to the same string as well, so
/// the contending set is one repository's near-identical long refs:
/// `release/999…176` beside `release/999…234`, or a wall of dependabot branches. At
/// ten of those the collision probability is 0.003%, one in thirty-seven thousand.
/// The 500 that broke 18 bits would be 7% here, so this is a decision about a
/// workload rather than a constant to move on taste. A machine that grows corpora
/// of that shape wants 5 characters, which is 25.8 bits and still narrower than
/// what it replaced.
///
/// **The width is the whole of the defence, which is the part worth fixing.** A
/// collision is not detected, so the loser of one silently opens the winner's
/// checkout. blooop/devlaunch#438 is the guard, and it costs nothing to hold: the
/// triple is already stored beside the id it derived.
pub(crate) const SUFFIX_LENGTH: usize = 4;

/// Domain tag for ref-less sources, kept out of the triple's hash input so a URL
/// spec can never derive the same suffix as an `(owner, repo, ref)` workspace.
const SOURCE_KIND: &str = "source";

/// Which part of the triple was unsafe.
///
/// The part travels with the refusal because the caller renders it (Python's
/// `Invalid git {kind} name: ...`); core holds no user-facing English.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
// binary surface — not part of the frozen wf API (#251 §7)
pub enum NamePart {
    Owner,
    Repo,
    Ref,
}

/// A name that is not safe as a git ref or a path component.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
// binary surface — not part of the frozen wf API (#251 §7)
pub struct UnsafeName {
    pub part: NamePart,
    pub name: String,
}

/// Whether *name* is safe as a git ref and as a path component.
///
/// Starts with a word character (so it can never be read as a flag) and holds
/// only word characters, dots, slashes and dashes — Python's
/// `^[\w][\w./-]*$`, trailing-newline quirk included (see the module docs).
///
/// Bad input gets exactly one response in this codebase: it is rejected. The
/// previous split — one path raising while another coerced — meant the same bad
/// ref produced a hard error on one path and a silently different workspace on
/// another. Coercion is also what made the old derivation non-injective, since
/// five distinct refs coerced to one directory name. Rejecting is the honest
/// answer: a ref that is not a ref cannot be checked out later anyway, so the
/// only choice is where the user hears about it.
pub(crate) fn is_safe_name(name: &str) -> bool {
    let body = name.strip_suffix('\n').unwrap_or(name);
    let mut chars = body.chars();
    match chars.next() {
        Some(first) if is_word(first) => {}
        _ => return false,
    }
    chars.all(|c| is_word(c) || matches!(c, '.' | '/' | '-'))
}

fn is_word(c: char) -> bool {
    c == '_' || c.is_alphanumeric()
}

/// [`is_safe_name`] as a refusal that names the part it rejected.
pub(crate) fn validate_ref_name(name: &str, part: NamePart) -> Result<(), UnsafeName> {
    if is_safe_name(name) {
        Ok(())
    } else {
        Err(UnsafeName {
            part,
            name: name.to_string(),
        })
    }
}

/// Lowercase *text* and collapse every run of non-alphanumerics to one dash.
///
/// This is the only slug rule in devlaunch. It applies to the repo part and the
/// ref part alike, so `my_repo` becomes `my-repo` everywhere rather than
/// `my-repo` in one derivation and `myrepo` in another.
pub(crate) fn slug(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let mut in_run = false;
    for c in text.to_lowercase().chars() {
        if c.is_ascii_lowercase() || c.is_ascii_digit() {
            out.push(c);
            in_run = false;
        } else if !in_run {
            out.push('-');
            in_run = true;
        }
    }
    out.trim_matches('-').to_string()
}

/// Workspace id for a git source that names no ref, e.g. `github.com/owner/repo`.
///
/// A URL spec has no ref, so it cannot form an `(owner, repo, ref)` triple, but
/// it still reaches devpod as `--id`. It gets the same treatment as a triple:
/// slugged for legibility, suffixed for identity, capped at [`TARGET_LENGTH`]. A
/// bare slug would be both uncapped — a long URL reached 92 characters against
/// devpod's 48-char ceiling — and non-injective, since `my_repo`, `my-repo` and
/// `my.repo` all slug to the same string.
///
/// The hashed fields are the tag `"source"` and the lowercased *source*. The tag
/// keeps a ref-less source from ever sharing a suffix with a real workspace
/// triple. Lowercasing matches the triple's treatment of owner and repo: a host
/// is case-insensitive and so are GitHub owner and repo names, so two spellings
/// of one URL are one workspace.
pub(crate) fn source_workspace_id(source: &str) -> String {
    let suffix = hashed_suffix(&[SOURCE_KIND, &source.to_lowercase()]);
    let room = TARGET_LENGTH.saturating_sub(suffix.len() + 1);
    join(&[head(&slug(source), room).trim_matches('-'), &suffix])
}

/// A validated `(owner, repo, ref)` triple and the id derived from it.
///
/// Constructing this type is the parse boundary. It validates all three parts,
/// so holding a `WorkspaceId` is itself the evidence that the ref was checked —
/// no caller has to remember to validate, and no code path can skip it.
/// [`value`](Self::value) is the derived id, used verbatim as the devpod
/// workspace id and as the clone directory's leaf name.
///
/// The fields are private and there is no other constructor, which is what makes
/// an unvalidated triple unrepresentable rather than merely discouraged.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct WorkspaceId {
    owner: String,
    repo: String,
    git_ref: String,
}

impl WorkspaceId {
    /// Parse an unsanitized triple, or refuse it naming the part at fault.
    ///
    /// Parts are checked owner-first, because a caller that builds
    /// `repos_dir/<owner>/<repo>` needs the owner's verdict before it touches
    /// the filesystem.
    pub fn new(owner: &str, repo: &str, git_ref: &str) -> Result<Self, UnsafeName> {
        validate_ref_name(owner, NamePart::Owner)?;
        validate_ref_name(repo, NamePart::Repo)?;
        validate_ref_name(git_ref, NamePart::Ref)?;
        Ok(Self {
            owner: owner.to_string(),
            repo: repo.to_string(),
            git_ref: git_ref.to_string(),
        })
    }

    pub(crate) fn owner(&self) -> &str {
        &self.owner
    }

    pub(crate) fn repo(&self) -> &str {
        &self.repo
    }

    pub(crate) fn git_ref(&self) -> &str {
        &self.git_ref
    }

    /// The [`SUFFIX_LENGTH`]-character identity suffix. Never truncated.
    ///
    /// Owner and repo are lowercased before hashing because GitHub treats them
    /// case-insensitively: `NVIDIA/cuda-samples` and `nvidia/cuda-samples` are
    /// one repository, and giving each spelling its own id means one repo cloned
    /// twice into two containers. The ref is hashed verbatim — git refs really
    /// are case-sensitive, and `Main` and `main` can both exist in one repo.
    ///
    /// Lowercasing does not move ids for input that was already lowercase, which
    /// is every id this project has published.
    pub(crate) fn suffix(&self) -> String {
        hashed_suffix(&[
            &self.owner.to_lowercase(),
            &self.repo.to_lowercase(),
            &self.git_ref,
        ])
    }

    /// The derived id, at most [`TARGET_LENGTH`] characters.
    pub fn value(&self) -> String {
        let Parts {
            repo,
            git_ref,
            suffix,
        } = self.parts();
        join(&[&repo, &git_ref, &suffix])
    }

    /// The same id read as `repo@ref`: no suffix, and an `@` where the id has a
    /// dash.
    ///
    /// This is the name for a tab bar rather than for devpod, and it is the *id*
    /// rather than a second derivation of the triple: the same slugs, cut to the
    /// same lengths by the same budget, so `devlaunch@main` and
    /// `devlaunch-main-3j1t` are one string with two characters changed. That is
    /// what keeps a tab matchable by eye against a `dl --ls` row, which a name
    /// truncated to a budget of its own would not be.
    ///
    /// **The suffix goes because nothing reads it, and the `@` comes back because
    /// people do.** The suffix carries the workspace's identity and none of its
    /// meaning: it is what keeps two branches whose readable halves cut to the same
    /// string in two containers, and somebody looking at a tab has already told
    /// them apart by the branch. The `@` is the character the spec is written with,
    /// so `devlaunch@main` reads as the branch it is where `devlaunch-main` reads
    /// as one dashed word.
    ///
    /// **Not unique, and it does not have to be**, which is the whole difference
    /// between this and [`value`](Self::value). Two workspaces whose ids differ
    /// only in the suffix — the `release/999...176` beside `release/999...234`
    /// shape [`SUFFIX_LENGTH`] is chosen against — get the same label. Nothing
    /// addresses a workspace by this, so a shared label costs a moment of ambiguity
    /// on a tab bar rather than two workspaces sharing one container.
    ///
    /// Falls back to the id when either half is empty — a repo or a ref that
    /// slugs to nothing, `_` being the shortest of them. There is nothing for the
    /// `@` to sit between there, and the id is the one name that is never empty.
    pub fn label(&self) -> String {
        let Parts {
            repo,
            git_ref,
            suffix,
        } = self.parts();
        if repo.is_empty() || git_ref.is_empty() {
            return join(&[&repo, &git_ref, &suffix]);
        }
        format!("{repo}@{git_ref}")
    }

    /// The three pieces an id is joined from, each already cut to its budget.
    ///
    /// One derivation for [`value`](Self::value) and [`label`](Self::label) rather
    /// than two that agree by inspection: the label is the id with the suffix
    /// dropped and one separator changed, and that claim only stays true while a
    /// single function decides where the cuts fall.
    fn parts(&self) -> Parts {
        let suffix = self.suffix();
        let mut repo_part = slug(&self.repo);
        // Cut the repo slug only when the id would otherwise overflow. Whenever the
        // cut does fire, the ref is left TARGET_LENGTH - 20 - 1 - 1 - 4 = 21
        // characters, so it can never come out of that branch with nothing to spend
        // — the hole that let a 47-char repo name skip truncation altogether.
        let untruncated = join(&[&repo_part, &fit_ref(&self.git_ref, TARGET_LENGTH), &suffix]);
        if untruncated.len() > TARGET_LENGTH {
            repo_part = head(&repo_part, REPO_SLUG_LENGTH)
                .trim_matches('-')
                .to_string();
        }
        let separators = if repo_part.is_empty() { 1 } else { 2 };
        // Saturating because the *other* branch can reach zero, and reaches it
        // legitimately: a repo slug of 42 with a ref that slugs to nothing fits
        // inside the budget untruncated, so the cut never fires and the arithmetic
        // asks for -1 characters of a ref there is none of. `fit_ref` at 0 answers
        // the empty string, `join` drops it, and the id lands exactly on the cap.
        let room = TARGET_LENGTH.saturating_sub(suffix.len() + repo_part.len() + separators);
        Parts {
            git_ref: fit_ref(&self.git_ref, room),
            repo: repo_part,
            suffix,
        }
    }
}

/// The pieces [`WorkspaceId::parts`] cuts, in the order an id joins them.
///
/// Any of the three can be the empty string, which [`join`] drops rather than
/// spelling as a stray dash.
struct Parts {
    repo: String,
    git_ref: String,
    suffix: String,
}

impl fmt::Display for WorkspaceId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.value())
    }
}

/// [`SUFFIX_LENGTH`] characters of hashed identity for NUL-delimited *fields*.
///
/// The digest is taken over the fields joined by NUL, with no other
/// normalization applied here. The delimiter is what keeps field boundaries, so
/// `(a, bc)` stays distinct from `(ab, c)`; callers decide what to normalize
/// before calling.
///
/// This algorithm is frozen, and the freeze is enforced by the golden vectors
/// rather than merely asked for: every workspace directory and devpod workspace on
/// disk is named by this output, so the alphabet, the length, the digest, the byte
/// slice and the delimiter are all pinned. Moving any of them moves every id, which
/// is a schema-version bump and a run of [`migration`](crate::flows::migration), not
/// an edit.
///
/// The bias from folding 64 bits into [`SUFFIX_SPACE`] is real and ignorable: the
/// space divides 2^64 about 1.1e13 times, so a favoured residue is favoured by one
/// part in 1e13, some twelve orders of magnitude under the birthday rate the width
/// is chosen against.
fn hashed_suffix(fields: &[&str]) -> String {
    let digest = sha256(fields.join("\0").as_bytes());
    let mut head = [0u8; 8];
    head.copy_from_slice(&digest[..8]);
    let mut bits = u64::from_be_bytes(head);
    let mut out = String::with_capacity(SUFFIX_LENGTH);
    for _ in 0..SUFFIX_LENGTH {
        out.push(SUFFIX_ALPHABET[(bits % 36) as usize] as char);
        bits /= 36;
    }
    out
}

/// Join non-empty *parts* with dashes, so an absent part leaves no stray dash.
fn join(parts: &[&str]) -> String {
    let mut out = String::new();
    for part in parts.iter().filter(|part| !part.is_empty()) {
        if !out.is_empty() {
            out.push('-');
        }
        out.push_str(part);
    }
    out
}

/// The first *n* characters of *s*, like Python's `s[:n]`.
fn head(s: &str, n: usize) -> &str {
    match s.char_indices().nth(n) {
        Some((end, _)) => &s[..end],
        None => s,
    }
}

/// Slug *git_ref* down to *room* characters, dropping whole segments first.
///
/// Refs are path-shaped, and their middle segments are usually taxonomy while
/// the ends carry the meaning. Truncating characters first turns
/// `dependabot/github_actions/codecov/codecov-action-6` into
/// `dependabot-github-actions-`, which says nothing about *which* action.
/// Dropping middle segments instead keeps `dependabot-codecov-action-6`.
fn fit_ref(git_ref: &str, room: usize) -> String {
    let mut segments: Vec<String> = git_ref
        .split('/')
        .map(slug)
        .filter(|segment| !segment.is_empty())
        .collect();
    while segments.len() > 2 && segments.join("-").len() > room {
        segments.remove(1);
    }
    head(&segments.join("-"), room)
        .trim_matches('-')
        .to_string()
}

/// SHA-256 (FIPS 180-4), because the frozen suffix is defined by this digest.
/// The `sha2` crate rather than a hand-rolled compression function: the golden
/// ids pin the output either way, and crypto primitives are the one place
/// "no dependency" costs more review than it saves.
fn sha256(message: &[u8]) -> [u8; 32] {
    use sha2::Digest;
    sha2::Sha256::digest(message).into()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    /// (owner, repo, ref) -> (suffix, value). FROZEN: every workspace directory
    /// and devpod workspace on disk is named by this output.
    ///
    /// **What these pin changed once, and it is worth saying which.** They were
    /// taken from the Python implementation and defended parity with it. That port
    /// is finished and the Python is gone, so what they defend now is only that
    /// **these ids do not move again** — and they have moved exactly once since,
    /// when the suffix went from eight syllable characters to four of base 36
    /// ([`SUFFIX_LENGTH`]). Regenerating them is therefore not a way to make a
    /// failing test pass. It is a schema-version bump plus a run of
    /// [`migration`](crate::flows::migration), which renames every clone directory
    /// on disk so uncommitted work survives and reports the devpod workspaces it
    /// orphans. A diff here with neither of those is a bug that costs someone their
    /// containers.
    const GOLDEN_TRIPLES: &[(&str, &str, &str, &str, &str)] = &[
        ("blooop", "devlaunch", "main", "3j1t", "devlaunch-main-3j1t"),
        ("blooop", "wayfinder", "main", "tdmx", "wayfinder-main-tdmx"),
        (
            "blooop",
            "devlaunch",
            "feature/auth",
            "np10",
            "devlaunch-feature-auth-np10",
        ),
        (
            "blooop",
            "devlaunch",
            "feature-auth",
            "lsi0",
            "devlaunch-feature-auth-lsi0",
        ),
        (
            "blooop",
            "devlaunch",
            "feature.auth",
            "w88t",
            "devlaunch-feature-auth-w88t",
        ),
        (
            "blooop",
            "devlaunch",
            "feature_auth",
            "4l43",
            "devlaunch-feature-auth-4l43",
        ),
        (
            "blooop",
            "devlaunch",
            "featureauth",
            "lzmk",
            "devlaunch-featureauth-lzmk",
        ),
        ("blooop", "devlaunch", "Main", "jzcc", "devlaunch-main-jzcc"),
        (
            "NVIDIA",
            "cuda-samples",
            "main",
            "mut5",
            "cuda-samples-main-mut5",
        ),
        (
            "nvidia",
            "cuda-samples",
            "main",
            "mut5",
            "cuda-samples-main-mut5",
        ),
        ("BlOoOp", "dEvLaUnCh", "main", "3j1t", "devlaunch-main-3j1t"),
        (
            "owner",
            "My_Repo.git",
            "Feature/MyBranch",
            "qlim",
            "my-repo-git-feature-mybranch-qlim",
        ),
        (
            "blooop",
            "devlaunch",
            "dependabot/github_actions/codecov/codecov-action-6",
            "amlt",
            "devlaunch-dependabot-codecov-action-6-amlt",
        ),
        (
            "blooop",
            "devlaunch",
            "dependabot/github_actions/blooop/prek-action-2",
            "wr14",
            "devlaunch-dependabot-blooop-prek-action-2-wr14",
        ),
        (
            "blooop",
            "python_template",
            "dependabot/pip/lib/dependencies-1",
            "ellr",
            "python-template-dependabot-dependencies-1-ellr",
        ),
        (
            "blooop",
            "lifetime_foc_rig",
            "dependabot/github_actions/codecov/codecov-action-6",
            "go3m",
            "lifetime-foc-rig-dependabot-codecov-action-go3m",
        ),
        (
            "kinisi-robotics",
            "kinisi_ros",
            "ags-devcontainer-tooling-support",
            "17uu",
            "kinisi-ros-ags-devcontainer-tooling-suppor-17uu",
        ),
        (
            "blooop",
            "devlaunch",
            "fix/gh-auth-in-devcontainer",
            "tz62",
            "devlaunch-fix-gh-auth-in-devcontainer-tz62",
        ),
        ("blooop", "test_renv", "nb4", "n95z", "test-renv-nb4-n95z"),
        (
            "blooop",
            "dl",
            "a/bbbbbbbb/cccccccc/dddddddd/zzz",
            "31vu",
            "dl-a-bbbbbbbb-cccccccc-dddddddd-zzz-31vu",
        ),
        (
            "blooop",
            "dl",
            "a/bbbbbbbbbbbb/cccccccccccc/dddddddddddd/zzz",
            "6igc",
            "dl-a-cccccccccccc-dddddddddddd-zzz-6igc",
        ),
        (
            "blooop",
            "dl",
            "aa/mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm/nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn/zz",
            "tiiw",
            "dl-aa-zz-tiiw",
        ),
        (
            "blooop",
            "devlaunch",
            "a//b///c/d",
            "8qqi",
            "devlaunch-a-b-c-d-8qqi",
        ),
        (
            "blooop",
            "devlaunch",
            "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            "pljo",
            "devlaunch-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-pljo",
        ),
        (
            "owner",
            "rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
            "main",
            "134a",
            "rrrrrrrrrrrrrrrrrrrr-main-134a",
        ),
        (
            "owner",
            "rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
            "a/very/long/branch/name/that/eats/the/budget",
            "ulfi",
            "rrrrrrrrrrrrrrrrrrrr-a-eats-the-budget-ulfi",
        ),
        (
            "owner",
            "rrrrrrrrrrrrrrrrrrrr",
            "a/very/long/branch/name/that/eats/the/budget",
            "k4h4",
            "rrrrrrrrrrrrrrrrrrrr-a-eats-the-budget-k4h4",
        ),
        (
            "owner",
            "repo",
            "release/9999999999999999999999999176",
            "t91t",
            "repo-release-9999999999999999999999999176-t91t",
        ),
        (
            "owner",
            "repo",
            "release/9999999999999999999999999234",
            "me30",
            "repo-release-9999999999999999999999999234-me30",
        ),
        ("a", "bc", "main", "0kfc", "bc-main-0kfc"),
        ("ab", "c", "main", "rikf", "c-main-rikf"),
        (
            "anyone",
            "github.com",
            "owner/repo",
            "bwb8",
            "github-com-owner-repo-bwb8",
        ),
        (
            "blooop",
            "a-repo-name-that-is-long",
            "feature/shared-prefix-1",
            "w7wc",
            "a-repo-name-that-is-feature-shared-prefix-w7wc",
        ),
        (
            "blooop",
            "a-repo-name-that-is-long",
            "feature/shared-prefix-2",
            "b611",
            "a-repo-name-that-is-feature-shared-prefix-b611",
        ),
        ("owner", "repo", "v1.2.3", "nw8g", "repo-v1-2-3-nw8g"),
        ("owner", "repo", "release_1", "ejia", "repo-release-1-ejia"),
        (
            "owner",
            "r",
            "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
            "6rmm",
            "r-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb-6rmm",
        ),
        (
            "owner",
            "rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
            "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
            "kjce",
            "rrrrrrrrrrrrrrrrrrrr-bbbbbbbbbbbbbbbbbbbbb-kjce",
        ),
        ("owner", "repo", "café", "nhwi", "repo-caf-nhwi"),
        ("owner", "repo", "分支", "g78q", "repo-g78q"),
        ("owner", "repo", "ветка", "j5k1", "repo-j5k1"),
        ("owner", "repo", "١٢٣", "jr9e", "repo-jr9e"),
        ("owner", "KKK", "main", "3t1u", "kkk-main-3t1u"),
        ("owner", "repo", "x\n", "5pb6", "repo-x-5pb6"),
        ("owner", "repo", "İstanbul", "axd9", "repo-i-stanbul-axd9"),
        ("owner", "K", "main", "onou", "k-main-onou"),
    ];

    /// source -> id, for git sources that name no ref.
    const GOLDEN_SOURCES: &[(&str, &str)] = &[
        ("github.com/owner/repo", "github-com-owner-repo-jbsm"),
        (
            "github.com/loft-sh/devpod",
            "github-com-loft-sh-devpod-oowa",
        ),
        ("gitlab.com/group/my_repo", "gitlab-com-group-my-repo-c8uq"),
        ("gitlab.com/group/my-repo", "gitlab-com-group-my-repo-1n65"),
        ("gitlab.com/group/my.repo", "gitlab-com-group-my-repo-wl1k"),
        (
            "github.com/Blooop/DevLaunch",
            "github-com-blooop-devlaunch-swgi",
        ),
        (
            "github.com/blooop/devlaunch",
            "github-com-blooop-devlaunch-swgi",
        ),
        (
            "github.com/oooooooooooooooooooooooooooooooooooooooo/rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
            "github-com-ooooooooooooooooooooooooooooooo-8hgl",
        ),
        (
            "github.com/oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo/rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
            "github-com-ooooooooooooooooooooooooooooooo-dduk",
        ),
        ("github.com/o/r", "github-com-o-r-hlw0"),
        ("o", "o-7u7f"),
        (
            "github.com/owner/repo.git",
            "github-com-owner-repo-git-h9if",
        ),
        (
            "git@github.com:owner/repo.git",
            "git-github-com-owner-repo-git-awz4",
        ),
        (
            "GIT@GitHub.COM:Owner/Repo",
            "git-github-com-owner-repo-8jb3",
        ),
        ("github.com/owner/repo-", "github-com-owner-repo-l97z"),
        ("-----", "4pwo"),
        ("", "lnye"),
        ("分支", "8pgu"),
    ];

    /// text -> slug.
    const GOLDEN_SLUGS: &[(&str, &str)] = &[
        ("main", "main"),
        ("Feature/MyBranch", "feature-mybranch"),
        ("my_repo", "my-repo"),
        ("python_template", "python-template"),
        ("v1.2.3", "v1-2-3"),
        ("--evil--", "evil"),
        ("a...b", "a-b"),
        ("", ""),
        ("-", ""),
        ("---", ""),
        ("MAIN", "main"),
        ("\u{dc}n\u{ef}c\u{f4}de", "n-c-de"),
        ("\u{5206}\u{652f}", ""),
        ("\u{212a}", "k"),
        ("\u{130}stanbul", "i-stanbul"),
        ("\u{3a3}\u{39f}\u{3a6}\u{39f}\u{3a3}", ""),
        ("a b c", "a-b-c"),
        ("\u{ff21}\u{ff22}\u{ff23}", ""),
        ("\u{ff11}\u{ff12}\u{ff13}", ""),
        ("\u{bd}", ""),
        ("\u{24b6}", ""),
        ("caf\u{e9}", "caf"),
        ("main\u{301}", "main"),
        ("x\n", "x"),
        ("x\n\n", "x"),
        ("a/b\n", "a-b"),
        ("x ", "x"),
        ("x\t", "x"),
    ];

    /// name -> whether Python's `^[\w][\w./-]*$` accepts it.
    const GOLDEN_SAFE_NAMES: &[(&str, bool)] = &[
        ("main", true),
        ("feature/my-branch", true),
        ("v1.2.3", true),
        ("release_1", true),
        ("a.b", true),
        ("a-b", true),
        ("a/b", true),
        ("_x", true),
        (".x", false),
        ("", false),
        ("--evil", false),
        ("-x", false),
        ("branch name", false),
        ("a;b", false),
        ("..", false),
        ("a%b", false),
        ("a b", false),
        ("a@b", false),
        ("a:b", false),
        ("a\\b", false),
        ("caf\u{e9}", true),
        ("\u{432}\u{435}\u{442}\u{43a}\u{430}", true),
        ("\u{5206}\u{652f}", true),
        ("\u{661}\u{662}\u{663}", true),
        ("\u{bd}", true),
        ("\u{b2}", true),
        ("\u{ff21}\u{ff22}\u{ff23}", true),
        ("\u{130}", true),
        ("\u{4e94}", true),
        ("x\n", true),
        ("x\n\n", false),
        ("\n", false),
        ("x\ny", false),
        ("x\r", false),
        ("x\r\n", false),
        ("main\n", true),
        ("a/b\n", true),
        ("x ", false),
        ("x\t", false),
        ("\u{212a}", true),
    ];

    /// Names Python refuses and this port accepts: see the module docs.
    const DIVERGENT_NAMES: &[&str] = &[
        "\u{24b6}",
        "x\u{24b6}",
        "\u{93e}",
        "x\u{93e}",
        "\u{5bf}",
        "x\u{903}",
    ];

    #[test]
    fn golden_triples_do_not_move() {
        for &(owner, repo, git_ref, suffix, value) in GOLDEN_TRIPLES {
            let id = WorkspaceId::new(owner, repo, git_ref)
                .unwrap_or_else(|_| panic!("{owner}/{repo}@{git_ref:?} must parse"));
            assert_eq!(id.suffix(), suffix, "suffix for {owner}/{repo}@{git_ref:?}");
            assert_eq!(id.value(), value, "value for {owner}/{repo}@{git_ref:?}");
        }
    }

    #[test]
    fn golden_sources_do_not_move() {
        for &(source, expected) in GOLDEN_SOURCES {
            assert_eq!(source_workspace_id(source), expected, "source {source:?}");
        }
    }

    #[test]
    fn golden_slugs_reproduce_the_python_slug_rule() {
        for &(text, expected) in GOLDEN_SLUGS {
            assert_eq!(slug(text), expected, "slug of {text:?}");
        }
    }

    #[test]
    fn golden_safe_names_reproduce_the_python_predicate() {
        for &(name, accepted) in GOLDEN_SAFE_NAMES {
            assert_eq!(
                is_safe_name(name),
                accepted,
                "safe-name verdict for {name:?}"
            );
        }
    }

    #[test]
    fn a_single_trailing_newline_is_accepted_like_pythons_dollar_anchor() {
        // `re.match(r"^[\w][\w./-]*$", "x\n")` matches: `$` also matches just before
        // one trailing newline. The port keeps the quirk rather than tightening it,
        // because the ref reaches the suffix hash verbatim and tightening would move
        // an id that Python already published.
        assert!(is_safe_name("x\n"));
        assert!(!is_safe_name("x\n\n"));
        assert!(!is_safe_name("x\ny"));
        assert!(!is_safe_name("\n"));
        let with_newline = WorkspaceId::new("owner", "repo", "x\n").expect("accepted");
        let without = WorkspaceId::new("owner", "repo", "x").expect("accepted");
        assert_ne!(with_newline.suffix(), without.suffix());
    }

    #[test]
    fn names_python_refuses_for_exotic_unicode_are_accepted_here() {
        // The measured divergence documented in the module docs. Every name Python
        // accepts, this port accepts and derives the same id for; the extra names are
        // combining marks, enclosed letters and codepoints Python's older UCD does
        // not know yet.
        for &name in DIVERGENT_NAMES {
            assert!(is_safe_name(name), "{name:?}");
        }
    }

    #[test]
    fn the_digest_matches_the_published_sha256_vectors() {
        assert_eq!(
            hex(&sha256(b"")),
            "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
        );
        assert_eq!(
            hex(&sha256(b"abc")),
            "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
        );
        assert_eq!(
            hex(&sha256(&[b'a'; 1000])),
            "41edece42d63e8d9bf515a9ba6932e1c20cbc9f5a5d134645adb5db1b9737ea3"
        );
    }

    fn hex(bytes: &[u8]) -> String {
        bytes.iter().map(|b| format!("{b:02x}")).collect()
    }

    fn id(owner: &str, repo: &str, git_ref: &str) -> WorkspaceId {
        WorkspaceId::new(owner, repo, git_ref).expect("the test triple is safe")
    }

    // ---- the suffix -------------------------------------------------------

    #[test]
    fn the_suffix_is_four_base36_characters() {
        assert_eq!(SUFFIX_LENGTH, 4);
        assert_eq!(SUFFIX_SPACE, 1_679_616);
        assert_eq!(id("blooop", "devlaunch", "main").suffix().len(), 4);
    }

    #[test]
    fn the_suffix_is_drawn_from_the_base36_alphabet() {
        // Every character a DNS label allows but `-`, which is the separator the id
        // is joined on -- so a suffix can never be read as two parts.
        let suffix = id("blooop", "devlaunch", "main").suffix();
        assert_eq!(suffix.len(), SUFFIX_LENGTH);
        for ch in suffix.chars() {
            assert!(ch.is_ascii_lowercase() || ch.is_ascii_digit(), "{ch}");
        }
    }

    #[test]
    fn the_suffix_hashes_the_unsanitized_ref() {
        assert_ne!(
            id("blooop", "devlaunch", "feature/auth").suffix(),
            id("blooop", "devlaunch", "feature-auth").suffix()
        );
    }

    #[test]
    fn the_suffix_separates_the_triples_fields() {
        // The NUL delimiter keeps field boundaries; without it these would collide.
        assert_ne!(
            id("a", "bc", "main").suffix(),
            id("ab", "c", "main").suffix()
        );
    }

    // ---- owner and repo are case-insensitive ------------------------------

    const CASE_VARIANTS: &[(&str, &str)] = &[
        ("blooop", "devlaunch"),
        ("Blooop", "devlaunch"),
        ("blooop", "DevLaunch"),
        ("BLOOOP", "DEVLAUNCH"),
        ("BlOoOp", "dEvLaUnCh"),
    ];

    #[test]
    fn case_variants_of_one_repo_derive_one_id() {
        let ids: HashSet<String> = CASE_VARIANTS
            .iter()
            .map(|&(owner, repo)| id(owner, repo, "main").value())
            .collect();
        assert_eq!(ids.len(), 1);
    }

    #[test]
    fn case_variants_share_the_suffix() {
        let suffixes: HashSet<String> = CASE_VARIANTS
            .iter()
            .map(|&(owner, repo)| id(owner, repo, "main").suffix())
            .collect();
        assert_eq!(suffixes.len(), 1);
    }

    #[test]
    fn lowercase_input_is_unaffected_by_case_folding() {
        assert_eq!(id("blooop", "devlaunch", "main").suffix(), "3j1t");
    }

    #[test]
    fn refs_stay_case_sensitive() {
        assert_ne!(
            id("blooop", "devlaunch", "main").value(),
            id("blooop", "devlaunch", "Main").value()
        );
    }

    #[test]
    fn the_nvidia_case_regression_stays_fixed() {
        assert_eq!(
            id("NVIDIA", "cuda-samples", "main").value(),
            id("nvidia", "cuda-samples", "main").value()
        );
    }

    // ---- the slug rule ----------------------------------------------------

    #[test]
    fn underscore_has_exactly_one_meaning() {
        assert_eq!(slug("my_repo"), "my-repo");
        assert!(
            id("owner", "my_repo", "main")
                .value()
                .starts_with("my-repo-")
        );
    }

    // ---- validation -------------------------------------------------------

    #[test]
    fn ordinary_refs_are_accepted() {
        for git_ref in ["main", "feature/my-branch", "v1.2.3", "release_1"] {
            assert_eq!(id("owner", "repo", git_ref).git_ref(), git_ref);
        }
    }

    #[test]
    fn unsafe_refs_are_refused_with_the_part_and_the_name() {
        for git_ref in ["", "--evil", "-x", "branch name", "a;b", "..", "a%b"] {
            assert_eq!(
                WorkspaceId::new("owner", "repo", git_ref),
                Err(UnsafeName {
                    part: NamePart::Ref,
                    name: git_ref.to_string(),
                }),
                "{git_ref:?}"
            );
        }
    }

    #[test]
    fn unsafe_owners_are_refused() {
        for owner in ["", "--evil", "own er"] {
            assert_eq!(
                WorkspaceId::new(owner, "repo", "main").map(|w| w.value()),
                Err(UnsafeName {
                    part: NamePart::Owner,
                    name: owner.to_string(),
                })
            );
        }
    }

    #[test]
    fn unsafe_repos_are_refused() {
        for repo in ["", "--evil", "re po"] {
            assert_eq!(
                WorkspaceId::new("owner", repo, "main").map(|w| w.value()),
                Err(UnsafeName {
                    part: NamePart::Repo,
                    name: repo.to_string(),
                })
            );
        }
    }

    #[test]
    fn the_owner_is_validated_before_the_repo_and_the_ref() {
        // Python validates owner, then repo, then ref, and dl.py reports the first
        // failure; a caller building repos_dir/<owner>/<repo> depends on the owner
        // being refused even when the ref is bad too.
        assert_eq!(
            WorkspaceId::new("../x", "..", "--evil"),
            Err(UnsafeName {
                part: NamePart::Owner,
                name: "../x".to_string(),
            })
        );
        assert_eq!(
            WorkspaceId::new("owner", "..", "--evil"),
            Err(UnsafeName {
                part: NamePart::Repo,
                name: "..".to_string(),
            })
        );
    }

    #[test]
    fn the_constructor_and_the_predicate_agree() {
        assert!(is_safe_name("main"));
        assert!(!is_safe_name("--evil"));
        assert!(WorkspaceId::new("owner", "repo", "main").is_ok());
        assert!(WorkspaceId::new("owner", "repo", "--evil").is_err());
    }

    // ---- injectivity ------------------------------------------------------

    #[test]
    fn slash_and_dash_refs_differ() {
        assert_ne!(
            id("blooop", "devlaunch", "feature/auth").value(),
            id("blooop", "devlaunch", "feature-auth").value()
        );
    }

    #[test]
    fn the_five_preimages_of_feature_auth_differ() {
        let ids: HashSet<String> = [
            "feature/auth",
            "feature-auth",
            "feature.auth",
            "feature_auth",
            "featureauth",
        ]
        .into_iter()
        .map(|git_ref| id("blooop", "devlaunch", git_ref).value())
        .collect();
        assert_eq!(ids.len(), 5);
    }

    #[test]
    fn refs_sharing_a_thirty_character_prefix_differ() {
        let prefix = "feature/a-very-long-branch-nam";
        assert_eq!(prefix.len(), 30);
        assert_ne!(
            id("blooop", "devlaunch", &format!("{prefix}e-one")).value(),
            id("blooop", "devlaunch", &format!("{prefix}e-two")).value()
        );
    }

    #[test]
    fn the_same_ref_in_a_different_repo_differs() {
        assert_ne!(
            id("blooop", "devlaunch", "main").value(),
            id("blooop", "wayfinder", "main").value()
        );
    }

    #[test]
    fn the_same_ref_under_a_different_owner_differs() {
        assert_ne!(
            id("blooop", "devlaunch", "main").value(),
            id("someone-else", "devlaunch", "main").value()
        );
    }

    #[test]
    fn truncation_contributes_no_collisions() {
        // 500 refs whose readable part truncates to one byte-identical string: the
        // number of distinct ids must equal the number of distinct suffixes, so
        // truncation adds nothing on top of the suffix's own birthday rate.
        let parsed: Vec<WorkspaceId> = (0..500)
            .map(|i| {
                id(
                    "blooop",
                    "a-repo-name-that-is-long",
                    &format!("feature/shared-prefix-{i}"),
                )
            })
            .collect();
        let readable: HashSet<String> = parsed
            .iter()
            .map(|w| drop_last_segment(&w.value()))
            .collect();
        assert_eq!(
            readable.len(),
            1,
            "the corpus must collide before truncation"
        );
        let values: HashSet<String> = parsed.iter().map(|w| w.value()).collect();
        let suffixes: HashSet<String> = parsed.iter().map(|w| w.suffix()).collect();
        assert_eq!(values.len(), suffixes.len());
    }

    fn drop_last_segment(value: &str) -> String {
        match value.rsplit_once('-') {
            Some((head, _)) => head.to_string(),
            None => value.to_string(),
        }
    }

    // ---- length -----------------------------------------------------------

    #[test]
    fn a_forty_seven_character_repo_fits() {
        let repo = "r".repeat(47);
        assert!(id("owner", &repo, "main").value().len() <= TARGET_LENGTH);
    }

    #[test]
    fn every_repo_length_fits() {
        for repo_len in 1..60 {
            let value = id("owner", &"r".repeat(repo_len), "some/long/branch/name-here").value();
            assert!(value.len() <= TARGET_LENGTH, "{repo_len}: {value}");
        }
    }

    #[test]
    fn every_ref_length_fits() {
        for ref_len in 1..80 {
            let value = id("owner", "devlaunch", &"b".repeat(ref_len)).value();
            assert!(value.len() <= TARGET_LENGTH, "{ref_len}: {value}");
        }
    }

    #[test]
    fn the_repo_slug_is_intact_up_to_twenty_characters() {
        let repo = "r".repeat(REPO_SLUG_LENGTH);
        let value = id(
            "owner",
            &repo,
            "a/very/long/branch/name/that/eats/the/budget",
        )
        .value();
        assert!(value.starts_with(&format!("{repo}-")), "{value}");
    }

    #[test]
    fn the_repo_slug_is_never_cut_below_twenty_characters() {
        let value = id(
            "owner",
            &"r".repeat(47),
            "a/very/long/branch/name/that/eats/the/budget",
        )
        .value();
        assert!(
            value.starts_with(&format!("{}-", "r".repeat(REPO_SLUG_LENGTH))),
            "{value}"
        );
    }

    #[test]
    fn the_suffix_is_never_truncated() {
        for repo_len in [1, 20, 47, 80] {
            let parsed = id("owner", &"r".repeat(repo_len), &"b".repeat(80));
            assert!(
                parsed.value().ends_with(&format!("-{}", parsed.suffix())),
                "{}",
                parsed.value()
            );
        }
    }

    /// The two sweeps above each move one length at a time, and the cap is a
    /// function of the pair: the repo slug decides how much room `fit_ref` gets.
    /// Reachability is asserted too, because a budget nothing reaches would pass
    /// a bound test while truncating harder than the format intends.
    #[test]
    fn no_pair_of_repo_and_ref_lengths_exceeds_the_budget() {
        let mut longest = 0;
        for repo_len in 1..48 {
            for ref_len in 1..48 {
                for git_ref in ["b".repeat(ref_len), "a/".repeat(ref_len)] {
                    let parsed = id("owner", &"r".repeat(repo_len), &git_ref);
                    let value = parsed.value();
                    assert!(
                        value.len() <= TARGET_LENGTH,
                        "repo {repo_len}, ref {ref_len}: {value}"
                    );
                    assert!(value.ends_with(&parsed.suffix()), "{value}");
                    assert!(!value.starts_with('-'), "{value}");
                    longest = longest.max(value.len());
                }
            }
        }
        assert_eq!(longest, TARGET_LENGTH, "the budget must be reachable");
    }

    // ------------------------------------------------- the name a person reads

    #[test]
    fn a_label_is_the_id_with_the_suffix_off_and_an_at_where_the_dash_was() {
        // The whole claim: the two strings differ in exactly the five characters the
        // tab has no use for. Nothing derives the label from the triple a second
        // time, so a change to how the id is cut cannot move one without moving the
        // other.
        let parsed = id("blooop", "devlaunch", "feature/auth");
        assert_eq!(parsed.value(), "devlaunch-feature-auth-np10");
        assert_eq!(parsed.label(), "devlaunch@feature-auth");

        // Stated as a *difference*, not as a reconstruction, because which dash the
        // `@` replaces cannot be read off the id: a repo slug holds dashes of its
        // own, so `my-repo@main` and `my@repo-main` are the same id read two ways.
        // That is exactly why a placement carries the name beside the id instead of
        // recovering one from the other (`flows::launch::Placement::title`).
        for (repo, git_ref, label) in [
            ("devlaunch", "feature/auth", "devlaunch@feature-auth"),
            ("my-repo", "main", "my-repo@main"),
            ("my_repo.v2", "release/1.2", "my-repo-v2@release-1-2"),
        ] {
            let parsed = id("owner", repo, git_ref);
            assert_eq!(parsed.label(), label, "{repo}@{git_ref}");
            assert_eq!(
                parsed.value(),
                format!("{}-{}", parsed.label().replace('@', "-"), parsed.suffix()),
                "the label and the id differ by the suffix and one separator"
            );
        }
    }

    #[test]
    fn a_label_is_cut_by_the_ids_budget_and_not_by_one_of_its_own() {
        // The room the ref gets is decided against the suffix's four characters even
        // though the label does not carry them. That is the point: a label wider than
        // the id's readable half would be a tab that says more than the `dl --ls` row
        // it is meant to be matched against, and the room is not the label's to spend.
        let parsed = id("owner", &"r".repeat(47), &"b".repeat(80));
        assert_eq!(
            parsed.label(),
            format!("{}@{}", "r".repeat(REPO_SLUG_LENGTH), "b".repeat(21))
        );
        assert_eq!(
            parsed.label().len(),
            TARGET_LENGTH - SUFFIX_LENGTH - 1,
            "the whole id, less the suffix and the dash in front of it"
        );
    }

    #[test]
    fn a_label_with_nothing_to_put_an_at_between_answers_the_id() {
        // `_` is a safe name -- `is_word` accepts it -- and slugs to nothing, so a
        // repo or a ref can genuinely arrive empty. There is no `@` to write with one
        // side missing, and `@main` or `devlaunch@` would read as a broken spec, so
        // the id is what comes back: it is the one name that is never empty.
        let no_repo = id("owner", "_", "main");
        assert_eq!(no_repo.label(), no_repo.value());
        assert_eq!(no_repo.label(), format!("main-{}", no_repo.suffix()));

        let no_ref = id("owner", "devlaunch", "_");
        assert_eq!(no_ref.label(), no_ref.value());
        assert_eq!(no_ref.label(), format!("devlaunch-{}", no_ref.suffix()));
    }

    #[test]
    fn a_label_holds_one_at_and_nothing_else_a_shell_or_a_terminal_reads() {
        // The label reaches two sinks that fear characters: an OSC 2 escape, ended by
        // a control, and a `PS1` assignment bash expands again at every prompt. Both
        // are filtered downstream (`sanitize_title`), and this is why that filter
        // finds nothing to do on this path: `slug` leaves lowercase alphanumerics and
        // dashes, and the only character added to them is the `@`.
        for git_ref in [
            "main",
            "feature/auth",
            "main\n",
            "release/9.9.9",
            "UPPER/Case",
        ] {
            let label = id("owner", "my_repo.v2", git_ref).label();
            assert!(
                label
                    .chars()
                    .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-' || c == '@'),
                "{label}"
            );
            assert!(label.matches('@').count() <= 1, "{label}");
        }
    }

    #[test]
    fn two_workspaces_that_differ_only_in_the_suffix_share_one_label() {
        // The property the label gives up, asserted so that it is a decision. The
        // suffix is the whole of what keeps these two apart, and it is exactly what
        // the tab drops -- so `dl --ls`, the hostname and devpod can still tell them
        // apart and a tab bar cannot. Nothing addresses a workspace by a label.
        let one = id("owner", "repo", &format!("release/{}176", "9".repeat(40)));
        let two = id("owner", "repo", &format!("release/{}234", "9".repeat(40)));
        assert_ne!(one.value(), two.value());
        assert_eq!(one.label(), two.label());
    }

    /// The repo-slug floor cannot win against the total budget: the floor, the
    /// suffix and the two dashes come to 26, so `fit_ref` is left twenty-one
    /// characters to land in and the worst case lands *on* the cap, not past it.
    #[test]
    fn the_repo_slug_floor_still_leaves_the_ref_room() {
        // Saturating, so a floor raised past the budget fails this assertion
        // rather than failing to compile. The literal is deliberately not derived
        // from the constants -- deriving it from the same expression asserts
        // nothing -- so it moves by hand when the budget does, and widening the
        // budget has to say so here instead of being absorbed in silence. 47 - 20
        // - 4 - 2; it read 17 at an eight-character suffix, and 8 when the budget
        // was 38.
        let room = TARGET_LENGTH.saturating_sub(REPO_SLUG_LENGTH + SUFFIX_LENGTH + 2);
        assert_eq!(room, 21);
        let parsed = id("owner", &"r".repeat(47), &"b".repeat(80));
        assert_eq!(
            parsed.value(),
            format!(
                "{}-{}-{}",
                "r".repeat(REPO_SLUG_LENGTH),
                "b".repeat(room),
                parsed.suffix()
            )
        );
        assert_eq!(parsed.value().len(), TARGET_LENGTH);
    }

    /// The one input that reaches `value`'s `saturating_sub` with something to
    /// saturate, so the saturation is pinned as behaviour rather than left looking
    /// like defensive decoration.
    ///
    /// The repo-slug cap fires only when the id would overflow, and this one does
    /// not: 42 characters of repo, a ref that slugs to nothing, one dash and the
    /// suffix come to exactly the budget. So the cut is skipped, and the ref budget
    /// computed after it asks for -1. A plain subtraction panics in debug and wraps
    /// to `usize::MAX` in release, which `fit_ref` would answer with the whole ref.
    #[test]
    fn a_repo_that_fills_the_budget_on_its_own_leaves_the_ref_no_room_and_not_a_wrap() {
        let repo = "r".repeat(42);
        let parsed = id("owner", &repo, "_");

        assert_eq!(slug("_"), "", "the ref has to slug to nothing");
        assert_eq!(parsed.value(), format!("{repo}-{}", parsed.suffix()));
        assert_eq!(parsed.value().len(), TARGET_LENGTH);
        // One shorter and the arithmetic is ordinary, which is what makes 42 the
        // boundary rather than an arbitrary length.
        let shorter = id("owner", &"r".repeat(41), "_");
        assert_eq!(shorter.value().len(), TARGET_LENGTH - 1);
        // One longer and the cut fires instead, which is the branch the comment on
        // `value` is about.
        let longer = id("owner", &"r".repeat(43), "_");
        assert!(
            longer
                .value()
                .starts_with(&format!("{}-", "r".repeat(REPO_SLUG_LENGTH))),
            "{}",
            longer.value()
        );
    }

    #[test]
    fn a_constructed_id_is_lowercase_alphanumerics_and_dashes() {
        let value = id("Owner", "My_Repo.git", "Feature/MyBranch").value();
        assert!(
            value
                .chars()
                .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-'),
            "{value}"
        );
        assert!(!value.starts_with('-'));
        assert!(!value.ends_with('-'));
    }

    // ---- segment-aware truncation -----------------------------------------

    #[test]
    fn a_dependabot_ref_keeps_the_action_name() {
        let value = id(
            "blooop",
            "devlaunch",
            "dependabot/github_actions/codecov/codecov-action-6",
        )
        .value();
        assert!(value.contains("codecov"), "{value}");
        assert!(value.starts_with("devlaunch-dependabot-codecov"), "{value}");
        assert!(!value.contains("github-actions"), "{value}");
    }

    /// The segment widths are sized to the budget: this ref is over it by less
    /// than one segment, so exactly one middle has to go. A ref that fits whole
    /// would pin nothing, which is what the 8-wide version of it became when the
    /// cap moved from 38 to 47.
    #[test]
    fn only_as_many_middle_segments_drop_as_needed() {
        let git_ref = format!(
            "a/{}/{}/{}/zzz",
            "b".repeat(12),
            "c".repeat(12),
            "d".repeat(12)
        );
        let value = id("blooop", "dl", &git_ref).value();
        let kept = format!("dl-a-{}-{}-zzz-", "c".repeat(12), "d".repeat(12));
        assert!(value.starts_with(&kept), "{value}");
        assert!(!value.contains(&"b".repeat(12)), "{value}");
    }

    /// The other side of the same rule: nothing drops until it has to.
    #[test]
    fn a_ref_that_fits_whole_keeps_every_segment() {
        let value = id("blooop", "dl", "a/bbbbbbbb/cccccccc/dddddddd/zzz").value();
        assert!(
            value.starts_with("dl-a-bbbbbbbb-cccccccc-dddddddd-zzz-"),
            "{value}"
        );
    }

    /// Both middles are far wider than the budget rather than just over it: at 30
    /// each this passed by a single character, so one more character of cap would
    /// have turned it into a test of dropping *one* middle without saying so.
    #[test]
    fn the_first_and_last_segments_survive_heavy_truncation() {
        let git_ref = format!("aa/{}/{}/zz", "m".repeat(40), "n".repeat(40));
        let value = id("blooop", "dl", &git_ref).value();
        assert!(value.starts_with("dl-aa-zz-"), "{value}");
        assert!(
            !value.contains("mmmm") && !value.contains("nnnn"),
            "{value}"
        );
    }

    #[test]
    fn a_single_segment_ref_is_truncated_by_characters() {
        let value = id("blooop", "devlaunch", &"a".repeat(60)).value();
        assert!(value.starts_with("devlaunch-aaa"), "{value}");
    }

    /// The shapes the segment pass cannot shorten: two segments with nothing in
    /// the middle to drop, a single segment longer than the room, and a ref whose
    /// segments all slug away to nothing. Each still yields a non-empty id with
    /// its suffix intact and no dash left dangling where a part was dropped.
    #[test]
    fn refs_the_segment_pass_cannot_shorten_still_yield_a_valid_id() {
        for git_ref in [
            format!("{}/{}", "a".repeat(30), "z".repeat(30)),
            "aaaa/bbbb".to_owned(),
            "a".repeat(60),
            "_".to_owned(),
            "___/___".to_owned(),
        ] {
            let parsed = id("owner", "devlaunch", &git_ref);
            let value = parsed.value();
            assert!(value.starts_with("devlaunch-"), "{git_ref:?}: {value}");
            assert!(value.ends_with(&parsed.suffix()), "{git_ref:?}: {value}");
            assert!(!value.contains("--"), "{git_ref:?}: {value}");
            assert!(value.len() <= TARGET_LENGTH, "{git_ref:?}: {value}");
        }
    }

    #[test]
    fn dropping_segments_leaves_no_double_dashes() {
        let value = id("blooop", "devlaunch", "a//b///c/d").value();
        assert!(!value.contains("--"), "{value}");
    }

    // ---- ref-less sources -------------------------------------------------

    #[test]
    fn underscore_dash_and_dot_sources_stay_distinct() {
        let ids: HashSet<String> = [
            "gitlab.com/group/my_repo",
            "gitlab.com/group/my-repo",
            "gitlab.com/group/my.repo",
        ]
        .into_iter()
        .map(source_workspace_id)
        .collect();
        assert_eq!(ids.len(), 3);
    }

    #[test]
    fn every_source_length_is_capped() {
        for length in [1, 10, 40, 80, 200] {
            let source = format!("github.com/{}/{}", "o".repeat(length), "r".repeat(length));
            assert!(
                source_workspace_id(&source).len() <= TARGET_LENGTH,
                "{length}"
            );
        }
    }

    #[test]
    fn the_readable_prefix_of_a_source_survives() {
        assert!(
            source_workspace_id("github.com/loft-sh/devpod")
                .starts_with("github-com-loft-sh-devpod-")
        );
    }

    #[test]
    fn a_sources_suffix_is_present_and_full_width() {
        let value = source_workspace_id("github.com/owner/repo");
        let (_, suffix) = value.rsplit_once('-').expect("a suffix is joined on");
        assert_eq!(suffix.len(), SUFFIX_LENGTH);
    }

    #[test]
    fn source_case_is_folded() {
        assert_eq!(
            source_workspace_id("github.com/Blooop/DevLaunch"),
            source_workspace_id("github.com/blooop/devlaunch")
        );
    }

    #[test]
    fn a_source_id_cannot_collide_with_a_triple_id() {
        let triple = id("anyone", "github.com", "owner/repo");
        let source = source_workspace_id("github.com/owner/repo");
        assert_eq!(drop_last_segment(&source), "github-com-owner-repo");
        assert_eq!(drop_last_segment(&triple.value()), "github-com-owner-repo");
        assert_ne!(source, triple.value());
    }

    #[test]
    fn a_sources_id_is_deterministic() {
        assert_eq!(
            source_workspace_id("github.com/owner/repo"),
            source_workspace_id("github.com/owner/repo")
        );
    }

    // ---- determinism ------------------------------------------------------

    #[test]
    fn the_derivation_is_pure() {
        // Nothing here reads the environment, the working directory, the clock or a
        // randomised hash seed -- the module's only inputs are its arguments, which
        // is why Python needed a fresh-interpreter test and this does not. The
        // repeated call is the part still worth asserting.
        let first = id("blooop", "devlaunch", "main").value();
        let second = id("blooop", "devlaunch", "main").value();
        assert_eq!(first, second);
        assert_eq!(first, "devlaunch-main-3j1t");
    }

    // ---- the real-world corpus -------------------------------------------

    #[test]
    fn the_real_world_corpus_is_unique_and_within_budget() {
        let ids: Vec<String> = GOLDEN_TRIPLES
            .iter()
            .map(|&(owner, repo, git_ref, _, _)| id(owner, repo, git_ref).value())
            .collect();
        for value in &ids {
            assert!(value.len() <= TARGET_LENGTH, "{value}");
        }
        // Two rows are deliberate case variants of one repo, so the corpus has
        // exactly two duplicate pairs.
        let distinct: HashSet<&String> = ids.iter().collect();
        assert_eq!(distinct.len(), ids.len() - 2);
    }

    #[test]
    fn a_short_repo_name_is_intact_in_the_corpus() {
        for &(owner, repo, git_ref, _, _) in GOLDEN_TRIPLES {
            let repo_slug = slug(repo);
            if repo_slug.len() <= REPO_SLUG_LENGTH && !repo_slug.is_empty() {
                let value = id(owner, repo, git_ref).value();
                assert!(value.starts_with(&format!("{repo_slug}-")), "{value}");
            }
        }
    }

    // ---- the parsed value itself ------------------------------------------

    #[test]
    fn display_is_the_id() {
        let parsed = id("blooop", "devlaunch", "main");
        assert_eq!(parsed.to_string(), parsed.value());
    }

    #[test]
    fn equality_is_by_triple() {
        assert_eq!(
            id("blooop", "devlaunch", "main"),
            id("blooop", "devlaunch", "main")
        );
        assert_ne!(
            id("blooop", "devlaunch", "main"),
            id("blooop", "devlaunch", "other")
        );
    }

    #[test]
    fn the_parsed_value_is_hashable() {
        let set: HashSet<WorkspaceId> = [
            id("blooop", "devlaunch", "main"),
            id("blooop", "devlaunch", "main"),
        ]
        .into_iter()
        .collect();
        assert_eq!(set.len(), 1);
    }

    #[test]
    fn the_triple_is_readable_back_off_the_parsed_value() {
        let parsed = id("blooop", "devlaunch", "feature/auth");
        assert_eq!(parsed.owner(), "blooop");
        assert_eq!(parsed.repo(), "devlaunch");
        assert_eq!(parsed.git_ref(), "feature/auth");
    }
}
