"""
dl - DevLaunch CLI

A streamlined CLI for devpod with intuitive autocomplete and fzf fuzzy selection.
Provides an renv-like UX for managing devcontainer workspaces.

Usage:
    dl                           # fzf selector for existing workspaces
    dl <workspace>               # open/create workspace, attach shell
    dl <workspace> <command>     # run command in workspace
    dl owner/repo                # create from git repo (github.com)
    dl owner/repo@branch         # specific branch
    dl ./path                    # create from local path
    dl --ls                      # list workspaces
    dl --stop <workspace>        # stop workspace
    dl --rm <workspace>          # delete workspace
    dl --code <workspace>        # open in VS Code
    dl --install                 # install completions
"""

import sys
import subprocess
import json
import logging
import os
import pathlib
import re
from importlib.metadata import version as pkg_version, PackageNotFoundError
from typing import List, Optional, Dict, Any
from dataclasses import dataclass

from .completion import install_completions
from .worktree.config import get_worktree_config
from .worktree.workspace_clone import WorkspaceCloneManager


def get_version() -> str:
    """Get the package version."""
    try:
        return pkg_version("devlaunch")
    except PackageNotFoundError:
        return "unknown"


logging.basicConfig(level=logging.INFO, format="%(message)s")


def _get_cache_dir() -> pathlib.Path:
    """Get the cache directory, honoring XDG_CACHE_HOME."""
    xdg_cache = os.environ.get("XDG_CACHE_HOME")
    if xdg_cache:
        return pathlib.Path(xdg_cache) / "devlaunch"
    return pathlib.Path.home() / ".cache" / "devlaunch"


# Cache configuration (honors XDG_CACHE_HOME)
CACHE_DIR = _get_cache_dir()
CACHE_FILE = CACHE_DIR / "completions.json"
BASH_CACHE_FILE = CACHE_DIR / "completions.bash"


def get_cache_path() -> pathlib.Path:
    """Get the path to the completion cache file."""
    return CACHE_FILE


def read_completion_cache() -> Optional[Dict[str, Any]]:
    """Read completion data from cache file."""
    cache_path = get_cache_path()
    if not cache_path.exists():
        return None
    try:
        with open(cache_path, encoding="utf-8") as f:
            return json.load(f)
    except (OSError, json.JSONDecodeError):
        return None


def write_completion_cache(data: Dict[str, Any]) -> None:
    """Write completion data to cache file (JSON format)."""
    cache_path = get_cache_path()
    try:
        cache_path.parent.mkdir(parents=True, exist_ok=True)
        # Write to temp file first, then atomic rename
        temp_path = cache_path.with_suffix(".tmp")
        with open(temp_path, "w", encoding="utf-8") as f:
            json.dump(data, f)
        # Atomic rename (on POSIX systems)
        temp_path.replace(cache_path)
    except OSError:
        pass


def write_bash_completion_cache(data: Dict[str, Any]) -> None:
    """Write completion data as a sourceable bash file."""
    try:
        BASH_CACHE_FILE.parent.mkdir(parents=True, exist_ok=True)
        workspaces = " ".join(data.get("workspaces", []))
        repos = " ".join(data.get("repos", []))
        owners = " ".join(data.get("owners", []))
        branches = " ".join(data.get("branches", []))
        lines = [
            "# Auto-generated by dl - do not edit",
            f'DL_WORKSPACES="{workspaces}"',
            f'DL_REPOS="{repos}"',
            f'DL_OWNERS="{owners}"',
            f'DL_BRANCHES="{branches}"',
        ]
        # Write to temp file first, then atomic rename
        temp_path = BASH_CACHE_FILE.with_suffix(".tmp")
        with open(temp_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines) + "\n")
        # Atomic rename (on POSIX systems)
        temp_path.replace(BASH_CACHE_FILE)
    except OSError:
        pass


def get_remote_branches(owner_repo: str) -> List[str]:
    """Get list of branches from a remote GitHub repository."""
    url = f"git@github.com:{owner_repo}.git"
    try:
        result = subprocess.run(
            ["git", "ls-remote", "--heads", url],
            capture_output=True,
            text=True,
            check=False,
            timeout=5,  # Don't hang on slow connections
        )
        if result.returncode == 0:
            branches = []
            for line in result.stdout.strip().split("\n"):
                if line and "refs/heads/" in line:
                    branch = line.split("refs/heads/")[-1]
                    branches.append(branch)
            return branches
    except (OSError, subprocess.SubprocessError, subprocess.TimeoutExpired):
        pass
    return []


def get_local_branches(owner_repo: str) -> List[str]:
    """Get list of local branches from the bare repo cache.

    Discovers branches that exist locally but may not yet be on the remote
    (e.g. branches created via ``dl owner/repo@new-branch``).
    """
    owner, repo = owner_repo.split("/", 1)
    repos_dir = pathlib.Path(get_worktree_config().repos_dir)
    bare_path = repos_dir / owner / repo / ".bare"
    if not bare_path.is_dir():
        return []
    try:
        result = subprocess.run(
            ["git", "for-each-ref", "--format=%(refname:short)", "refs/heads/"],
            cwd=bare_path,
            capture_output=True,
            text=True,
            check=False,
            timeout=2,
        )
        if result.returncode == 0:
            return [b for b in result.stdout.strip().split("\n") if b]
    except (OSError, subprocess.SubprocessError, subprocess.TimeoutExpired):
        pass
    return []


def update_completion_cache() -> Dict[str, Any]:
    """Update the completion cache with current data."""
    workspaces = list_workspaces()
    workspace_ids = [ws.id for ws in workspaces]
    repos = discover_repos_from_workspaces(workspaces)

    # Merge repos discovered from the local cache directory so that repos
    # cloned locally (even without a devpod workspace yet) appear in completions
    for owner, repo_list in discover_repos_from_cache_dir().items():
        if owner not in repos:
            repos[owner] = []
        for repo in repo_list:
            if repo not in repos[owner]:
                repos[owner].append(repo)

    # Flatten repos to list of owner/repo strings
    known_repos = []
    for owner, repo_list in sorted(repos.items()):
        for repo in sorted(repo_list):
            known_repos.append(f"{owner}/{repo}")

    # Extract unique owners
    owners = sorted(repos.keys())

    # Fetch branches for all known repos (as owner/repo@branch strings)
    # Merge remote and local branches so locally-created branches also complete
    all_branches = []
    for owner_repo in known_repos:
        remote = set(get_remote_branches(owner_repo))
        local = set(get_local_branches(owner_repo))
        for branch in sorted(remote | local):
            all_branches.append(f"{owner_repo}@{branch}")

    data = {
        "workspaces": workspace_ids,
        "repos": known_repos,
        "owners": owners,
        "branches": all_branches,
    }
    write_completion_cache(data)
    write_bash_completion_cache(data)
    return data


def update_cache_background() -> None:
    """Update completion cache in background."""
    try:
        # pylint: disable=consider-using-with
        subprocess.Popen(
            [sys.executable, "-m", "devlaunch.dl", "--update-cache"],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            start_new_session=True,
        )
    except OSError:
        pass


def purge_all_data() -> int:
    """Purge all devlaunch data including DevPod workspaces and caches.

    This:
    1. Deletes all DevPod workspaces
    2. Removes ~/.cache/devlaunch/ which contains:
       - completions.json, completions.bash (completion caches)
    """
    import shutil

    cache_dir = _get_cache_dir()

    # First, delete all DevPod workspaces
    workspaces = list_workspaces()
    for ws in workspaces:
        print(f"Deleting DevPod workspace: {ws.id}")
        result = run_devpod(["delete", ws.id, "--force"], capture=True)
        if result.returncode != 0:
            logging.warning(f"Failed to delete workspace {ws.id}: {result.stderr}")

    # Then remove local cache
    if not cache_dir.exists():
        if not workspaces:
            print("No data to purge.")
        return 0

    try:
        shutil.rmtree(cache_dir)
        print(f"Removed: {cache_dir}")
        return 0
    except OSError as e:
        print(f"Error removing {cache_dir}: {e}")
        return 1


# Regex to match owner/repo[@branch] format (not a path, not already a URL)

OWNER_REPO_PATTERN = re.compile(r"^[a-zA-Z0-9_.-]+/[a-zA-Z0-9_.-]+(@[a-zA-Z0-9_./%-]+)?$")


def parse_owner_repo_branch(spec: str) -> Optional[tuple]:
    """Parse owner/repo[@branch] spec into (owner_repo, branch) tuple.

    Returns None if spec doesn't match owner/repo format.
    Branch may be None if not specified.
    """
    # Skip paths and full URLs
    if is_path_spec(spec) or "://" in spec:
        return None
    if spec.startswith("github.com/") or spec.startswith("gitlab.com/"):
        return None

    if not OWNER_REPO_PATTERN.match(spec):
        return None

    if "@" in spec:
        owner_repo, branch = spec.split("@", 1)
        return (owner_repo, branch)
    return (spec, None)


def is_path_spec(spec: str) -> bool:
    """Check if spec looks like a filesystem path."""
    return spec.startswith("./") or spec.startswith("/") or spec.startswith("~")


def is_git_spec(spec: str) -> bool:
    """Check if spec looks like a git repo (owner/repo or URL)."""
    # Paths are not git specs
    if is_path_spec(spec):
        return False
    if "://" in spec:
        return True
    if spec.startswith("github.com/") or spec.startswith("gitlab.com/"):
        return True
    return bool(OWNER_REPO_PATTERN.match(spec))


def expand_workspace_spec(spec: str) -> str:
    """Expand owner/repo[@branch] to git@github.com:owner/repo.git[@branch] for devpod."""
    # Don't expand if it's a path
    if is_path_spec(spec):
        return spec
    # Don't expand if it already looks like a URL
    if "://" in spec or spec.startswith("github.com/") or spec.startswith("gitlab.com/"):
        return spec
    # Don't expand if it's already an SSH URL (more specific pattern: user@host:path)
    # Matches patterns like git@github.com:, git@gitlab.com:, etc.
    if re.match(r"^[^@]+@[^:]+:", spec):
        return spec
    # Check if it matches owner/repo[@branch] pattern - use SSH URL format for GitHub
    if OWNER_REPO_PATTERN.match(spec):
        if "@" in spec:
            owner_repo, branch = spec.split("@", 1)
            return f"git@github.com:{owner_repo}.git@{branch}"
        return f"git@github.com:{spec}.git"
    # Otherwise return as-is (existing workspace name)
    return spec


def sanitize_workspace_id(name: str) -> str:
    """Sanitize a name to match devpod's workspace ID format.

    Devpod converts names to lowercase and replaces / with -.
    """
    return name.lower().replace("/", "-")


def get_work_symlink_path(workspace_id: str) -> str:
    """Get the symlink path used for shorter terminal prompts.

    Returns ~/<workspace_id> which is a symlink to the actual workspace directory.
    This gives users a short path that includes the project name in their prompt.
    e.g. ~/python-template (main) instead of ~/work (main)
    """
    return f"/home/vscode/{workspace_id}"


def get_container_workdir(workspace_id: str) -> str:
    """Get the container working directory for a workspace.

    DevPod mounts workspaces to /workspaces/{workspace_id}/
    """
    return f"/workspaces/{workspace_id}"


def setup_work_symlink(workspace_id: str) -> bool:
    """Create ~/work symlink pointing to the workspace directory.

    This provides a shorter path for terminal prompts. Instead of seeing
    /workspaces/blooop-bencher-main in the prompt, users see ~/work.

    Args:
        workspace_id: The DevPod workspace ID to SSH into

    Returns:
        True if symlink was created successfully, False otherwise
    """
    symlink_path = get_work_symlink_path(workspace_id)
    workdir = get_container_workdir(workspace_id)
    # Use ln -sfn: -s for symlink, -f to force overwrite, -n to not dereference
    symlink_cmd = f"ln -sfn {workdir} {symlink_path}"
    result = workspace_ssh(workspace_id, command=symlink_cmd)
    return result == 0


def spec_to_workspace_id(spec: str) -> str:
    """Derive the workspace ID for a given spec.

    Uses <repo>-<branch> format so workspace names are meaningful in devpod list.
    Branch is truncated so total stays ≤ 48 chars.

    - For owner/repo with branch: <repo>-<branch> (e.g., python-template-nb4)
    - For owner/repo without branch: <repo> (e.g., python-template)
    - For paths: the directory name (e.g., ./my-project -> my-project)
    - For existing IDs: the ID as-is
    """
    # Check for @branch suffix
    if "@" in spec:
        base_spec, _ = spec.split("@", 1)
    else:
        base_spec = spec

    # For paths, use the directory name
    if is_path_spec(base_spec):
        return pathlib.Path(base_spec).expanduser().resolve().name

    # For git URLs or owner/repo
    if is_git_spec(base_spec):
        parsed = parse_owner_repo_branch(spec)
        if parsed:
            owner_repo, parsed_branch = parsed
            repo_name = owner_repo.split("/")[-1]
            repo_name = sanitize_workspace_id(repo_name).replace("_", "-")
            if parsed_branch:
                branch_sanitized = sanitize_workspace_id(parsed_branch).replace("_", "-")
                max_branch = 48 - len(repo_name) - 1  # -1 for separator
                if 0 < max_branch < len(branch_sanitized):
                    branch_sanitized = branch_sanitized[:max_branch].rstrip("-")
                return f"{repo_name}-{branch_sanitized}"
            return repo_name

        # Fallback for non-owner/repo git URLs (github.com/..., https://...)
        full_source = expand_workspace_spec(base_spec)
        # Strip protocol prefix if present
        if "://" in full_source:
            full_source = full_source.split("://", 1)[1]
        # Strip SSH URL prefix (user@host:) if present
        ssh_match = re.match(r"^[^@]+@([^:]+):(.*)", full_source)
        if ssh_match:
            full_source = f"{ssh_match.group(1)}/{ssh_match.group(2)}"
        # Strip .git suffix if present
        if full_source.endswith(".git"):
            full_source = full_source[:-4]
        # Devpod sanitizes: lowercase, replace . and / and : with -, remove _
        workspace_id = full_source.lower()
        workspace_id = workspace_id.replace(".", "-").replace("/", "-").replace(":", "-")
        workspace_id = workspace_id.replace("_", "")
        # Remove trailing - if any
        workspace_id = workspace_id.rstrip("-")
        return workspace_id

    # Otherwise assume it's already a workspace ID
    return spec


def validate_workspace_spec(spec: str, existing_ids: List[str]) -> Optional[str]:
    """Validate workspace spec and return error message if invalid."""
    # Valid if it's an existing workspace
    if spec in existing_ids:
        return None
    # Valid if it's a path
    if is_path_spec(spec):
        return None
    # Valid if it's a git spec (owner/repo or URL)
    if is_git_spec(spec):
        return None
    # Invalid - provide helpful error
    return f"Unknown workspace '{spec}'. Use 'dl --ls' to list workspaces, or specify owner/repo or ./path"


@dataclass
class Workspace:
    """Represents a devpod workspace."""

    id: str
    source_type: str  # "local" or "git"
    source: str
    last_used: str
    provider: str
    ide: str

    @classmethod
    def from_json(cls, data: Dict[str, Any]) -> "Workspace":
        """Parse workspace from devpod JSON output."""
        source = data.get("source", {})
        if "localFolder" in source:
            source_type = "local"
            source_path = source["localFolder"]
        elif "gitRepository" in source:
            source_type = "git"
            source_path = source["gitRepository"]
        else:
            source_type = "unknown"
            source_path = str(source)

        return cls(
            id=data.get("id", ""),
            source_type=source_type,
            source=source_path,
            last_used=data.get("lastUsed", ""),
            provider=data.get("provider", {}).get("name", ""),
            ide=data.get("ide", {}).get("name", ""),
        )


# Regex patterns for parsing git URLs
GIT_URL_PATTERNS = [
    # git@github.com:owner/repo.git
    re.compile(r"git@github\.com:([^/]+)/([^/]+?)(?:\.git)?$"),
    # https://github.com/owner/repo.git or https://github.com/owner/repo
    re.compile(r"https?://github\.com/([^/]+)/([^/]+?)(?:\.git)?$"),
    # github.com/owner/repo
    re.compile(r"^github\.com/([^/]+)/([^/]+?)(?:\.git)?$"),
]


def parse_owner_repo_from_url(url: str) -> Optional[tuple]:
    """Extract (owner, repo) from a git URL."""
    for pattern in GIT_URL_PATTERNS:
        match = pattern.match(url)
        if match:
            return (match.group(1), match.group(2))
    return None


def get_git_remote_url(path: str) -> Optional[str]:
    """Get the origin remote URL from a git repository."""
    try:
        result = subprocess.run(
            ["git", "-C", path, "remote", "get-url", "origin"],
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode == 0:
            return result.stdout.strip()
    except (OSError, subprocess.SubprocessError):
        pass
    return None


def get_git_branches(path: str) -> List[str]:
    """Get list of branches from a git repository."""
    try:
        result = subprocess.run(
            ["git", "-C", path, "branch", "-r"],
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode == 0:
            branches = []
            for line in result.stdout.strip().split("\n"):
                line = line.strip()
                if line and "origin/" in line and "HEAD" not in line:
                    branch = line.replace("origin/", "")
                    branches.append(branch)
            return branches
    except (OSError, subprocess.SubprocessError):
        pass
    return []


def _git_ls_remote(owner_repo: str, *args: str) -> Optional[str]:
    """Run git ls-remote and return stdout, or None on error.

    Uses SSH URL for consistency with other git operations.
    Includes timeout to prevent hanging on slow/unreachable remotes.
    """
    url = f"git@github.com:{owner_repo}.git"
    try:
        result = subprocess.run(
            ["git", "ls-remote", url, *args],
            capture_output=True,
            text=True,
            check=False,
            timeout=5,
        )
        if result.returncode == 0 and result.stdout.strip():
            return result.stdout
    except (OSError, subprocess.SubprocessError, subprocess.TimeoutExpired):
        pass
    return None


def remote_branch_exists(owner_repo: str, branch: str) -> bool:
    """Check if a branch exists on a remote GitHub repository."""
    output = _git_ls_remote(owner_repo, "--heads", branch)
    return bool(output)


def get_remote_head_sha(owner_repo: str) -> Optional[str]:
    """Get the SHA of the default branch (HEAD) of a remote repository."""
    output = _git_ls_remote(owner_repo, "HEAD")
    if not output:
        return None
    # Output format: "<sha>\tHEAD"
    return output.strip().split()[0]


def discover_repos_from_workspaces(workspaces: List[Workspace]) -> Dict[str, List[str]]:
    """Discover owner/repo from workspace git remotes.

    Returns dict mapping owner -> list of repos.
    """
    repos: Dict[str, List[str]] = {}

    for ws in workspaces:
        owner_repo = None

        # For git workspaces, parse the source URL directly
        if ws.source_type == "git":
            owner_repo = parse_owner_repo_from_url(ws.source)

        # For local workspaces, try to get git remote
        elif ws.source_type == "local" and ws.source:
            remote_url = get_git_remote_url(ws.source)
            if remote_url:
                owner_repo = parse_owner_repo_from_url(remote_url)

        if owner_repo:
            owner, repo = owner_repo
            if owner not in repos:
                repos[owner] = []
            if repo not in repos[owner]:
                repos[owner].append(repo)

    return repos


def discover_repos_from_cache_dir() -> Dict[str, List[str]]:
    """Discover owner/repo from bare repos in the local cache directory.

    Scans <repos_dir>/<owner>/<repo>/.bare/ on the filesystem so that repos
    cloned locally (even without a devpod workspace yet) are discovered.

    Returns dict mapping owner -> list of repos (same shape as
    ``discover_repos_from_workspaces``).
    """
    repos: Dict[str, List[str]] = {}
    repos_dir = pathlib.Path(get_worktree_config().repos_dir)
    if not repos_dir.is_dir():
        return repos
    try:
        for owner_dir in repos_dir.iterdir():
            if not owner_dir.is_dir():
                continue
            for repo_dir in owner_dir.iterdir():
                if not repo_dir.is_dir():
                    continue
                if (repo_dir / ".bare").is_dir():
                    owner = owner_dir.name
                    repo = repo_dir.name
                    if owner not in repos:
                        repos[owner] = []
                    if repo not in repos[owner]:
                        repos[owner].append(repo)
    except OSError:
        pass
    return repos


def get_known_repos() -> List[str]:
    """Get list of known owner/repo strings from workspaces."""
    workspaces = list_workspaces()
    repos = discover_repos_from_workspaces(workspaces)
    result = []
    for owner, repo_list in sorted(repos.items()):
        for repo in sorted(repo_list):
            result.append(f"{owner}/{repo}")
    return result


def run_devpod(args: List[str], capture: bool = False) -> subprocess.CompletedProcess:
    """Run a devpod command.

    Security note: Using list form of subprocess.run (not shell=True) prevents
    command injection. Each list element is passed as a separate argument to
    the executable, so special characters are not interpreted by a shell.
    """
    cmd = ["devpod"] + args
    logging.debug("Running: %s", " ".join(cmd))
    if capture:
        # nosec B603 - using list form, not shell=True; no command injection risk
        return subprocess.run(cmd, capture_output=True, text=True, check=False)
    # nosec B603 - using list form, not shell=True; no command injection risk
    return subprocess.run(cmd, check=False)


def list_workspaces() -> List[Workspace]:
    """List all devpod workspaces."""
    result = run_devpod(["list", "--output", "json"], capture=True)
    if result.returncode != 0 or not result.stdout.strip():
        return []
    try:
        data = json.loads(result.stdout)
        return [Workspace.from_json(ws) for ws in data]
    except json.JSONDecodeError:
        logging.error("Failed to parse devpod output")
        return []


def get_workspace_ids() -> List[str]:
    """Get list of workspace IDs for completion."""
    return [ws.id for ws in list_workspaces()]


def print_workspaces():
    """Print workspace list in a nice format."""
    workspaces = list_workspaces()
    if not workspaces:
        print("No workspaces found.")
        return

    # Calculate column widths
    id_width = max(len(ws.id) for ws in workspaces)
    type_width = max(len(ws.source_type) for ws in workspaces)
    source_width = max(len(ws.source) for ws in workspaces)

    # Print header
    print(
        f"{'WORKSPACE':<{id_width}}  {'TYPE':<{type_width}}  {'SOURCE':<{source_width}}  LAST USED"
    )
    print("-" * (id_width + type_width + source_width + 30))

    # Print rows
    for ws in workspaces:
        last_used = ws.last_used[:19].replace("T", " ") if ws.last_used else "never"
        print(
            f"{ws.id:<{id_width}}  {ws.source_type:<{type_width}}  {ws.source:<{source_width}}  {last_used}"
        )


def fuzzy_select_workspace() -> Optional[str]:
    """Interactive fuzzy finder for workspace selection."""
    try:
        from iterfzf import iterfzf
    except ImportError:
        logging.error("iterfzf not available. Install with: pip install iterfzf")
        return None

    workspaces = list_workspaces()
    if not workspaces:
        logging.info("No workspaces found. Create one with: dl owner/repo or dl ./path")
        return None

    # Format options for display: "id | type | source"
    options = []
    ws_map = {}
    for ws in workspaces:
        label = f"{ws.id} | {ws.source_type} | {ws.source}"
        options.append(label)
        ws_map[label] = ws.id

    print("Select workspace (type to filter):")
    try:
        selected = iterfzf(options, multi=False)
    except KeyboardInterrupt:
        return None
    if selected:
        return ws_map.get(selected)
    return None


def get_context_option(name: str) -> Optional[str]:
    """Read a devpod context option value (e.g. DOTFILES_URL)."""
    result = run_devpod(
        ["context", "options", "--output", "json"], capture=True
    )
    if result.returncode != 0 or not result.stdout.strip():
        return None
    try:
        data = json.loads(result.stdout)
        option = data.get(name, {})
        return option.get("value") or None
    except (json.JSONDecodeError, AttributeError):
        return None


def workspace_up(
    workspace: str,
    ide: Optional[str] = None,
    recreate: bool = False,
    reset: bool = False,
    workspace_id: Optional[str] = None,
):
    """Start or create a workspace."""
    args = ["up", workspace]
    if workspace_id:
        args.extend(["--id", workspace_id])
    if ide:
        args.extend(["--ide", ide])
    if recreate:
        args.append("--recreate")
    if reset:
        args.append("--reset")
    dotfiles_url = get_context_option("DOTFILES_URL")
    if dotfiles_url:
        args.extend(["--dotfiles", dotfiles_url])
    dotfiles_script = get_context_option("DOTFILES_SCRIPT")
    if dotfiles_script:
        args.extend(["--dotfiles-script", dotfiles_script])
    return run_devpod(args)


def workspace_ssh(
    workspace: str,
    command: Optional[str] = None,
    workdir: Optional[str] = None,
    preserve_symlink: bool = False,
) -> int:
    """SSH into a workspace, optionally running a command.

    Args:
        workspace: The workspace ID to SSH into
        command: Optional command to run (if None, starts interactive shell)
        workdir: Working directory to start in
        preserve_symlink: If True and workdir is set, use 'cd' instead of --workdir
                         to preserve symlink paths in $PWD (for shorter prompts)
    """
    args = ["ssh", workspace]

    # If preserve_symlink is True, we use 'cd' instead of --workdir
    # because DevPod's --workdir resolves symlinks, but 'cd' preserves them in $PWD
    if workdir and preserve_symlink:
        if command:
            # Wrap the command with cd
            wrapped_cmd = f"cd {workdir} && {command}"
            args.extend(["--command", wrapped_cmd])
        else:
            # For interactive shell, cd and exec a login shell
            wrapped_cmd = f"cd {workdir} && exec $SHELL -l"
            args.extend(["--command", wrapped_cmd])
    else:
        # Standard behavior: use --workdir (resolves symlinks)
        if workdir:
            args.extend(["--workdir", workdir])
        if command:
            args.extend(["--command", command])

    logging.info(f"SSH command: devpod {' '.join(args)}")
    result = run_devpod(args)
    return result.returncode


def workspace_stop(workspace: str) -> int:
    """Stop a workspace."""
    result = run_devpod(["stop", workspace])
    # Update cache after stopping workspace
    update_cache_background()
    return result.returncode


def workspace_delete(workspace: str) -> int:
    """Delete a workspace and its local clone (if any)."""
    result = run_devpod(["delete", workspace])
    # Clean up local workspace clone (look up by workspace ID in metadata)
    try:
        clone_mgr = _get_clone_manager()
        if clone_mgr.remove_workspace_by_id(workspace):
            logging.info(f"Removed local clone for {workspace}")
    except Exception as e:
        logging.warning(f"Failed to remove local clone: {e}")
    # Update cache after deleting workspace
    update_cache_background()
    return result.returncode


def workspace_status(workspace: str) -> int:
    """Get status of a workspace."""
    result = run_devpod(["status", workspace])
    return result.returncode


def get_workspace_state(workspace_id: str) -> Optional[str]:
    """Get workspace state from devpod (e.g., 'Running', 'Stopped')."""
    result = run_devpod(["status", workspace_id, "--output", "json"], capture=True)
    if result.returncode != 0:
        return None
    try:
        data = json.loads(result.stdout)
        return data.get("state")
    except json.JSONDecodeError:
        logging.warning("Failed to parse devpod status JSON for workspace %s", workspace_id)
        return None


def print_help():
    """Print usage help."""
    help_text = """dl - DevLaunch CLI

Usage:
    dl                               Interactive workspace selector (fzf)
    dl <user/repo>                   Start workspace and attach shell
    dl <user/repo> <cmd>             Run workspace command (stop, code, etc.)
    dl <user/repo> -- <shell>        Run shell command in workspace

Workspace sources:
    dl myproject                     Existing workspace by name
    dl user/repo                     Create from GitHub repo
    dl user/repo@branch              Create from specific branch
    dl ./path                        Create from local path

Workspace commands:
    dl <user/repo> stop              Stop the workspace
    dl <user/repo> rm, prune         Delete the workspace
    dl <user/repo> code              Open in VS Code
    dl <user/repo> restart           Stop and start (no rebuild)
    dl <user/repo> recreate          Recreate container
    dl <user/repo> reset             Clean slate (remove all, recreate)
    dl <user/repo> -- <command>      Run shell command in workspace

Global commands:
    dl --ls                          List all workspaces
    dl --install                     Install shell completions
    dl --refresh                     Refresh completion cache
    dl --purge [-y]                  Remove all DevPod workspaces and caches
    dl --help, -h                    Show this help
    dl --version                     Show version

Examples:
    dl                               # Select workspace with fzf
    dl devpod                        # Open existing workspace
    dl loft-sh/devpod                # Create from GitHub
    dl blooop/devlaunch@main         # Create from specific branch
    dl ./my-project                  # Create from local folder
    dl blooop/devlaunch code         # Open in VS Code
    dl blooop/devlaunch -- make test # Run command in workspace
    dl blooop/devlaunch stop         # Stop workspace
"""
    print(help_text)


_cache: dict[str, WorkspaceCloneManager] = {}


def _get_clone_manager() -> WorkspaceCloneManager:
    """Lazy factory for WorkspaceCloneManager."""
    if "clone_manager" not in _cache:
        _cache["clone_manager"] = WorkspaceCloneManager()
    return _cache["clone_manager"]


def main() -> int:
    """Main entry point for dl CLI."""
    args = sys.argv[1:]

    # Always update cache in background (unless we're the update process)
    if args and args[0] in ["--update-cache"]:
        pass  # Don't recursively update
    else:
        update_cache_background()

    # No args - try fzf selection
    if not args:
        selected = fuzzy_select_workspace()
        if not selected:
            print_help()
            return 1
        workspace_up(selected)
        setup_work_symlink(selected)
        return workspace_ssh(
            selected, workdir=get_work_symlink_path(selected), preserve_symlink=True
        )

    # Global commands (no workspace required)
    if args[0] in ("--help", "-h"):
        print_help()
        return 0

    if args[0] == "--version":
        print(f"dl {get_version()}")
        return 0

    if args[0] == "--ls":
        print_workspaces()
        return 0

    if args[0] == "--repos":
        # Output known repos for bash completion (uses cache if available)
        cache = read_completion_cache()
        if cache and "repos" in cache:
            for repo in cache["repos"]:
                print(repo)
        else:
            for repo in get_known_repos():
                print(repo)
        return 0

    if args[0] == "--update-cache":
        # Silent background update
        update_completion_cache()
        return 0

    if args[0] == "--refresh":
        # Manual refresh with feedback
        print("Refreshing completion cache...")
        data = update_completion_cache()
        print(f"Cache updated: {len(data.get('workspaces', []))} workspaces found")
        return 0

    if args[0] == "--completion-data":
        # Output all completion data as JSON (fast, from cache)
        cache = read_completion_cache()
        if cache:
            print(json.dumps(cache))
        else:
            # No cache, generate and cache it
            data = update_completion_cache()
            print(json.dumps(data))
        return 0

    if args[0] == "--install":
        rc_path = None
        if len(args) > 1:
            rc_path = pathlib.Path(args[1])
        # Generate cache so completions work immediately
        update_completion_cache()
        return install_completions(rc_path)

    if args[0] == "--purge":
        # Check for -y flag to skip confirmation
        skip_confirm = len(args) > 1 and args[1] in ("-y", "--yes")
        cache_dir = _get_cache_dir()
        workspaces = list_workspaces()
        print("This will remove all devlaunch data:")
        print(f"  - {len(workspaces)} DevPod workspace(s)")
        print(f"  - {cache_dir}/ (workspace clones, repo caches, completions)")
        print()
        if skip_confirm:
            return purge_all_data()
        confirm = input("Are you sure? [y/N] ").strip().lower()
        if confirm in ("y", "yes"):
            return purge_all_data()
        print("Aborted.")
        return 0

    # Workspace commands: dl <workspace> [subcommand] [-- command]
    raw_spec = args[0]
    subcommand = args[1] if len(args) > 1 else None

    # Validate the workspace spec
    existing_ids = get_workspace_ids()
    error = validate_workspace_spec(raw_spec, existing_ids)
    if error:
        logging.error(error)
        return 1

    # Resolve workspace spec and ID
    is_existing = raw_spec in existing_ids
    parsed = parse_owner_repo_branch(raw_spec)

    if is_existing:
        workspace_spec = raw_spec
        workspace_id = raw_spec
        custom_id = None  # Don't pass --id for existing workspaces
    elif parsed:
        # Git spec (owner/repo[@branch]) — check if workspace already exists first
        owner_repo, branch = parsed
        owner, repo = owner_repo.split("/", 1)
        remote_url = f"git@github.com:{owner_repo}.git"

        clone_mgr = _get_clone_manager()
        repo_ensured = False

        # Resolve branch early so we can compute workspace ID
        if not branch:
            try:
                clone_mgr.repo_manager.ensure_repo(owner, repo, remote_url)
            except (RuntimeError, OSError) as e:
                logging.error(f"Repository '{owner_repo}': {e}")
                return 1
            repo_ensured = True
            branch = clone_mgr.repo_manager.get_default_branch(owner, repo)

        # Compute workspace ID with resolved branch
        workspace_id = spec_to_workspace_id(f"{owner_repo}@{branch}")

        # Fast path: if devpod already knows this workspace, skip clone manager
        if workspace_id in existing_ids:
            workspace_spec = workspace_id
            custom_id = None
        else:
            # Full path: clone locally and pass local path to DevPod
            if not repo_ensured:
                try:
                    clone_mgr.repo_manager.ensure_repo(owner, repo, remote_url)
                except (RuntimeError, OSError) as e:
                    logging.error(f"Repository '{owner_repo}': {e}")
                    return 1

            # Ensure branch exists in bare repo (create on remote if needed)
            try:
                clone_mgr.ensure_branch(owner, repo, branch)
            except (RuntimeError, OSError) as e:
                logging.error(f"Failed to ensure branch '{branch}': {e}")
                return 1

            custom_id = workspace_id

            # Create workspace clone
            try:
                workspace_path = clone_mgr.ensure_workspace(
                    owner, repo, branch, remote_url, workspace_id
                )
                workspace_spec = str(workspace_path)
            except (RuntimeError, OSError) as e:
                logging.error(f"Failed to prepare workspace: {e}")
                return 1
    else:
        workspace_spec = expand_workspace_spec(raw_spec)
        workspace_id = spec_to_workspace_id(raw_spec)
        custom_id = workspace_id  # Pass --id to create with our desired ID

    # Handle workspace subcommands
    if subcommand == "stop":
        return workspace_stop(workspace_id)

    if subcommand in ("rm", "prune"):
        return workspace_delete(workspace_id)

    if subcommand == "code":
        result = workspace_up(workspace_spec, ide="vscode", workspace_id=custom_id)
        return result.returncode

    if subcommand == "recreate":
        result = workspace_up(workspace_spec, recreate=True, workspace_id=custom_id)
        if result.returncode != 0:
            return result.returncode
        setup_work_symlink(workspace_id)
        return workspace_ssh(
            workspace_id, workdir=get_work_symlink_path(workspace_id), preserve_symlink=True
        )

    if subcommand == "restart":
        # Stop and start without rebuilding
        stop_ret = workspace_stop(workspace_id)
        if stop_ret != 0:
            return stop_ret
        result = workspace_up(workspace_spec, workspace_id=custom_id)
        if result.returncode != 0:
            return result.returncode
        setup_work_symlink(workspace_id)
        return workspace_ssh(
            workspace_id, workdir=get_work_symlink_path(workspace_id), preserve_symlink=True
        )

    if subcommand == "reset":
        # Clean slate - remove everything and recreate
        result = workspace_up(workspace_spec, reset=True, workspace_id=custom_id)
        if result.returncode != 0:
            return result.returncode
        setup_work_symlink(workspace_id)
        return workspace_ssh(
            workspace_id, workdir=get_work_symlink_path(workspace_id), preserve_symlink=True
        )

    # Check for shell command (after --)
    shell_command = None
    if subcommand == "--" and len(args) > 2:
        shell_command = " ".join(args[2:])
    elif subcommand is not None and subcommand != "--":
        # Unknown subcommand - treat as error
        logging.error(
            f"Unknown command '{subcommand}'. Use 'dl {raw_spec} -- {subcommand}' to run a shell command."
        )
        return 1

    # Fast-attach: skip workspace_up() if workspace is already running
    if custom_id is None and get_workspace_state(workspace_id) == "Running":
        logging.info(f"Workspace {workspace_id} is already running, attaching...")
        setup_work_symlink(workspace_id)
        ret = workspace_ssh(
            workspace_id,
            shell_command,
            workdir=get_work_symlink_path(workspace_id),
            preserve_symlink=True,
        )
        update_cache_background()
        return ret

    # Default: start workspace and attach shell
    try:
        result = workspace_up(workspace_spec, workspace_id=custom_id)
    except (RuntimeError, OSError) as e:
        logging.error(f"Failed to create workspace: {e}")
        return 1

    if result.returncode != 0:
        return result.returncode

    # Create ~/work symlink for shorter terminal prompt
    setup_work_symlink(workspace_id)

    # Attach to workspace via ~/work symlink (preserves short path in $PWD)
    ret = workspace_ssh(
        workspace_id,
        shell_command,
        workdir=get_work_symlink_path(workspace_id),
        preserve_symlink=True,
    )

    # Update cache after workspace operations
    update_cache_background()

    return ret


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        sys.exit(130)
