#!/usr/bin/env bash
#
# Regenerate the three checked-in `cargo public-api` snapshots -- and, wherever
# they are checked, be the one definition of how the surface is classified.
#
# There are three files because there are three different promises:
#
#   rust/devlaunch-core/public-api.api.txt   the frozen promise. Every row is a
#       declaration under `devlaunch_core::api`, the tier an external consumer
#       is entitled to depend on, so a diff here is a breaking change by
#       definition and wants a reviewer who reads it that way.
#   rust/devlaunch-core/public-api.rest.txt  the tripwire. The binary surface --
#       `flows::`, `domain::`, `clients::` -- which is reachable but never
#       promised: regenerate it freely, and read a diff for the accidental `pub`
#       rather than for a broken contract.
#   rust/devlaunch-runner/public-api.txt     the process seam, as an external
#       `Runner` implementor sees it. It had no snapshot until the split: the
#       whole crate entered core's as one unexpanded glob row, so a removed
#       trait method moved nothing and passed CI.
#
# The classification is one `grep` and it lives here, in the script CI runs,
# because the alternative is two copies of it -- one in the workflow, one in
# whatever regenerates the files -- drifting until the promise file quietly
# stops holding the promise. `.github/workflows/ci.yml`'s `public-api` job runs
# this into a scratch tree and diffs the result against what the repo carries;
# a developer runs it with no argument to accept a deliberate change.
#
# Usage:
#   scripts/public-api-snapshots.sh            # rewrite the checked-in files
#   scripts/public-api-snapshots.sh DEST       # write them under DEST instead
#   scripts/public-api-snapshots.sh --print-pin
#
# Needs a nightly toolchain (cargo-public-api's rustdoc-JSON backend is
# nightly-only; the crates themselves still build on the stable pin) and the
# pinned cargo-public-api. This repository's devcontainer carries neither, so
# this is a host command:
#
#   rustup toolchain install nightly
#   cargo install cargo-public-api --locked \
#       --version "$(scripts/public-api-snapshots.sh --print-pin)"
#
set -euo pipefail

# Pinned, and pinned here so the workflow installs what this script demands
# rather than the two agreeing by coincidence: cargo-public-api's rendering
# moves between releases, and a snapshot generated by a different one is a
# whole-file diff that says nothing. Bump it together with regenerated files.
PIN=0.52.0

# `-ss` omits blanket and auto-trait impls. Those rows move when *rustdoc*
# moves -- `UnsafeUnpin` appeared with a nightly, not with a crate change -- and
# a tripwire that fires on toolchain drift teaches people to update snapshots
# unread. Derived impls (Clone, Debug, serde) stay in: losing one is a real
# break.
FLAGS=(-ss)

# The boundary matters: `\b` is what keeps a future `devlaunch_core::apiary`
# out of the promise file. `rust/devlaunch-core/tests/public_api_snapshots.rs`
# holds the checked-in files to this same rule from the other side.
API_ROW='devlaunch_core::api\b'

if [[ "${1:-}" == "--print-pin" ]]; then
  echo "$PIN"
  exit 0
fi

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
dest="${1:-$repo_root/rust}"
mkdir -p "$dest/devlaunch-core" "$dest/devlaunch-runner"

if ! installed="$(cargo public-api --version 2>/dev/null)"; then
  echo "cargo-public-api is not installed. cargo install cargo-public-api --locked --version $PIN" >&2
  exit 1
fi
if [[ "$installed" != "cargo-public-api $PIN" ]]; then
  echo "cargo-public-api is '$installed', and these snapshots are rendered by $PIN." >&2
  echo "Install the pin, or bump PIN in this script and regenerate everything with it." >&2
  exit 1
fi

cd "$repo_root/rust"

core="$(cargo public-api -p devlaunch-core "${FLAGS[@]}")"

# Two greps rather than one pass with a fallthrough, so the two files are
# complements by construction. Either coming out empty means the filter no
# longer matches the crate, which is a broken split rather than a small API.
if ! printf '%s\n' "$core" | grep -E "$API_ROW" >"$dest/devlaunch-core/public-api.api.txt"; then
  echo "no rows matched $API_ROW: devlaunch-core no longer declares an 'api' module?" >&2
  exit 1
fi
if ! printf '%s\n' "$core" | grep -Ev "$API_ROW" >"$dest/devlaunch-core/public-api.rest.txt"; then
  echo "every row matched $API_ROW: the split has nothing left to classify?" >&2
  exit 1
fi

cargo public-api -p devlaunch-runner "${FLAGS[@]}" >"$dest/devlaunch-runner/public-api.txt"
