#!/usr/bin/env bash
# The verdict on whether a pull request was actually reviewed by anything.
#
# Separate from the workflow that calls it so the classification is executable
# outside CI, which is what `test/test_review_guard.py` executes. A `case`
# statement living only inside a `run:` block is testable only by copying it, and
# a copied guard is a guard that drifts.
#
# Reads the PR's reviews on stdin as a JSON array of {author, body}, and the PR's
# author in $PR_AUTHOR. Exit 0 means somebody or something reviewed the code;
# exit 1 means nothing did, and the reason goes to stdout as a workflow-command
# error so it annotates the pull request rather than only a log nobody opens.
#
# ## What counts
#
# A review by someone *other than the author* counts on its own -- that is a
# second party looking, which is the thing worth having.
#
# A review by the author counts only if it carries the provenance line that
# `wf-review` writes. That is not ceremony: the line marks a two-axis report
# produced in fresh context that did not see the code written, and the
# distinction it draws is exactly the one that matters here -- between a review
# and "lgtm" typed by the person who wrote it. Anyone determined can still write
# the line, but the guard is against a review silently not happening, not against
# a person deciding to skip one; that decision has a label.
set -euo pipefail

OVERRIDE=${OVERRIDE_LABEL:-no-external-review}
AUTHOR=${PR_AUTHOR:-}
HEAD_SHA=${PR_HEAD_SHA:-}
# `wf-review`'s provenance line, matched on its stable middle rather than whole
# so a change of emphasis or a trailing period does not silently stop counting.
PROVENANCE="generated by AI during"

reviews=$(cat)
if [ -z "${reviews//[[:space:]]/}" ]; then
  reviews='[]'
fi

# Without it, every review is somebody else's and the author's own "lgtm" counts
# as a second party -- the one way this script can be wrong in the direction that
# lets something through. Unreachable from today's workflow, which is why it is
# asserted rather than trusted.
if [ -z "$AUTHOR" ]; then
  echo "::error::PR_AUTHOR is empty, so this check cannot tell the author's own"\
       "review from anybody else's and will not guess."
  exit 1
fi

# Both refusals are quota refusals, and neither says anything about the code. The
# second fires on *size*, so it exempts exactly the changes least safe to merge
# unread.
#
# Asked of the *reviewer*, not of the prose. Sniffing the body for those
# sentences has now been wrong twice in opposite directions: matched loosely it
# ate a `wf-review` report that quoted them (the report had to misspell them to
# get through), and anchored to `Sorry @` it stopped recognising a refusal with a
# leading newline -- strictly weaker than the loose match it replaced. Only the
# reviewer can refuse on its own behalf, so that is the question asked.
#
# The cost is that a *new* external reviewer's refusals go unrecognised until its
# login is added here. That is a config change with a test naming it, rather than
# a regex quietly deciding what a refusal looks like.
REFUSING_LOGINS=${REFUSING_LOGINS:-sourcery-ai[bot]}

is_refusal() {
  local author=$1 body=$2 login
  local matched=1
  for login in $REFUSING_LOGINS; do
    [ "$author" = "$login" ] && matched=0
  done
  [ "$matched" -eq 0 ] || return 1
  case $body in
    *"you have reached your weekly rate limit"*) return 0 ;;
    *"larger than the review limit"*) return 0 ;;
  esac
  return 1
}

count=$(jq 'length' <<<"$reviews")
second_party=0
self_review=0
refusals=0
at_head=0

for i in $(seq 0 $((count - 1))); do
  author=$(jq -r ".[$i].author // \"\"" <<<"$reviews")
  body=$(jq -r ".[$i].body // \"\"" <<<"$reviews")
  state=$(jq -r ".[$i].state // \"\"" <<<"$reviews")
  commit=$(jq -r ".[$i].commit // \"\"" <<<"$reviews")

  # A review somebody dismissed is a review that was taken back.
  # A review taken back, and a draft only its author can see. Neither is
  # somebody having reviewed this pull request.
  [ "$state" = DISMISSED ] && continue
  [ "$state" = PENDING ] && continue

  # The author's own report is recognised first. That ordering was once what
  # kept a report quoting the refusal sentences from being eaten by them; since
  # `is_refusal` became a question about the reviewer rather than about prose, it
  # no longer carries that weight, and reverting it alone breaks no test. It is
  # kept because "is this the author's own report" is the clearer thing to ask
  # first, not because anything now depends on the order.
  if [ "$author" = "$AUTHOR" ]; then
    case $body in
      *"$PROVENANCE"*)
        self_review=$((self_review + 1))
        [ -n "$HEAD_SHA" ] && [ "$commit" = "$HEAD_SHA" ] && at_head=$((at_head + 1))
        continue
        ;;
    esac
    # Any other review by the author is an approval of their own code, which is
    # the thing being guarded against rather than a way past it.
    continue
  fi

  if is_refusal "$author" "$body"; then
    refusals=$((refusals + 1))
    continue
  fi

  # A second party either said something, or reached a verdict. An APPROVED or
  # CHANGES_REQUESTED with no prose is still somebody who read it and pressed a
  # button; an empty COMMENTED is not distinguishable from a drive-by without
  # fetching the inline comments, so it does not count on its own.
  if [ -n "${body//[[:space:]]/}" ] || [ "$state" = APPROVED ] ||
     [ "$state" = CHANGES_REQUESTED ]; then
    second_party=$((second_party + 1))
    [ -n "$HEAD_SHA" ] && [ "$commit" = "$HEAD_SHA" ] && at_head=$((at_head + 1))
  fi
done

# Warned, not failed. A review of an earlier commit *did happen* -- that is a
# different thing from the absence this guard exists to catch, and failing it
# would mean re-reviewing after every typo fix, which is how a guard earns being
# deleted. What it must not do is pass in silence.
stale_notice() {
  [ -n "$HEAD_SHA" ] || return 0
  [ "$at_head" -gt 0 ] && return 0
  echo "::warning::Every review here predates the current head ($HEAD_SHA). The"\
       "code that merges is not the code that was reviewed; re-review if the"\
       "later commits changed anything that matters."
}

if [ "$second_party" -gt 0 ]; then
  echo "reviewed by $second_party review(s) from somebody other than the author"
  stale_notice
  exit 0
fi

if [ "$self_review" -gt 0 ]; then
  echo "::notice::No second-party review: merging on $self_review self-review(s)."\
       "The external reviewer is unavailable or found nothing to say, and the"\
       "author's own wf-review report is what this merge rests on."
  stale_notice
  exit 0
fi

if [ "$refusals" -gt 0 ]; then
  echo "::error::The external reviewer refused (quota or diff size) and there is"\
       "no self-review to stand in for it. Post a wf-review report on this pull"\
       "request and re-run this job, or label '$OVERRIDE' to merge unreviewed."
  exit 1
fi

echo "::error::Nothing reviewed this pull request. Post a wf-review report and"\
     "re-run this job, or label '$OVERRIDE' to merge unreviewed."
exit 1
