#!/usr/bin/env bash
# The verdict on whether a pull request was actually reviewed by anything.
#
# Separate from the workflow that calls it so the classification is executable
# outside CI, which is what `test/test_review_guard.py` executes. A `case`
# statement living only inside a `run:` block is testable only by copying it, and
# a copied guard is a guard that drifts.
#
# Reads the PR's reviews on stdin as a JSON array of {author, body}, and the PR's
# author in $PR_AUTHOR. Exit 0 means somebody or something reviewed the code;
# exit 1 means nothing did, and the reason goes to stdout as a workflow-command
# error so it annotates the pull request rather than only a log nobody opens.
#
# ## What counts
#
# A review by someone *other than the author* counts on its own -- that is a
# second party looking, which is the thing worth having.
#
# A review by the author counts only if it carries the provenance line that
# `wf-review` writes. That is not ceremony: the line marks a two-axis report
# produced in fresh context that did not see the code written, and the
# distinction it draws is exactly the one that matters here -- between a review
# and "lgtm" typed by the person who wrote it. Anyone determined can still write
# the line, but the guard is against a review silently not happening, not against
# a person deciding to skip one; that decision has a label.
set -euo pipefail

OVERRIDE=${OVERRIDE_LABEL:-no-external-review}
AUTHOR=${PR_AUTHOR:-}
# `wf-review`'s provenance line, matched on its stable middle rather than whole
# so a change of emphasis or a trailing period does not silently stop counting.
PROVENANCE="generated by AI during"

reviews=$(cat)
if [ -z "${reviews//[[:space:]]/}" ]; then
  reviews='[]'
fi

# Both refusals are quota refusals, and neither says anything about the code. The
# second fires on *size*, so it exempts exactly the changes least safe to merge
# unread. Matched on the stable half of each sentence: the numbers move when the
# plan does, and the account name is not fixed.
is_refusal() {
  case $1 in
    *"you have reached your weekly rate limit"*) return 0 ;;
    *"larger than the review limit"*) return 0 ;;
  esac
  return 1
}

count=$(jq 'length' <<<"$reviews")
second_party=0
self_review=0
refusals=0

for i in $(seq 0 $((count - 1))); do
  [ "$count" -eq 0 ] && break
  author=$(jq -r ".[$i].author // \"\"" <<<"$reviews")
  body=$(jq -r ".[$i].body // \"\"" <<<"$reviews")

  if is_refusal "$body"; then
    refusals=$((refusals + 1))
    continue
  fi
  [ -z "${body//[[:space:]]/}" ] && continue

  if [ -n "$AUTHOR" ] && [ "$author" = "$AUTHOR" ]; then
    case $body in
      *"$PROVENANCE"*) self_review=$((self_review + 1)) ;;
    esac
  else
    second_party=$((second_party + 1))
  fi
done

if [ "$second_party" -gt 0 ]; then
  echo "reviewed by $second_party review(s) from somebody other than the author"
  exit 0
fi

if [ "$self_review" -gt 0 ]; then
  echo "::notice::No second-party review: merging on $self_review self-review(s)."\
       "The external reviewer is unavailable or found nothing to say, and the"\
       "author's own wf-review report is what this merge rests on."
  exit 0
fi

if [ "$refusals" -gt 0 ]; then
  echo "::error::The external reviewer refused (quota or diff size) and there is"\
       "no self-review to stand in for it. Post a wf-review report on this pull"\
       "request, or label '$OVERRIDE' to merge unreviewed."
  exit 1
fi

echo "::error::Nothing reviewed this pull request. Post a wf-review report, or"\
     "label '$OVERRIDE' to merge unreviewed."
exit 1
