//! The completion cache: what the shell offers, and how stale it is allowed to be.
//!
//! Two files in devlaunch's cache directory, written together and read by
//! different things:
//!
//! - `completions.json` — the machine-readable copy. `dl --completion-data` hands
//!   it back verbatim and `dl --repos` reads its `repos` list. It also carries the
//!   clock: the file's own mtime is the freshness timestamp.
//! - `completions.bash` — four shell assignments the shipped completion script
//!   sources. That script spells the path as
//!   `${XDG_CACHE_HOME:-$HOME/.cache}/devlaunch/completions.bash` and nothing
//!   negotiates it at runtime, which is what `flows::completion`'s
//!   `the_payload_reads_the_cache_the_listing_side_writes` pins from the other
//!   side.
//!
//! Ported from `dl.py`'s `_get_cache_dir`, `read_completion_cache`,
//! `write_completion_cache`, `write_bash_completion_cache`,
//! `get_remote_branches`, `get_local_branches`, `update_completion_cache`,
//! `completion_cache_age_seconds`, `completion_cache_is_fresh` and
//! `wants_startup_cache_refresh`; see docs/rust-rewrite-plan.md (M5).
//!
//! # Why an hour
//!
//! Refreshing means a `git ls-remote` per known repo, so doing it on every
//! invocation costs seconds of machine for a list of names that barely moves. An
//! hour mirrors the worktree config's `fetch_interval`, which already decides how
//! stale devlaunch is willing to let its view of a repo's branches get — and
//! branch names are exactly what the expensive part of this refresh collects, so
//! the two should agree. `dl --refresh` remains the escape hatch when a user wants
//! it now.
//!
//! The timestamp is the file's mtime rather than a field inside it: the write
//! renames the finished file into place, so mtime marks a *completed* refresh;
//! caches written by earlier versions carry no timestamp field and would otherwise
//! read as infinitely stale; and a `stat` keeps the check free on the path whose
//! entire purpose is to do no work.
//!
//! # What is deliberately not here
//!
//! - **The background self-spawn.** Python's `update_cache_background` forks
//!   `python -m devlaunch.dl --update-cache` and forgets it. Which program to
//!   re-exec is the binary's own name, so it lands with the binary (M6).
//! - **The repo-fetch sweep.** `sweep_repo_fetches` shares the detached child with
//!   this refresh but does something else entirely — it fetches the bare clones
//!   under the repo locks — and belongs with the storage flows (M6).

use std::collections::BTreeSet;
use std::io;
use std::path::{Path, PathBuf};
use std::time::{Duration, SystemTime};

use serde::{Deserialize, Serialize};

use crate::clients::devpod::ListingUnreadable;
use crate::clients::git::Git;
use crate::flows::listing::{self, CommandContext, UnreadableSource, json_as_python_writes_it};

/// How long a completion cache is considered current.
pub(crate) const COMPLETION_CACHE_TTL: Duration = Duration::from_secs(3600);

/// The JSON cache's file name, under devlaunch's cache directory.
const CACHE_FILE: &str = "completions.json";

/// The shell-sourceable cache's file name. The shipped completion script has this
/// path built in.
const BASH_CACHE_FILE: &str = "completions.bash";

/// The first line of `completions.bash`, so a person who opens it knows not to.
const BASH_HEADER: &str = "# Auto-generated by dl - do not edit";

/// The JSON cache inside *cache_dir*.
pub fn cache_path(cache_dir: &Path) -> PathBuf {
    cache_dir.join(CACHE_FILE)
}

/// The shell cache inside *cache_dir*.
pub(crate) fn bash_cache_path(cache_dir: &Path) -> PathBuf {
    cache_dir.join(BASH_CACHE_FILE)
}

/// What the shell may complete: four lists, in the order the cache carries them.
///
/// The field names are the JSON keys, and the order is the key order — the cutover
/// checklist requires both binaries to write this file identically, so this
/// declaration is the wire format.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct CompletionData {
    /// Every devpod workspace id.
    #[serde(default)]
    pub workspaces: Vec<String>,
    /// Every known `owner/repo`, sorted.
    #[serde(default)]
    pub repos: Vec<String>,
    /// Every known owner, sorted.
    #[serde(default)]
    pub owners: Vec<String>,
    /// Every known `owner/repo@branch`, sorted within each repo.
    #[serde(default)]
    pub branches: Vec<String>,
}

impl CompletionData {
    /// The document as `dl --completion-data` prints it: one line, Python's
    /// spacing.
    pub fn as_json_line(&self) -> String {
        json_as_python_writes_it(
            &serde_json::to_value(self).unwrap_or_else(|_| serde_json::json!({})),
        )
    }

    /// The shell file's four assignments, with the do-not-edit header.
    ///
    /// Space-joined inside double quotes, which is what `compgen -W` wants — and
    /// which is why a branch name with a space in it could not be completed
    /// either before or after the port.
    pub(crate) fn as_bash(&self) -> String {
        let mut text = String::from(BASH_HEADER);
        for (name, values) in [
            ("DL_WORKSPACES", &self.workspaces),
            ("DL_REPOS", &self.repos),
            ("DL_OWNERS", &self.owners),
            ("DL_BRANCHES", &self.branches),
        ] {
            text.push_str(&format!("\n{name}=\"{}\"", values.join(" ")));
        }
        text.push('\n');
        text
    }
}

/// Read the cache, or nothing when there is none to read.
///
/// A file that is not there, cannot be opened, or is not the document this build
/// writes all answer the same thing: there is no cache. That is what Python
/// answers too — its readers then either fall back to asking devpod
/// (`--completion-data`, `--repos`) or refresh.
pub fn read_completion_cache(path: &Path) -> Option<CompletionData> {
    let text = std::fs::read_to_string(path).ok()?;
    serde_json::from_str(&text).ok()
}

/// Write the JSON cache, atomically.
///
/// Written to a temp file in the same directory and renamed over the real path, so
/// an interrupted write cannot leave a half-cache behind and mtime marks a
/// *completed* refresh.
pub(crate) fn write_completion_cache(path: &Path, data: &CompletionData) -> io::Result<()> {
    write_atomically(path, &data.as_json_line())
}

/// Write the shell cache, atomically.
pub(crate) fn write_bash_completion_cache(path: &Path, data: &CompletionData) -> io::Result<()> {
    write_atomically(path, &data.as_bash())
}

/// *text* into *path*, via a temp file in the same directory.
///
/// **The temp file's name is Python's, and Python's is a hazard.** Python builds it
/// with `Path.with_suffix(".tmp")`, which *replaces* the extension — so
/// `completions.json` and `completions.bash` both stage through
/// `completions.tmp`. Two refreshes running at once can therefore have one's bash
/// text renamed over the other's JSON cache. It is reproduced rather than fixed
/// because a fix is a behavioural divergence and those are numbered in
/// docs/rust-rewrite-plan.md; this comment is the note asking for a row. Nothing
/// is corrupted beyond one cache file, and the next refresh rewrites it.
fn write_atomically(path: &Path, text: &str) -> io::Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    let staged = path.with_extension("tmp");
    std::fs::write(&staged, text)?;
    std::fs::rename(&staged, path)
}

/// How long ago the cache was written, or nothing when there is no cache.
///
/// Never negative: a cache stamped in the future is zero seconds old, as Python's
/// `max(0.0, …)` makes it, rather than an error a caller would have to have an
/// answer for.
pub(crate) fn completion_cache_age(path: &Path, now: SystemTime) -> Option<Duration> {
    let modified = std::fs::metadata(path)
        .and_then(|meta| meta.modified())
        .ok()?;
    Some(now.duration_since(modified).unwrap_or(Duration::ZERO))
}

/// Whether the cache is new enough to leave alone.
pub fn completion_cache_is_fresh(path: &Path) -> bool {
    is_fresh_at(path, SystemTime::now())
}

fn is_fresh_at(path: &Path, now: SystemTime) -> bool {
    completion_cache_age(path, now).is_some_and(|age| age < COMPLETION_CACHE_TTL)
}

/// The commands that read the completion cache without changing what it describes.
const CACHE_READING_COMMANDS: [&str; 3] = ["--ls", "--repos", "--completion-data"];

/// Whether this invocation should warm the completion cache before running.
///
/// Only the commands that read the cache and leave the workspace list alone.
/// Everything else either has no use for completions (`--help`, `--version`), owns
/// the refresh itself (`--install`, `--refresh`, `--update-cache`), is about to
/// delete the cache directory (`--purge`), or is a workspace command — and those
/// refresh once they are finished, when the workspace list they cache is final,
/// instead of indexing the state they are about to replace.
///
/// No arguments at all is the fuzzy picker, which is a view of the workspace list.
///
/// A pure predicate over argv, and deliberately over *argv* rather than over parsed
/// arguments: the decision has to be made before the command runs, and `dl --help`
/// must not pay for a refresh it has no use for.
pub fn wants_startup_cache_refresh<S: AsRef<str>>(args: &[S]) -> bool {
    match args.first() {
        None => true,
        Some(first) => CACHE_READING_COMMANDS.contains(&first.as_ref()),
    }
}

/// One cache file that could not be written, and what the OS said.
///
/// Python swallows these (`except OSError: pass`) and it is right to: a cache that
/// could not be written is not a reason to fail the command that was warming it.
/// They are carried out rather than dropped so a caller *may* say so.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct CacheNotWritten {
    pub path: PathBuf,
    pub reason: String,
}

/// What a refresh collected, and what it could not.
pub struct Refreshed {
    pub data: CompletionData,
    /// Why the workspace names are missing, when they are.
    ///
    /// The one reader of the workspace list that has something to do with a
    /// listing it cannot read. Everywhere else an unreadable listing means the
    /// question cannot be answered at all; here the workspace names are one of
    /// four things being collected and the other three come off the local disk, so
    /// this builds completions out of what it can still see. Refusing would mean an
    /// unreachable devpod stops `dl --install` from installing completions at all,
    /// when what it costs is the workspace names.
    ///
    /// Carried rather than swallowed because `dl --refresh` prints the workspace
    /// count it got, and zero-because-we-could-not-ask must not read as
    /// zero-because-there-are-none.
    pub listing_refused: Option<ListingUnreadable>,
    /// Workspaces whose source devlaunch could not read, so a caller can say which.
    pub unreadable_sources: Vec<UnreadableSource>,
    pub not_written: Vec<CacheNotWritten>,
}

/// Rebuild the completion cache and write both files.
///
/// The workspace names come from devpod; the repos, owners and branches come off
/// the local disk and a `git ls-remote` per repo. Everything is sorted, so two
/// refreshes that saw the same world write the same bytes.
pub fn update_completion_cache(
    context: &mut CommandContext<'_>,
    cache_dir: &Path,
    repos_dir: &Path,
) -> Refreshed {
    let (workspaces, listing_refused) = match context.workspaces() {
        Ok(workspaces) => (workspaces, None),
        Err(refused) => (Vec::new(), Some(refused)),
    };
    let git = context.git();
    let mut discovered = listing::discover_repos_from_workspaces(&git, &workspaces);
    // Merged so that repos cloned locally — even without a devpod workspace yet —
    // appear in completions.
    listing::merge_repos(
        &mut discovered.repos,
        &listing::discover_repos_from_cache_dir(repos_dir),
    );

    let repos = listing::flatten_repos(&discovered.repos);
    let owners = listing::owners_of(&discovered.repos);
    let mut branches = Vec::new();
    for owner_repo in &repos {
        for branch in branches_of(&git, repos_dir, owner_repo) {
            branches.push(format!("{owner_repo}@{branch}"));
        }
    }

    let data = CompletionData {
        workspaces: workspaces
            .into_iter()
            .map(|workspace| workspace.id)
            .collect(),
        repos,
        owners,
        branches,
    };
    let mut not_written = Vec::new();
    for (path, written) in [
        (
            cache_path(cache_dir),
            write_completion_cache(&cache_path(cache_dir), &data),
        ),
        (
            bash_cache_path(cache_dir),
            write_bash_completion_cache(&bash_cache_path(cache_dir), &data),
        ),
    ] {
        if let Err(reason) = written {
            not_written.push(CacheNotWritten {
                path,
                reason: reason.to_string(),
            });
        }
    }
    Refreshed {
        data,
        listing_refused,
        unreadable_sources: discovered.unreadable,
        not_written,
    }
}

/// Every branch of one `owner/repo` worth completing, deduplicated and sorted.
///
/// Remote and local are merged so a branch created by `dl owner/repo@new-branch`
/// completes before it has been pushed anywhere.
fn branches_of(git: &Git<'_>, repos_dir: &Path, owner_repo: &str) -> BTreeSet<String> {
    let mut branches: BTreeSet<String> = remote_branches(git, owner_repo).into_iter().collect();
    branches.extend(local_branches(git, repos_dir, owner_repo));
    branches
}

/// The branches a GitHub repo has, asked over ssh with a five-second ceiling.
///
/// A refusal — no network, no key, a repo that is not there — is an empty list
/// rather than an error: it costs those branch names their completion and nothing
/// else.
pub(crate) fn remote_branches(git: &Git<'_>, owner_repo: &str) -> Vec<String> {
    git.ls_remote_heads_of(&format!("git@github.com:{owner_repo}.git"))
        .said()
        .unwrap_or_default()
}

/// The branches the bare clone in the cache holds.
///
/// No bare clone means no branches and no spawn: this runs once per known repo on
/// a path whose whole point is to be cheap.
pub(crate) fn local_branches(git: &Git<'_>, repos_dir: &Path, owner_repo: &str) -> Vec<String> {
    let Some((owner, repo)) = owner_repo.split_once('/') else {
        return Vec::new();
    };
    let bare = repos_dir.join(owner).join(repo).join(".bare");
    if !bare.is_dir() {
        return Vec::new();
    }
    git.local_branches(&bare).said().unwrap_or_default()
}

#[cfg(test)]
mod tests {
    //! Ported from `test/test_dl.py`'s `TestCacheFunctions`,
    //! `TestCompletionCacheFreshness`, `TestNoRefreshForCacheFreeCommands` and
    //! `TestCacheReadingCommandsWarmTheCache`, plus
    //! `test/unit/test_workspace_listing.py::TestCompletionsAreBuiltFromWhateverCanBeRead`.
    //!
    //! The two files' bytes are goldens: they were read off a scratch cache written
    //! by the Python build, run against the devpod shim.
    //!
    //! The classes about *spawning* the refresh (`TestBackgroundRefreshSpawning`,
    //! `TestRefreshChildRechecksFreshness`, `TestWorkspaceCommandsRefreshOnceAfterwards`)
    //! are about `update_cache_background`, which re-execs the binary and so lands
    //! with it (M6). What is here is the predicate they turn on
    //! ([`wants_startup_cache_refresh`]) and the TTL they consult.

    use std::path::PathBuf;

    use devlaunch_test_support::{FakeRunner, Response, WorkspaceState};

    use super::*;

    fn temp_dir() -> tempfile::TempDir {
        tempfile::tempdir().expect("a temporary directory")
    }

    fn data() -> CompletionData {
        CompletionData {
            workspaces: vec!["ws1".into(), "ws2".into()],
            repos: vec!["a/b".into()],
            owners: vec!["a".into()],
            branches: vec!["a/b@main".into(), "a/b@feature/x".into()],
        }
    }

    fn read(path: &Path) -> String {
        std::fs::read_to_string(path).expect("a written file")
    }

    // ------------------------------------------------------------ the two files

    #[test]
    fn the_ttl_mirrors_the_lazy_fetch_interval() {
        // One hour: the same staleness the worktree config already allows a repo.
        assert_eq!(COMPLETION_CACHE_TTL, Duration::from_secs(3600));
    }

    #[test]
    fn the_caches_live_where_the_shipped_completion_script_looks() {
        let cache = PathBuf::from("/xdg/cache/devlaunch");

        assert_eq!(cache_path(&cache), cache.join("completions.json"));
        assert_eq!(bash_cache_path(&cache), cache.join("completions.bash"));
    }

    #[test]
    fn a_cache_written_is_a_cache_read_back() {
        let root = temp_dir();
        let path = cache_path(root.path());

        write_completion_cache(&path, &data()).expect("the cache is written");

        assert_eq!(read_completion_cache(&path), Some(data()));
    }

    #[test]
    fn there_is_no_cache_where_no_file_is() {
        let root = temp_dir();

        assert_eq!(read_completion_cache(&cache_path(root.path())), None);
    }

    #[test]
    fn a_file_that_is_not_a_cache_reads_as_no_cache() {
        let root = temp_dir();
        let path = cache_path(root.path());
        std::fs::write(&path, "not json").expect("a file");

        assert_eq!(read_completion_cache(&path), None);
    }

    #[test]
    fn the_json_cache_is_the_bytes_python_writes() {
        // Golden: a scratch `completions.json` written by the Python build. Python's
        // `json.dump` defaults mean `", "` and `": "` separators and no trailing
        // newline, and the cutover checklist requires both binaries to write this
        // file identically.
        let root = temp_dir();
        let path = cache_path(root.path());
        let empty = CompletionData::default();

        write_completion_cache(&path, &empty).expect("the cache is written");
        assert_eq!(
            read(&path),
            r#"{"workspaces": [], "repos": [], "owners": [], "branches": []}"#
        );

        write_completion_cache(
            &path,
            &CompletionData {
                workspaces: vec!["dl-ws".into()],
                repos: vec!["blooop/devlaunch".into(), "other/proj".into()],
                owners: vec!["blooop".into(), "other".into()],
                branches: vec!["blooop/devlaunch@main".into()],
            },
        )
        .expect("the cache is written");
        assert_eq!(
            read(&path),
            r#"{"workspaces": ["dl-ws"], "repos": ["blooop/devlaunch", "other/proj"], "owners": ["blooop", "other"], "branches": ["blooop/devlaunch@main"]}"#
        );
    }

    #[test]
    fn the_bash_cache_is_the_bytes_python_writes() {
        // Golden: a scratch `completions.bash` written by the Python build. The
        // shipped completion script `source`s this, so the four names, the quoting
        // and the space joining are the contract.
        let root = temp_dir();
        let path = bash_cache_path(root.path());

        write_bash_completion_cache(
            &path,
            &CompletionData {
                workspaces: vec!["dl-ws".into()],
                repos: vec!["blooop/devlaunch".into(), "other/proj".into()],
                owners: vec!["blooop".into(), "other".into()],
                branches: vec!["blooop/devlaunch@main".into(), "other/proj@main".into()],
            },
        )
        .expect("the cache is written");

        assert_eq!(
            read(&path),
            concat!(
                "# Auto-generated by dl - do not edit\n",
                "DL_WORKSPACES=\"dl-ws\"\n",
                "DL_REPOS=\"blooop/devlaunch other/proj\"\n",
                "DL_OWNERS=\"blooop other\"\n",
                "DL_BRANCHES=\"blooop/devlaunch@main other/proj@main\"\n",
            )
        );
    }

    #[test]
    fn an_empty_cache_still_declares_all_four_names() {
        // The script initialises them itself, but a cache that dropped a name would
        // leave the previous shell's value standing.
        let bash = CompletionData::default().as_bash();

        for name in ["DL_WORKSPACES", "DL_REPOS", "DL_OWNERS", "DL_BRANCHES"] {
            assert!(bash.contains(&format!("{name}=\"\"")), "{bash}");
        }
    }

    #[test]
    fn both_caches_stage_through_the_same_temp_file() {
        // Python builds the temp name with `Path.with_suffix(".tmp")`, which
        // *replaces* the extension, so `completions.json` and `completions.bash`
        // both stage through `completions.tmp`. Reproduced rather than fixed —
        // fixing it is a behavioural divergence and those are numbered in
        // docs/rust-rewrite-plan.md — and pinned here so the row has something to
        // point at. Two refreshes at once can have one's bash text renamed over the
        // other's JSON cache.
        let root = temp_dir();

        assert_eq!(
            cache_path(root.path()).with_extension("tmp"),
            bash_cache_path(root.path()).with_extension("tmp")
        );
        assert_eq!(
            cache_path(root.path()).with_extension("tmp"),
            root.path().join("completions.tmp")
        );
    }

    #[test]
    fn a_write_leaves_no_temp_file_behind() {
        let root = temp_dir();

        write_completion_cache(&cache_path(root.path()), &data()).expect("written");
        write_bash_completion_cache(&bash_cache_path(root.path()), &data()).expect("written");

        assert!(!root.path().join("completions.tmp").exists());
    }

    #[test]
    fn a_cache_directory_that_is_not_there_yet_is_made() {
        let root = temp_dir();
        let cache = root.path().join("deep").join("devlaunch");

        write_completion_cache(&cache_path(&cache), &data()).expect("written");

        assert!(cache_path(&cache).is_file());
    }

    #[test]
    fn the_completion_data_line_is_the_json_python_prints() {
        assert_eq!(
            CompletionData {
                workspaces: vec!["ws1".into()],
                repos: vec![],
                owners: vec![],
                branches: vec![],
            }
            .as_json_line(),
            r#"{"workspaces": ["ws1"], "repos": [], "owners": [], "branches": []}"#
        );
    }

    // ------------------------------------------------------------- freshness

    #[test]
    fn a_just_written_cache_is_fresh() {
        let root = temp_dir();
        let path = cache_path(root.path());
        write_completion_cache(&path, &data()).expect("written");

        assert!(completion_cache_is_fresh(&path));
        assert!(
            completion_cache_age(&path, SystemTime::now()).expect("an age") < COMPLETION_CACHE_TTL
        );
    }

    #[test]
    fn a_cache_older_than_the_ttl_is_stale() {
        let root = temp_dir();
        let path = cache_path(root.path());
        write_completion_cache(&path, &data()).expect("written");

        let later = SystemTime::now() + COMPLETION_CACHE_TTL + Duration::from_secs(60);

        assert!(!is_fresh_at(&path, later));
    }

    #[test]
    fn a_cache_just_inside_the_ttl_is_fresh() {
        let root = temp_dir();
        let path = cache_path(root.path());
        write_completion_cache(&path, &data()).expect("written");

        let later = SystemTime::now() + COMPLETION_CACHE_TTL - Duration::from_secs(60);

        assert!(is_fresh_at(&path, later));
    }

    #[test]
    fn a_missing_cache_is_not_fresh() {
        let root = temp_dir();

        let path = cache_path(root.path());
        assert_eq!(completion_cache_age(&path, SystemTime::now()), None);
        assert!(!completion_cache_is_fresh(&path));
    }

    #[test]
    fn freshness_follows_the_file_and_not_its_contents() {
        // mtime is the timestamp, so a cache written by an older dl — which carried
        // no timestamp field at all — still counts as fresh rather than as
        // infinitely stale.
        let root = temp_dir();
        let path = cache_path(root.path());
        std::fs::write(&path, "{}").expect("a file");

        assert!(completion_cache_is_fresh(&path));
    }

    #[test]
    fn a_cache_stamped_in_the_future_is_no_seconds_old_rather_than_an_error() {
        let root = temp_dir();
        let path = cache_path(root.path());
        write_completion_cache(&path, &data()).expect("written");

        let earlier = SystemTime::now() - Duration::from_secs(600);

        assert_eq!(completion_cache_age(&path, earlier), Some(Duration::ZERO));
        assert!(is_fresh_at(&path, earlier));
    }

    // --------------------------------------------------- the startup predicate

    #[test]
    fn the_commands_that_read_the_cache_warm_it() {
        for command in ["--ls", "--repos", "--completion-data"] {
            assert!(wants_startup_cache_refresh(&[command]), "{command}");
        }
        // The fuzzy picker is a view of the workspace list.
        let nothing: [&str; 0] = [];
        assert!(wants_startup_cache_refresh(&nothing));
    }

    #[test]
    fn everything_else_warms_nothing() {
        for command in [
            // No use for completions.
            "--help",
            "-h",
            "--version",
            // Owns the refresh itself.
            "--install",
            "--refresh",
            "--update-cache",
            // About to delete the cache directory.
            "--purge",
            // Other commands that change the workspace list.
            "--prune",
            "--reconcile",
            // A workspace command refreshes afterwards, when the list is final,
            // rather than indexing the state it is about to replace.
            "myws",
            "owner/repo@branch",
            "./path",
        ] {
            assert!(!wants_startup_cache_refresh(&[command]), "{command}");
        }
    }

    #[test]
    fn only_the_first_argument_decides() {
        // `dl --ls --size --json` warms; `dl myws -- --ls` does not.
        assert!(wants_startup_cache_refresh(&["--ls", "--size", "--json"]));
        assert!(!wants_startup_cache_refresh(&["myws", "--", "--ls"]));
    }

    // ----------------------------------------------------------- the refresh

    /// A cache directory with bare clones under it, and a fake devpod and git.
    struct Refresher {
        root: tempfile::TempDir,
        fake: FakeRunner,
    }

    impl Refresher {
        fn new() -> Self {
            Self {
                root: temp_dir(),
                fake: FakeRunner::new(),
            }
        }

        fn cache(&self) -> PathBuf {
            self.root.path().join("cache").join("devlaunch")
        }

        fn repos_dir(&self) -> PathBuf {
            self.cache().join("repos")
        }

        /// A bare clone in the cache, which is what makes a repo "known" with no
        /// devpod workspace for it.
        fn with_bare(&self, owner: &str, repo: &str) -> &Self {
            std::fs::create_dir_all(self.repos_dir().join(owner).join(repo).join(".bare"))
                .expect("a bare clone");
            self
        }

        fn refresh(&self) -> Refreshed {
            let mut context = CommandContext::new(&self.fake);
            update_completion_cache(&mut context, &self.cache(), &self.repos_dir())
        }
    }

    /// `git ls-remote --heads` output for some branches.
    fn ls_remote(branches: &[&str]) -> String {
        branches
            .iter()
            .enumerate()
            .map(|(index, branch)| format!("{index:040}\trefs/heads/{branch}\n"))
            .collect()
    }

    #[test]
    fn a_refresh_collects_workspaces_repos_owners_and_branches() {
        let scene = Refresher::new();
        scene.with_bare("blooop", "devlaunch");
        scene
            .fake
            .add_workspace_from("dl-ws", "github.com/zowner/zrepo", WorkspaceState::Stopped);
        scene.fake.script(
            [
                "git",
                "ls-remote",
                "--heads",
                "git@github.com:blooop/devlaunch.git",
            ],
            Response::stdout(ls_remote(&["main", "release/0.1"])),
        );
        scene.fake.script(
            [
                "git",
                "ls-remote",
                "--heads",
                "git@github.com:zowner/zrepo.git",
            ],
            Response::stdout(ls_remote(&["main"])),
        );
        scene.fake.script(
            ["git", "for-each-ref"],
            Response::stdout("main\nfeature/x\n"),
        );

        let refreshed = scene.refresh();

        assert_eq!(refreshed.data.workspaces, ["dl-ws"]);
        assert_eq!(refreshed.data.repos, ["blooop/devlaunch", "zowner/zrepo"]);
        assert_eq!(refreshed.data.owners, ["blooop", "zowner"]);
        assert_eq!(
            refreshed.data.branches,
            [
                // Remote and local, merged and sorted, with `main` counted once.
                "blooop/devlaunch@feature/x",
                "blooop/devlaunch@main",
                "blooop/devlaunch@release/0.1",
                // No bare clone for this one, so no local branches and no spawn.
                "zowner/zrepo@main",
            ]
        );
        assert!(refreshed.listing_refused.is_none());
        assert!(refreshed.not_written.is_empty());
    }

    #[test]
    fn a_refresh_writes_both_files() {
        let scene = Refresher::new();
        scene
            .fake
            .add_workspace_from("dl-ws", "/somewhere/else", WorkspaceState::Stopped);

        let refreshed = scene.refresh();

        assert_eq!(
            read_completion_cache(&cache_path(&scene.cache())),
            Some(refreshed.data.clone())
        );
        assert_eq!(
            read(&bash_cache_path(&scene.cache())),
            refreshed.data.as_bash()
        );
    }

    #[test]
    fn a_repo_with_no_bare_clone_costs_no_local_spawn() {
        let scene = Refresher::new();
        scene
            .fake
            .add_workspace_from("dl-ws", "github.com/o/r", WorkspaceState::Stopped);
        scene
            .fake
            .script(["git", "ls-remote"], Response::stdout(""));

        scene.refresh();

        assert!(
            !scene
                .fake
                .args_to("git")
                .iter()
                .any(|argv| argv[0] == "for-each-ref"),
            "{:?}",
            scene.fake.args_to("git")
        );
    }

    #[test]
    fn completions_are_built_from_whatever_can_be_read() {
        // The one reader of the workspace list that has something to do with a
        // listing it cannot read: the workspace names are one of four things being
        // collected, and the other three come off the local disk. Refusing would
        // mean an unreachable devpod stops `dl --install` from installing
        // completions at all.
        let scene = Refresher::new();
        scene.with_bare("blooop", "devlaunch");
        scene.fake.script(
            ["devpod", "list"],
            Response::failed(1, "context not found\n"),
        );
        scene
            .fake
            .script(["git", "ls-remote"], Response::stdout(""));

        let refreshed = scene.refresh();

        assert_eq!(refreshed.data.repos, ["blooop/devlaunch"]);
        assert!(refreshed.data.workspaces.is_empty());
        // Not swallowed: `dl --refresh` prints the workspace count it got, and
        // zero-because-we-could-not-ask must not read as zero-because-there-are-none.
        match refreshed.listing_refused {
            Some(ListingUnreadable::Failed { stderr, .. }) => {
                assert!(stderr.contains("context not found"), "{stderr}");
            }
            other => panic!("expected the refusal to travel, got {other:?}"),
        }
        // And the caches are still written, so completion still offers the repos.
        assert!(cache_path(&scene.cache()).is_file());
        assert!(bash_cache_path(&scene.cache()).is_file());
    }

    #[test]
    fn a_source_discovery_could_not_read_is_carried_out_of_the_refresh() {
        let scene = Refresher::new();
        scene.fake.script(
            ["devpod", "list"],
            Response::stdout(
                serde_json::json!([{ "id": "ws-42", "source": { "image": "ubuntu:24.04" } }])
                    .to_string(),
            ),
        );

        let refreshed = scene.refresh();

        assert_eq!(refreshed.data.workspaces, ["ws-42"]);
        assert_eq!(
            refreshed.unreadable_sources,
            [UnreadableSource {
                workspace_id: "ws-42".into(),
                payload: r#"{"image": "ubuntu:24.04"}"#.into(),
            }]
        );
    }

    #[test]
    fn a_repo_whose_remote_cannot_be_reached_costs_its_branches_and_nothing_else() {
        let scene = Refresher::new();
        scene.with_bare("blooop", "devlaunch");
        scene.fake.script(
            ["git", "ls-remote"],
            Response::failed(128, "ssh: Could not resolve hostname\n"),
        );
        scene
            .fake
            .script(["git", "for-each-ref"], Response::stdout("main\n"));

        let refreshed = scene.refresh();

        assert_eq!(refreshed.data.repos, ["blooop/devlaunch"]);
        assert_eq!(refreshed.data.branches, ["blooop/devlaunch@main"]);
    }

    #[test]
    fn a_refresh_of_an_empty_machine_writes_four_empty_lists() {
        let scene = Refresher::new();

        let refreshed = scene.refresh();

        assert_eq!(refreshed.data, CompletionData::default());
        assert_eq!(
            read(&cache_path(&scene.cache())),
            r#"{"workspaces": [], "repos": [], "owners": [], "branches": []}"#
        );
    }

    #[test]
    fn a_refresh_asks_devpod_once() {
        let scene = Refresher::new();
        scene
            .fake
            .add_workspace_from("dl-ws", "/somewhere", WorkspaceState::Stopped);

        scene.refresh();

        assert_eq!(scene.fake.args_to("devpod"), [["list", "--output", "json"]]);
    }

    #[test]
    fn the_remote_branch_url_is_the_ssh_one() {
        let fake = FakeRunner::new();
        fake.script(["git", "ls-remote"], Response::stdout(ls_remote(&["main"])));
        let git = Git::new(&fake);

        assert_eq!(remote_branches(&git, "blooop/devlaunch"), ["main"]);
        assert_eq!(
            fake.args_to("git"),
            [[
                "ls-remote",
                "--heads",
                "git@github.com:blooop/devlaunch.git"
            ]]
        );
    }

    #[test]
    fn local_branches_are_read_from_the_bare_clone() {
        let root = temp_dir();
        let repos = root.path().join("repos");
        std::fs::create_dir_all(repos.join("owner").join("repo").join(".bare"))
            .expect("a bare clone");
        let fake = FakeRunner::new();
        fake.script(
            ["git", "for-each-ref"],
            Response::stdout("main\nfeature/test\ndevelop\n"),
        );
        let git = Git::new(&fake);

        assert_eq!(
            local_branches(&git, &repos, "owner/repo"),
            ["main", "feature/test", "develop"]
        );
    }

    #[test]
    fn a_name_that_is_not_owner_slash_repo_has_no_local_branches() {
        let root = temp_dir();
        let fake = FakeRunner::new();
        let git = Git::new(&fake);

        assert!(local_branches(&git, root.path(), "nameless").is_empty());
        assert!(fake.args_to("git").is_empty());
    }
}
